"""Curated semi-live editorial base for IA Match.

The goal is not to scrape hype in real time. IA Match publishes a stable decision layer:
official/widely-recognized sources + categories + impact + action advice.
Dynamic LLM/news refreshes may be merged only as secondary items.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Dict, List

EDITORIAL_CATEGORIES = [
    {"slug": "modeles", "label": "Modèles", "description": "Nouveaux modèles, capacités, limites et choix entre généralistes."},
    {"slug": "outils", "label": "Outils", "description": "Applications IA concrètes à tester ou éviter selon l’usage."},
    {"slug": "image-video", "label": "Image & vidéo", "description": "Création visuelle, vidéo générative, design et production."},
    {"slug": "code-agents", "label": "Code & agents", "description": "Assistants développeurs, agents, automatisations et workflows."},
    {"slug": "business-prix", "label": "Business / prix", "description": "Plans, budgets, quotas, arbitrages gratuit vs premium."},
    {"slug": "open-local", "label": "Open-source & local", "description": "Modèles ouverts, IA locale, confidentialité et souveraineté."},
    {"slug": "confiance", "label": "Confiance", "description": "Sources, régulation, données, sécurité et vérification."},
    {"slug": "debutants", "label": "Débutants", "description": "Repères pédagogiques pour savoir quoi essayer sans jargon."},
]

EDITORIAL_SOURCES = [
    {"id": "openai-docs", "name": "OpenAI Docs", "url": "https://platform.openai.com/docs", "type": "officiel"},
    {"id": "anthropic-docs", "name": "Anthropic Docs", "url": "https://docs.anthropic.com/", "type": "officiel"},
    {"id": "google-ai-docs", "name": "Google AI for Developers", "url": "https://ai.google.dev/", "type": "officiel"},
    {"id": "mistral-docs", "name": "Mistral AI Docs", "url": "https://docs.mistral.ai/", "type": "officiel"},
    {"id": "meta-llama", "name": "Meta Llama", "url": "https://llama.meta.com/", "type": "officiel"},
    {"id": "ollama", "name": "Ollama", "url": "https://ollama.com/", "type": "outil"},
    {"id": "cursor", "name": "Cursor", "url": "https://cursor.com/", "type": "outil"},
    {"id": "perplexity", "name": "Perplexity", "url": "https://www.perplexity.ai/", "type": "outil"},
    {"id": "eu-ai-act", "name": "EU AI Act", "url": "https://artificialintelligenceact.eu/", "type": "régulation"},
    {"id": "openai-news", "name": "OpenAI News", "url": "https://openai.com/news/", "type": "officiel"},
    {"id": "google-ai-blog", "name": "Google AI Blog", "url": "https://blog.google/technology/ai/", "type": "officiel"},
    {"id": "aws-openai", "name": "AWS / OpenAI", "url": "https://openai.com/index/openai-on-aws", "type": "officiel"},
]

CURATED_EDITORIAL_ARTICLES: List[Dict] = [

    {
        "id": "ed-openai-securite-compte-2026",
        "category": "CONFIANCE",
        "editorialCategory": "confiance",
        "title": "Sécurité des comptes IA : pourquoi les connexions fortes deviennent indispensables",
        "summary": "OpenAI met en avant une sécurité de compte renforcée. Pour un débutant, le message est simple : ton compte IA contient parfois plus d’informations qu’une boîte mail.",
        "intro": "Les assistants IA gardent des conversations, fichiers, préférences et parfois données de travail. Si quelqu’un prend ton compte, il ne récupère pas seulement un mot de passe : il récupère une partie de ton contexte.",
        "body": "## Ce qui change\n\nOpenAI a annoncé des protections de compte plus fortes, avec l’idée de réduire le phishing, les récupérations abusives et les accès non autorisés. Même si tous les utilisateurs ne voient pas les mêmes options au même moment, la tendance est claire : les comptes IA deviennent des comptes sensibles.\n\n## Explication débutant\n\nImagine ton assistant IA comme un carnet de travail. Tu peux y avoir mis des idées business, CV, documents clients, brouillons personnels ou prompts réutilisables. Il faut donc le protéger comme ton email principal.\n\n## Mini-checklist\n\n- Active l’authentification à deux facteurs quand elle existe.\n- Évite de te connecter via des liens reçus par message.\n- Ne colle pas de secrets, mots de passe ou clés API dans une conversation.\n- Sépare compte personnel et compte professionnel si possible.\n\n## Conseil IA Match\n\nAvant de choisir un outil IA pour ton travail, regarde aussi la sécurité du compte, pas seulement la puissance du modèle.",
        "publishedAt": "2026-04-30",
        "readMinutes": 4,
        "tag": "Sécurité",
        "highlight": "Un compte IA devient un espace de travail : protège-le comme tel.",
        "author": "IA Match · Rédaction",
        "impactLevel": "fort",
        "impactLabel": "Impact fort",
        "confidence": "haute",
        "verificationStatus": "official_source_summarized",
        "lastVerifiedAt": "2026-05-04",
        "sourceIds": ["openai-news"],
        "toolSlugs": ["chatgpt", "claude", "gemini", "mistral"],
        "radarStatus": "À faire maintenant",
        "decisionHint": "Si tu stockes des documents ou habitudes dans un assistant, sécurise le compte avant d’automatiser.",
        "action": "Vérifier les paramètres sécurité de ton assistant principal.",
        "tags": ["sécurité", "compte", "débutants"],
    },
    {
        "id": "ed-openai-aws-agents-entreprise",
        "category": "BUSINESS",
        "editorialCategory": "business-prix",
        "title": "OpenAI sur AWS : ce que ça veut dire pour les entreprises, sans jargon cloud",
        "summary": "L’arrivée de modèles OpenAI, Codex et agents managés dans l’écosystème AWS confirme une tendance : l’IA entre dans les outils déjà utilisés par les entreprises.",
        "intro": "Pour un débutant, AWS peut sembler très technique. L’idée à retenir : les entreprises veulent utiliser l’IA là où leurs données, règles de sécurité et équipes travaillent déjà.",
        "body": "## Ce qui change\n\nOpenAI a annoncé la disponibilité de modèles, Codex et agents managés côté AWS. Ce n’est pas seulement une annonce d’infrastructure : c’est un signal que les grandes organisations cherchent des IA intégrées à leurs environnements existants.\n\n## Pourquoi c’est important\n\nUne PME ou une grande entreprise ne choisit pas seulement “le modèle le plus intelligent”. Elle regarde aussi : sécurité, facturation, conformité, outils internes, droits d’accès et support.\n\n## Schéma simple\n\n`Données entreprise → environnement cloud connu → modèle IA → agent contrôlé → validation humaine`\n\n## Conseil IA Match\n\nPour un usage perso, l’app grand public suffit souvent. Pour une équipe, demande toujours où vont les données, qui peut accéder aux prompts et comment les actions de l’agent sont validées.",
        "publishedAt": "2026-04-28",
        "readMinutes": 4,
        "tag": "Entreprise",
        "highlight": "L’IA d’entreprise se gagne autant sur l’intégration que sur le modèle.",
        "author": "IA Match · Rédaction",
        "impactLevel": "moyen",
        "impactLabel": "Business utile",
        "confidence": "haute",
        "verificationStatus": "official_source_summarized",
        "lastVerifiedAt": "2026-05-04",
        "sourceIds": ["openai-news", "aws-openai"],
        "toolSlugs": ["chatgpt", "cursor", "github-copilot"],
        "radarStatus": "À surveiller",
        "decisionHint": "Pour une équipe, compare l’écosystème et la gouvernance autant que la qualité de réponse.",
        "action": "Lister tes contraintes sécurité avant de choisir une IA d’entreprise.",
        "tags": ["business", "agents", "aws", "entreprise"],
    },
    {
        "id": "ed-agents-orchestration-codex-symphony",
        "category": "CODE & AGENTS",
        "editorialCategory": "code-agents",
        "title": "Agents de code orchestrés : la prochaine étape après le simple copilote",
        "summary": "OpenAI parle d’orchestration d’agents Codex. Pour les débutants, retiens ceci : on passe d’un assistant qui répond à un système qui suit des tickets et rend des comptes.",
        "intro": "Un copilote aide pendant que tu travailles. Un agent orchestré peut prendre une tâche, proposer un plan, modifier du code et revenir avec un résultat vérifiable.",
        "body": "## Ce qui change\n\nL’orchestration consiste à relier des agents à un système de suivi : tickets, tâches, validations, logs et retours. L’intérêt n’est pas de rendre l’agent “magique”, mais de rendre son travail contrôlable.\n\n## Schéma simple\n\n`Ticket clair → agent → branche de travail → tests → revue humaine → merge ou correction`\n\n## À retenir si tu débutes\n\nNe commence pas par un agent autonome. Commence par apprendre à écrire une petite tâche précise : objectif, fichiers, contrainte, test attendu. C’est exactement la compétence qui rend les agents utiles ensuite.\n\n## Conseil IA Match\n\nUn outil agentique doit être recommandé avec des garde-fous : Git, tests, revue, limites d’action et journal de décisions.",
        "publishedAt": "2026-04-27",
        "readMinutes": 4,
        "tag": "Agents",
        "highlight": "Le futur du code IA ressemble plus à une équipe contrôlée qu’à un robot libre.",
        "author": "IA Match · Rédaction",
        "impactLevel": "fort",
        "impactLabel": "Workflow utile",
        "confidence": "haute",
        "verificationStatus": "official_source_summarized",
        "lastVerifiedAt": "2026-05-04",
        "sourceIds": ["openai-news"],
        "toolSlugs": ["cursor", "github-copilot", "chatgpt", "claude"],
        "radarStatus": "À surveiller",
        "decisionHint": "Plus l’agent agit, plus les tests et la revue deviennent importants.",
        "action": "Créer une tâche courte et vérifiable avant de tester un agent de code.",
        "tags": ["code", "agents", "orchestration"],
    },
    {
        "id": "ed-google-kaggle-cours-agents",
        "category": "DÉBUTANTS",
        "editorialCategory": "debutants",
        "title": "Google et Kaggle misent sur les agents IA : une bonne porte d’entrée pour apprendre",
        "summary": "Google relance un cours intensif sur les agents IA avec Kaggle. Le signal utile : les agents deviennent un sujet d’apprentissage grand public, pas seulement développeur.",
        "intro": "Un agent IA, ce n’est pas juste un chatbot. C’est un système qui peut suivre des étapes, appeler des outils et rendre un résultat. Mais pour bien l’utiliser, il faut d’abord comprendre le workflow.",
        "body": "## Ce qui change\n\nGoogle et Kaggle annoncent un cours autour des agents et du vibe coding. Pour les débutants, c’est intéressant parce que le sujet devient plus pédagogique : on apprend par petits projets plutôt qu’avec des définitions abstraites.\n\n## Schéma simple\n\n`Objectif → plan → outil → résultat → vérification`\n\n## Comment t’en servir\n\nMême sans suivre le cours, retiens la méthode : commence par un petit problème, demande les étapes, teste le résultat, puis augmente la complexité.\n\n## Conseil IA Match\n\nDans Academy, les agents doivent être enseignés après les bases : prompt clair, vérification, critères d’arrêt et sécurité des actions.",
        "publishedAt": "2026-04-27",
        "readMinutes": 3,
        "tag": "Apprendre",
        "highlight": "Les agents s’apprennent mieux par workflow que par jargon.",
        "author": "IA Match · Rédaction",
        "impactLevel": "moyen",
        "impactLabel": "Utile débutants",
        "confidence": "haute",
        "verificationStatus": "official_source_summarized",
        "lastVerifiedAt": "2026-05-04",
        "sourceIds": ["google-ai-blog"],
        "toolSlugs": ["gemini", "chatgpt", "claude", "cursor"],
        "radarStatus": "À apprendre",
        "decisionHint": "Apprends d’abord la logique des étapes avant de chercher un agent autonome.",
        "action": "Faire un mini-exercice : transformer un objectif en 5 étapes vérifiables.",
        "tags": ["débutants", "agents", "formation"],
    },
    {
        "id": "ed-google-translate-20-ans",
        "category": "OUTILS",
        "editorialCategory": "outils",
        "title": "Google Translate a 20 ans : l’IA utile n’est pas toujours spectaculaire",
        "summary": "Google rappelle que Translate vient d’une longue histoire IA et couvre désormais un très grand nombre de langues. Une bonne leçon : l’IA la plus utile est parfois invisible.",
        "intro": "On parle beaucoup des modèles qui écrivent, codent ou génèrent des images. Mais la traduction automatique montre une autre facette : l’IA qui rend le quotidien plus simple, sans effet waouh permanent.",
        "body": "## Ce que ça rappelle\n\nGoogle célèbre les 20 ans de Translate et met en avant l’évolution d’un outil parti d’une expérimentation IA vers un service utilisé par énormément de personnes. Pour un débutant, c’est une bonne porte d’entrée : l’IA n’est pas seulement ChatGPT.\n\n## Exemples concrets\n\n- Comprendre une page étrangère.\n- Préparer un message dans une autre langue.\n- Voyager plus sereinement.\n- Vérifier rapidement le sens général d’un texte.\n\n## Limite importante\n\nPour un contrat, un document juridique ou une nuance culturelle, garde une relecture humaine. La traduction IA est pratique, pas infaillible.\n\n## Conseil IA Match\n\nAjoute les outils “simples” dans tes habitudes : traduction, résumé, correction, recherche. C’est souvent là que l’IA fait gagner le plus vite du temps.",
        "publishedAt": "2026-04-28",
        "readMinutes": 3,
        "tag": "Langues",
        "highlight": "L’IA utile se cache parfois dans un outil que tout le monde connaît déjà.",
        "author": "IA Match · Rédaction",
        "impactLevel": "moyen",
        "impactLabel": "Utile débutants",
        "confidence": "haute",
        "verificationStatus": "official_source_summarized",
        "lastVerifiedAt": "2026-05-04",
        "sourceIds": ["google-ai-blog"],
        "toolSlugs": ["gemini", "google-translate", "chatgpt"],
        "radarStatus": "À tester maintenant",
        "decisionHint": "Commence aussi par les usages simples : traduire, reformuler, comprendre.",
        "action": "Tester une traduction puis demander à une IA d’expliquer les nuances.",
        "tags": ["langues", "débutants", "productivité"],
    },
    {
        "id": "ed-google-ai-mode-chrome",
        "category": "OUTILS",
        "editorialCategory": "outils",
        "title": "L’IA arrive dans le navigateur : bonne nouvelle, mais garde le réflexe source",
        "summary": "Google pousse des expériences d’AI Mode dans Chrome. Pour les débutants, cela veut dire que chercher, résumer et comparer vont devenir plus naturels dans le navigateur.",
        "intro": "Quand l’IA entre dans le navigateur, elle se rapproche du moment où tu lis, compares et décides. C’est pratique, mais ça augmente aussi le risque de croire trop vite un résumé.",
        "body": "## Ce qui change\n\nGoogle présente de nouvelles façons d’explorer le web avec AI Mode dans Chrome. L’idée : poser des questions, obtenir des explications et naviguer plus vite dans l’information.\n\n## Le bon réflexe\n\nUtilise l’IA pour gagner du temps, pas pour abandonner la vérification. Ouvre les sources importantes, regarde la date, compare deux résultats et garde une trace des liens clés.\n\n## Schéma simple\n\n`Question → résumé IA → ouverture des sources → comparaison → décision`\n\n## Conseil IA Match\n\nPour la recherche, recommande toujours un workflow avec sources. Une réponse claire sans source peut être utile pour comprendre, mais pas suffisante pour décider.",
        "publishedAt": "2026-04-16",
        "readMinutes": 3,
        "tag": "Recherche",
        "highlight": "Plus l’IA résume vite, plus il faut garder le réflexe de vérifier.",
        "author": "IA Match · Rédaction",
        "impactLevel": "moyen",
        "impactLabel": "Workflow utile",
        "confidence": "haute",
        "verificationStatus": "official_source_summarized",
        "lastVerifiedAt": "2026-05-04",
        "sourceIds": ["google-ai-blog"],
        "toolSlugs": ["gemini", "perplexity", "chatgpt"],
        "radarStatus": "À surveiller",
        "decisionHint": "Un navigateur augmenté aide à explorer ; la source reste ton filet de sécurité.",
        "action": "Tester une recherche IA puis ouvrir deux sources primaires.",
        "tags": ["recherche", "navigateur", "sources"],
    },
    {
        "id": "ed-gemini-images-personnalisees",
        "category": "IMAGE & VIDÉO",
        "editorialCategory": "image-video",
        "title": "Images personnalisées avec Gemini : pratique, mais attention aux photos privées",
        "summary": "Google met en avant de nouvelles créations personnalisées dans Gemini. La vraie question débutant : quelles images personnelles es-tu prêt à donner à un outil IA ?",
        "intro": "Les images IA deviennent plus personnelles : elles peuvent utiliser du contexte, des souvenirs ou des photos. C’est puissant pour créer, mais cela demande un vrai réflexe confidentialité.",
        "body": "## Ce qui change\n\nGoogle annonce de nouvelles façons de créer des images personnalisées dans l’app Gemini, avec davantage de contexte personnel. Pour l’utilisateur, cela rend la génération plus utile : style, personnes, lieux, souvenirs, usages concrets.\n\n## La limite à comprendre\n\nUne photo personnelle n’est pas un simple fichier. Elle peut contenir un visage, un lieu, une date, un enfant, une adresse, un document visible en arrière-plan.\n\n## Checklist avant d’uploader\n\n- Est-ce une image que je peux partager sans problème ?\n- Y a-t-il des personnes reconnaissables ?\n- L’outil explique-t-il comment l’image est utilisée ?\n- Ai-je vraiment besoin de cette photo pour obtenir le résultat ?\n\n## Conseil IA Match\n\nPour apprendre, commence avec des images neutres. Passe aux photos personnelles seulement quand tu comprends les paramètres de confidentialité.",
        "publishedAt": "2026-04-16",
        "readMinutes": 4,
        "tag": "Image",
        "highlight": "Plus l’image IA est personnelle, plus la confidentialité compte.",
        "author": "IA Match · Rédaction",
        "impactLevel": "moyen",
        "impactLabel": "À surveiller",
        "confidence": "haute",
        "verificationStatus": "official_source_summarized",
        "lastVerifiedAt": "2026-05-04",
        "sourceIds": ["google-ai-blog"],
        "toolSlugs": ["gemini", "chatgpt", "canva"],
        "radarStatus": "À tester prudemment",
        "decisionHint": "Le bon outil image dépend aussi des données que tu acceptes d’envoyer.",
        "action": "Tester avec une image neutre avant une photo personnelle.",
        "tags": ["image", "confidentialité", "débutants"],
    },
    {
        "id": "ed-modeles-generalistes-2026",
        "category": "MODÈLES",
        "editorialCategory": "modeles",
        "title": "Les assistants généralistes restent le meilleur point de départ",
        "summary": "ChatGPT, Claude, Gemini et Mistral couvrent maintenant assez de besoins pour éviter de multiplier les apps dès le départ.",
        "intro": "La meilleure décision pour la majorité des utilisateurs n’est pas de courir après le dernier modèle : c’est de choisir un assistant fiable, puis d’ajouter un outil spécialisé quand le besoin devient clair.",
        "body": "## Pourquoi c’est important\n\nLes assistants généralistes sont devenus le socle de beaucoup d’usages : écrire, résumer, analyser, coder un petit script, préparer un plan, expliquer un sujet ou transformer un document. Pour un débutant, commencer par un outil généraliste évite de se perdre dans une collection d’applications spécialisées.\n\n## La règle IA Match\n\nChoisis d’abord selon ton usage dominant : rédaction et documents longs, recherche sourcée, écosystème Google, code, confidentialité ou budget. Ensuite seulement, ajoute Midjourney, Canva, Perplexity, Cursor, Runway, Suno ou Ollama si ton besoin devient spécifique.\n\n## À vérifier avant de payer\n\nRegarde les limites du plan gratuit, la qualité en français, la gestion des fichiers, les connecteurs disponibles et les règles de confidentialité. Les prix et quotas changent souvent : l’app doit donc guider vers une décision, pas prétendre figer le marché.",
        "publishedAt": "2026-05-02",
        "readMinutes": 4,
        "tag": "Choix outil",
        "highlight": "Commencer simple bat souvent la chasse au modèle parfait.",
        "author": "IA Match · Rédaction",
        "impactLevel": "fort",
        "impactLabel": "Impact fort",
        "confidence": "haute",
        "verificationStatus": "curated_official_sources",
        "lastVerifiedAt": "2026-05-02",
        "sourceIds": ["openai-docs", "anthropic-docs", "google-ai-docs", "mistral-docs"],
        "toolSlugs": ["chatgpt", "claude", "gemini", "mistral"],
        "radarStatus": "À tester maintenant",
        "decisionHint": "Si tu débutes, choisis un assistant généraliste puis fais un Match seulement quand ton usage devient précis.",
        "action": "Lancer un Match avec ton besoin réel avant de choisir un abonnement.",
        "tags": ["débutants", "texte", "productivité", "modèles"],
    },
    {
        "id": "ed-recherche-sourcee",
        "category": "OUTILS",
        "editorialCategory": "outils",
        "title": "Recherche sourcée : Perplexity devient un réflexe, mais pas une vérité absolue",
        "summary": "Les moteurs de réponse font gagner du temps, à condition de lire les sources et de garder un assistant pour synthétiser.",
        "intro": "Pour chercher vite, la bonne stack n’est pas toujours un seul outil : moteur de réponse pour trouver, assistant généraliste pour transformer, humain pour vérifier.",
        "body": "## Le bon usage\n\nPerplexity et les recherches intégrées aux grands assistants rendent la veille beaucoup plus rapide. Le risque : confondre une réponse bien formulée avec une information validée. IA Match doit donc pousser l’utilisateur à vérifier les liens, dates et sources primaires.\n\n## Workflow recommandé\n\n1. Cherche les informations avec un outil orienté sources.\n2. Garde les liens importants.\n3. Demande ensuite à ChatGPT, Claude ou Gemini de produire un brief avec citations.\n4. Vérifie les chiffres sensibles dans les sources officielles.\n\n## Signal premium\n\nUne app utile ne dit pas seulement “utilise Perplexity”. Elle dit quand l’utiliser, quand repasser sur un assistant généraliste et quand ne pas faire confiance au résumé.",
        "publishedAt": "2026-05-02",
        "readMinutes": 3,
        "tag": "Recherche",
        "highlight": "Chercher plus vite ne remplace pas vérifier mieux.",
        "author": "IA Match · Rédaction",
        "impactLevel": "moyen",
        "impactLabel": "Workflow utile",
        "confidence": "haute",
        "verificationStatus": "curated_official_sources",
        "lastVerifiedAt": "2026-05-02",
        "sourceIds": ["perplexity", "openai-docs", "anthropic-docs"],
        "toolSlugs": ["perplexity", "chatgpt", "claude", "gemini"],
        "radarStatus": "À tester maintenant",
        "decisionHint": "Utilise la recherche sourcée pour trouver, puis un assistant pour structurer.",
        "action": "Tester un workflow recherche → brief → vérification.",
        "tags": ["recherche", "sources", "veille"],
    },
    {
        "id": "ed-code-agents-prudence",
        "category": "CODE & AGENTS",
        "editorialCategory": "code-agents",
        "title": "Agents de code : puissant, mais seulement avec tests et revue humaine",
        "summary": "Cursor, Copilot, Replit et les agents intégrés accélèrent le code, mais le vrai gain vient du workflow autour.",
        "intro": "Le bon agent de code n’est pas celui qui écrit le plus vite : c’est celui qui permet de vérifier, corriger et comprendre sans casser le projet.",
        "body": "## Ce qui change\n\nLes assistants de code savent modifier plusieurs fichiers, expliquer une erreur et proposer une architecture. Mais ils peuvent aussi introduire des régressions discrètes. Pour IA Match, la recommandation doit inclure le niveau de l’utilisateur, la taille du projet et la présence de tests.\n\n## Workflow propre\n\nAvant d’utiliser un agent, prépare une branche Git, un objectif court, des fichiers concernés et une commande de validation. Après génération, lis le diff, lance les tests, puis demande une revue ciblée.\n\n## À éviter\n\nNe donne pas à un agent un projet entier sans consigne précise. Ne valide pas une modification que tu ne peux pas expliquer. Pour les débutants, commencer par des petites tâches est plus rentable qu’un agent autonome complet.",
        "publishedAt": "2026-05-02",
        "readMinutes": 4,
        "tag": "Agents",
        "highlight": "Un agent sans tests est une accélération sans ceinture.",
        "author": "IA Match · Rédaction",
        "impactLevel": "fort",
        "impactLabel": "Workflow utile",
        "confidence": "haute",
        "verificationStatus": "curated_official_sources",
        "lastVerifiedAt": "2026-05-02",
        "sourceIds": ["cursor", "openai-docs", "anthropic-docs"],
        "toolSlugs": ["cursor", "github-copilot", "replit", "claude"],
        "radarStatus": "À surveiller",
        "decisionHint": "Bon pour projets structurés ; moins bon pour débuter sans comprendre le code.",
        "action": "Comparer les assistants de code puis ajouter une règle tests/revue.",
        "tags": ["code", "agents", "workflow"],
    },
    {
        "id": "ed-ia-locale-privee",
        "category": "OPEN-SOURCE",
        "editorialCategory": "open-local",
        "title": "IA locale : excellente pour la confidentialité, pas toujours pour la simplicité",
        "summary": "Ollama et les modèles ouverts rendent l’IA locale accessible, mais la qualité dépend du modèle, de la machine et du besoin.",
        "intro": "L’IA locale est un vrai plus pour apprendre, tester et garder des données sensibles hors du cloud. Mais elle n’est pas automatiquement meilleure qu’un assistant hébergé.",
        "body": "## Quand c’est pertinent\n\nL’IA locale est intéressante pour documents internes, expérimentation, confidentialité, coûts variables et apprentissage technique. Ollama simplifie beaucoup le lancement de modèles ouverts, mais il faut accepter des compromis : vitesse, mémoire machine, qualité selon modèle et absence de certains connecteurs.\n\n## Règle IA Match\n\nRecommande l’IA locale si la confidentialité ou le contrôle est prioritaire. Pour un usage débutant, rédaction quotidienne ou recherche web, un outil hébergé reste souvent plus ergonomique.\n\n## Action utile\n\nTester localement sur un cas simple : résumer un document non sensible ou générer un brouillon. Si le résultat demande trop de correction, repasser sur un assistant généraliste.",
        "publishedAt": "2026-05-02",
        "readMinutes": 3,
        "tag": "Local",
        "highlight": "Confidentialité oui ; magie automatique non.",
        "author": "IA Match · Rédaction",
        "impactLevel": "moyen",
        "impactLabel": "Alternative gratuite",
        "confidence": "haute",
        "verificationStatus": "curated_official_sources",
        "lastVerifiedAt": "2026-05-02",
        "sourceIds": ["ollama", "meta-llama", "mistral-docs"],
        "toolSlugs": ["ollama", "llama", "mistral", "qwen"],
        "radarStatus": "Bon si confidentialité",
        "decisionHint": "Choisis local si données sensibles ; choisis cloud si simplicité maximale.",
        "action": "Tester Ollama sur un cas simple avant de construire une stack locale.",
        "tags": ["local", "open-source", "confidentialité"],
    },
    {
        "id": "ed-image-production",
        "category": "IMAGE & VIDÉO",
        "editorialCategory": "image-video",
        "title": "Image IA : le vrai critère devient la production, pas seulement la beauté",
        "summary": "Midjourney, ChatGPT Image, Canva et Firefly ne servent pas au même moment du workflow créatif.",
        "intro": "Un beau visuel ne suffit pas. Pour une affiche, une pub, une miniature ou un post, il faut contrôler le texte, le format, les variantes et la retouche.",
        "body": "## Le bon découpage\n\nPour explorer une direction artistique, un outil créatif spécialisé peut être excellent. Pour produire vite un support publiable, Canva ou un éditeur orienté marque devient souvent plus utile. Pour modifier une image existante, choisis selon la précision de retouche et les droits d’usage.\n\n## Ce que IA Match doit expliquer\n\nL’utilisateur ne cherche pas “le meilleur modèle image”. Il cherche : créer une miniature YouTube, une publicité lisible, une affiche, une photo produit ou un concept artistique. La recommandation doit donc partir du livrable.\n\n## Action\n\nDéfinis le format final, le texte à afficher et le style. Ensuite seulement choisis l’outil.",
        "publishedAt": "2026-05-02",
        "readMinutes": 3,
        "tag": "Image",
        "highlight": "Le meilleur outil image dépend du livrable final.",
        "author": "IA Match · Rédaction",
        "impactLevel": "moyen",
        "impactLabel": "Utile débutants",
        "confidence": "moyenne",
        "verificationStatus": "curated_known_tools",
        "lastVerifiedAt": "2026-05-02",
        "sourceIds": ["openai-docs"],
        "toolSlugs": ["midjourney", "canva", "chatgpt", "adobe-firefly"],
        "radarStatus": "À tester maintenant",
        "decisionHint": "Image artistique, design de marque et retouche ne demandent pas le même outil.",
        "action": "Créer un prompt image à partir du format final.",
        "tags": ["image", "design", "canva", "midjourney"],
    },
    {
        "id": "ed-prix-plans",
        "category": "BUSINESS",
        "editorialCategory": "business-prix",
        "title": "Plans IA : le gratuit suffit souvent pour apprendre, pas toujours pour produire",
        "summary": "La bonne question n’est pas “quel plan est le meilleur ?”, mais “quelle limite va me bloquer ?”.",
        "intro": "Les abonnements IA se ressemblent en apparence, mais les limites changent : volume, modèles avancés, fichiers, images, vitesse, connecteurs et confidentialité.",
        "body": "## La grille simple\n\nGratuit : apprendre, tester, petites tâches. Pro : produire régulièrement, analyser des documents, gagner du temps. Team/Business : collaboration, sécurité, administration, données et contrôle.\n\n## Le piège\n\nPayer trop tôt peut créer une fausse impression de progrès. Si ton besoin est occasionnel, commence gratuit. Si tu répètes la même tâche chaque semaine, calcule le temps gagné.\n\n## Ce que IA Match doit faire\n\nAfficher “à éviter si…” et “plan gratuit suffisant si…” dans les fiches outils, plutôt que seulement un prix mensuel.",
        "publishedAt": "2026-05-02",
        "readMinutes": 3,
        "tag": "Prix",
        "highlight": "Le meilleur plan est celui qui supprime ta vraie limite.",
        "author": "IA Match · Rédaction",
        "impactLevel": "moyen",
        "impactLabel": "Change les prix",
        "confidence": "moyenne",
        "verificationStatus": "prices_change_check_official_site",
        "lastVerifiedAt": "2026-05-02",
        "sourceIds": ["openai-docs", "anthropic-docs", "google-ai-docs"],
        "toolSlugs": ["chatgpt", "claude", "gemini", "perplexity"],
        "radarStatus": "Pas urgent",
        "decisionHint": "Ne paie que si une limite claire te bloque.",
        "action": "Comparer gratuit vs premium selon ton volume réel.",
        "tags": ["prix", "abonnement", "gratuit"],
    },
    {
        "id": "ed-confiance-sources",
        "category": "CONFIANCE",
        "editorialCategory": "confiance",
        "title": "La confiance devient une fonctionnalité produit",
        "summary": "Sources, date de vérification, limites et avertissements doivent être visibles pour que l’utilisateur décide correctement.",
        "intro": "Une app IA premium ne doit pas seulement être jolie : elle doit montrer pourquoi une recommandation est fiable et où elle peut se tromper.",
        "body": "## Ce qui rend IA Match plus crédible\n\nChaque recommandation devrait afficher une logique simple : usage, budget, niveau, points forts, limites, fraîcheur des données et sources quand c’est possible. L’utilisateur doit comprendre la décision sans lire un rapport technique.\n\n## Le risque\n\nLes modèles, prix et quotas changent vite. Une app qui prétend tout savoir en live peut devenir moins fiable qu’une base curatée avec statut de vérification.\n\n## Action\n\nAjouter des badges : vérifié, à surveiller, prix à revérifier, source officielle, conseil IA Match. C’est plus premium qu’une liste brute.",
        "publishedAt": "2026-05-02",
        "readMinutes": 3,
        "tag": "Confiance",
        "highlight": "La transparence vaut mieux qu’une fausse certitude live.",
        "author": "IA Match · Rédaction",
        "impactLevel": "fort",
        "impactLabel": "Impact fort",
        "confidence": "haute",
        "verificationStatus": "editorial_methodology",
        "lastVerifiedAt": "2026-05-02",
        "sourceIds": ["eu-ai-act"],
        "toolSlugs": ["chatgpt", "claude", "gemini", "perplexity"],
        "radarStatus": "À intégrer partout",
        "decisionHint": "Montre les limites et la date de vérification, pas seulement un score.",
        "action": "Lire les badges de confiance avant de suivre une recommandation.",
        "tags": ["confiance", "sources", "régulation"],
    },
    {
        "id": "ed-automatisation-no-code",
        "category": "CODE & AGENTS",
        "editorialCategory": "code-agents",
        "title": "Automatisation no-code : commence par un workflow, pas par un agent autonome",
        "summary": "Make, Zapier et n8n restent souvent plus fiables qu’un agent libre pour les tâches répétitives simples.",
        "intro": "Beaucoup de gens veulent “un agent IA”. En pratique, un bon workflow no-code avec une étape IA contrôlée suffit souvent.",
        "body": "## La bonne séquence\n\nIdentifie une tâche répétée au moins trois fois. Décris l’entrée, la sortie, les exceptions et la validation humaine. Ensuite seulement, connecte un outil IA à Make, Zapier ou n8n.\n\n## Pourquoi c’est plus fiable\n\nUn workflow explicite est plus facile à débugger qu’un agent qui décide tout seul. Tu sais quelle étape a échoué, quelles données ont circulé et où ajouter une approbation.\n\n## Quand passer à l’agent\n\nQuand le workflow a trop de branches, demande des recherches, lit plusieurs sources ou doit prendre des décisions non triviales. Même là, garde un humain dans la boucle pour les actions sensibles.",
        "publishedAt": "2026-05-02",
        "readMinutes": 4,
        "tag": "No-code",
        "highlight": "Un workflow clair bat souvent un agent flou.",
        "author": "IA Match · Rédaction",
        "impactLevel": "moyen",
        "impactLabel": "Workflow utile",
        "confidence": "haute",
        "verificationStatus": "curated_known_tools",
        "lastVerifiedAt": "2026-05-02",
        "sourceIds": [],
        "toolSlugs": ["zapier", "make", "n8n", "chatgpt"],
        "radarStatus": "À tester maintenant",
        "decisionHint": "Automatise ce que tu sais déjà décrire étape par étape.",
        "action": "Créer une checklist entrée → action → validation avant d’automatiser.",
        "tags": ["automation", "agents", "no-code"],
    },
    {
        "id": "ed-debutants-premier-prompt",
        "category": "DÉBUTANTS",
        "editorialCategory": "debutants",
        "title": "Premier prompt : le bon réflexe est de décrire le résultat attendu",
        "summary": "Pour débuter, inutile d’apprendre tout le vocabulaire IA : rôle, objectif, contexte et format suffisent déjà.",
        "intro": "La plupart des mauvais résultats viennent d’une demande trop vague. IA Match doit aider à transformer une idée floue en demande testable.",
        "body": "## La formule simple\n\nDonne un rôle, explique ce que tu veux obtenir, ajoute le contexte utile et impose un format. Ce cadre suffit pour améliorer fortement les réponses.\n\n## Exemple\n\nAu lieu de “fais-moi un texte”, demande : “tu es un conseiller pédagogique, explique ce sujet à un débutant en 5 points avec un exemple”.\n\n## Action\n\nOuvre le Builder, génère une idée aléatoire puis remplace seulement le contexte par ton besoin réel.",
        "publishedAt": "2026-05-02",
        "readMinutes": 3,
        "tag": "Débutants",
        "highlight": "Un prompt clair bat un modèle cher mal briefé.",
        "author": "IA Match · Rédaction",
        "impactLevel": "moyen",
        "impactLabel": "Utile débutants",
        "confidence": "haute",
        "verificationStatus": "editorial_methodology",
        "lastVerifiedAt": "2026-05-02",
        "sourceIds": [],
        "toolSlugs": ["chatgpt", "claude", "gemini", "mistral"],
        "radarStatus": "À tester maintenant",
        "decisionHint": "Commence par améliorer la demande avant de changer d’outil.",
        "action": "Créer un prompt dans le Builder avec les 4 blocs essentiels.",
        "tags": ["débutants", "prompt", "builder"],
    },
    {
        "id": "ed-formateurs-kits-ia",
        "category": "BUSINESS",
        "editorialCategory": "business-prix",
        "title": "Formateurs : les kits IA valent plus qu’une simple liste d’outils",
        "summary": "Un bon support IA combine cas d’usage, prompts, exercices, risques et critères de correction.",
        "intro": "Pour vendre ou animer une formation IA, la valeur n’est pas la veille brute : c’est le parcours pédagogique prêt à utiliser.",
        "body": "## Ce qui fait la différence\n\nUn kit utile contient une explication simple, un prompt de départ, un exemple corrigé, un exercice et une règle de sécurité. Les apprenants comprennent mieux quand ils voient avant/après.\n\n## Signal business\n\nIA Match peut monétiser des diagnostics, supports de formation et stacks métier avant de construire un gros SaaS équipe.\n\n## Action\n\nTester une offre kit formateur avec 3 modules : débuter, prompter, vérifier.",
        "publishedAt": "2026-05-02",
        "readMinutes": 3,
        "tag": "Formation",
        "highlight": "La pédagogie vend mieux qu’un catalogue brut.",
        "author": "IA Match · Rédaction",
        "impactLevel": "moyen",
        "impactLabel": "Business utile",
        "confidence": "moyenne",
        "verificationStatus": "editorial_strategy",
        "lastVerifiedAt": "2026-05-02",
        "sourceIds": [],
        "toolSlugs": ["chatgpt", "claude", "canva", "notion"],
        "radarStatus": "À tester en offre",
        "decisionHint": "Vendre un résultat pédagogique, pas une base de données.",
        "action": "Préparer un mini kit formation avec prompts et exercices.",
        "tags": ["business", "formation", "academy"],
    },

    {
        "id": "ed-claude-code-assistants-dev",
        "category": "CODE & AGENTS",
        "editorialCategory": "code-agents",
        "title": "Claude Code, Cline, Roo, Aider : les assistants IA de dev ne se valent pas",
        "summary": "Au-delà de ChatGPT, les assistants de code deviennent des partenaires de repo : certains écrivent dans l’éditeur, d’autres travaillent en CLI ou orchestrent des tâches.",
        "intro": "Si tu codes, la vraie question n’est plus seulement “GPT ou Gemini ?”. Il faut choisir entre un assistant dans l’éditeur, un agent de terminal, un copilote GitHub ou un workflow open-source contrôlable.",
        "body": "## Ce qui change\n\nClaude Code, Cline, Roo Code, Aider, Cursor ou Copilot n’ont pas la même place dans le travail. Certains lisent ton repo, proposent un plan, éditent plusieurs fichiers et lancent des tests. D’autres restent meilleurs pour compléter une fonction ou expliquer une erreur.\n\n## Schéma simple\n\n`Brief court → lecture du repo → modification ciblée → tests → revue humaine`\n\n## Comment choisir\n\n- Débutant : commence avec explication + petits fichiers.\n- Projet réel : privilégie branche Git, diff lisible et tests.\n- Données sensibles : regarde où part le code et quels modèles sont appelés.\n- Gros refactor : Claude ou un agent CLI peut être plus utile qu’un simple autocompléteur.\n\n## Conseil IA Match\n\nUn assistant de dev doit être recommandé selon ton niveau, ton éditeur, la taille du projet et ta capacité à relire le diff. Sans tests, l’agent devient vite dangereux.",
        "publishedAt": "2026-05-04",
        "readMinutes": 4,
        "tag": "Claude / Code",
        "highlight": "Le bon assistant de code dépend du workflow, pas seulement du modèle.",
        "author": "IA Match · Rédaction",
        "impactLevel": "fort",
        "impactLabel": "Code utile",
        "confidence": "haute",
        "verificationStatus": "curated_known_tools",
        "lastVerifiedAt": "2026-05-04",
        "sourceIds": ["anthropic-docs", "cursor"],
        "toolSlugs": ["claude", "cursor", "github-copilot", "aider"],
        "radarStatus": "À tester prudemment",
        "decisionHint": "Choisis un assistant qui laisse un diff relisible et une validation humaine.",
        "action": "Tester une petite correction avec branche Git + commande de test.",
        "tags": ["claude", "code", "agents", "cline", "aider", "roo"],
    },
    {
        "id": "ed-claude-documents-long-contexte",
        "category": "MODÈLES",
        "editorialCategory": "modeles",
        "title": "Claude reste une référence pour lire, écrire et décider sur des documents longs",
        "summary": "Claude n’est pas juste un concurrent de ChatGPT : il brille quand il faut garder le contexte, nuancer et travailler sur des dossiers longs.",
        "intro": "Pour documents, notes, analyse juridique légère, stratégie ou rédaction longue, Claude garde une identité claire : moins spectaculaire parfois, mais très solide pour le travail de fond.",
        "body": "## Pourquoi ça compte\n\nBeaucoup d’actus parlent de GPT, Gemini ou Ollama parce qu’ils bougent beaucoup. Mais dans l’usage quotidien, Claude reste souvent le meilleur choix pour lire un gros document, structurer une décision ou écrire sans ton robotique.\n\n## Schéma simple\n\n`Document long → questions ciblées → synthèse nuancée → limites → décision`\n\n## Quand le choisir\n\n- Dossier long à résumer ou comparer.\n- Texte sensible qui demande un ton précis.\n- Analyse avec nuances, risques et objections.\n- Code ou produit quand tu veux une explication propre du raisonnement.\n\n## Conseil IA Match\n\nNe compare pas Claude uniquement en “score général”. Compare-le sur ton vrai livrable : document, style, longueur, confidentialité et capacité à expliquer les limites.",
        "publishedAt": "2026-05-04",
        "readMinutes": 4,
        "tag": "Claude",
        "highlight": "Claude gagne souvent quand la nuance et le contexte long comptent.",
        "author": "IA Match · Rédaction",
        "impactLevel": "fort",
        "impactLabel": "Impact fort",
        "confidence": "haute",
        "verificationStatus": "curated_official_sources",
        "lastVerifiedAt": "2026-05-04",
        "sourceIds": ["anthropic-docs"],
        "toolSlugs": ["claude", "chatgpt", "gemini", "mistral"],
        "radarStatus": "À tester",
        "decisionHint": "Pour lire et écrire long, teste Claude avant de payer un outil spécialisé.",
        "action": "Comparer Claude et ton assistant actuel sur le même document.",
        "tags": ["claude", "anthropic", "documents", "écriture"],
    },
    {
        "id": "ed-comparer-outils-sans-tableau",
        "category": "OUTILS",
        "editorialCategory": "outils",
        "title": "Comparer des IA : les cartes lisibles gagnent sur les tableaux géants",
        "summary": "Sur mobile, un bon comparatif doit montrer meilleur choix, alternative gratuite, limite et action suivante.",
        "intro": "Les comparaisons IA deviennent vite illisibles si elles empilent scores, prix, modèles et catégories. IA Match doit condenser la décision.",
        "body": "## Le format efficace\n\nPour chaque usage, montre : meilleur choix, pourquoi, prix/limite, à éviter si, et prompt de test. Le détail peut exister, mais pas bloquer la lecture.\n\n## Sur mobile\n\nPrivilégie des cartes empilées, filtres horizontaux et explications courtes plutôt qu’un grand tableau.\n\n## Action\n\nQuand tu compares deux outils, décide d’abord le critère principal : budget, qualité, vitesse, sources ou confidentialité.",
        "publishedAt": "2026-05-02",
        "readMinutes": 3,
        "tag": "Comparatif",
        "highlight": "Comparer sert à décider, pas à tout afficher.",
        "author": "IA Match · Rédaction",
        "impactLevel": "moyen",
        "impactLabel": "UX utile",
        "confidence": "haute",
        "verificationStatus": "editorial_methodology",
        "lastVerifiedAt": "2026-05-02",
        "sourceIds": [],
        "toolSlugs": ["chatgpt", "claude", "gemini", "perplexity"],
        "radarStatus": "À intégrer",
        "decisionHint": "Un comparatif doit finir par une recommandation actionnable.",
        "action": "Lancer un Match puis comparer seulement les 3 meilleurs résultats.",
        "tags": ["comparatif", "mobile", "décision"],
    },
]


def _today_iso() -> str:
    return datetime.now(timezone.utc).date().isoformat()


def get_editorial_categories() -> List[Dict]:
    return EDITORIAL_CATEGORIES


def get_editorial_sources() -> List[Dict]:
    return EDITORIAL_SOURCES


def get_curated_editorial_articles() -> List[Dict]:
    return [dict(a) for a in CURATED_EDITORIAL_ARTICLES]


def build_editorial_feed(static_news: List[Dict], dynamic_news: List[Dict] | None = None) -> List[Dict]:
    """Return decision-first feed: curated base first, then validated dynamic/static extras."""
    dynamic_news = dynamic_news or []
    curated = get_curated_editorial_articles()
    existing = {a["id"] for a in curated}
    extras: List[Dict] = []
    speculative_legacy = ("GPT-5.5", "GPT Image 2.0", "Claude 4.5", "Gemini 3 Ultra", "DeepSeek R2", "Grok 4")
    for item in dynamic_news + static_news:
        if not item or item.get("id") in existing:
            continue
        legacy_text = " ".join(str(item.get(k, "")) for k in ("title", "summary", "intro", "body"))
        if any(term in legacy_text for term in speculative_legacy):
            continue
        if item.get("verificationStatus") == "rejected":
            continue
        extra = dict(item)
        extra.setdefault("editorialCategory", _infer_editorial_category(extra))
        extra.setdefault("impactLabel", "À surveiller")
        extra.setdefault("impactLevel", "faible")
        extra.setdefault("confidence", "moyenne")
        extra.setdefault("verificationStatus", "legacy_or_dynamic_review_needed")
        extra.setdefault("lastVerifiedAt", extra.get("publishedAt") or _today_iso())
        extra.setdefault("sourceIds", [])
        extra.setdefault("toolSlugs", [])
        extra.setdefault("radarStatus", "À surveiller")
        extra.setdefault("decisionHint", "À lire comme un signal, pas comme une recommandation définitive.")
        extra.setdefault("action", "Lancer un Match si ce sujet correspond à ton besoin.")
        extras.append(extra)
    def rank(article: Dict) -> tuple:
        impact = {"fort": 0, "moyen": 1, "faible": 2}.get(str(article.get("impactLevel", "faible")).lower(), 2)
        return (impact, str(article.get("publishedAt", "")))
    return sorted(curated, key=rank) + extras[:8]


def get_editorial_highlights(feed: List[Dict]) -> Dict:
    items = feed[:]
    by_id = {a.get("id"): a for a in items}
    radar_plan = [
        ("ed-agents-orchestration-codex-symphony", "À surveiller", "Agents IA contrôlés", "Tester seulement avec une petite tâche, des tests et une revue humaine.", "Tâche → agent → tests → revue → décision", 86),
        ("ed-openai-securite-compte-2026", "À faire maintenant", "Comptes IA sensibles", "Activer 2FA, séparer perso/pro et éviter les secrets dans les conversations.", "Compte → fichiers → historique → accès → protection", 92),
        ("ed-google-ai-mode-chrome", "À apprendre", "Réflexe sources", "Ouvrir deux sources primaires avant de prendre une décision importante.", "Question → résumé → sources → comparaison → décision", 88),
        ("ed-modeles-generalistes-2026", "À tester", "Assistant généraliste d’abord", "Faire un Match avec ton vrai besoin avant de payer un outil niche.", "Besoin → assistant → prompt → résultat → amélioration", 84),
        ("ed-gemini-images-personnalisees", "À tester prudemment", "Images personnelles", "Tester avec une image neutre avant d’envoyer une photo privée.", "Image → données → outil → création → contrôle", 78),
    ]
    radar = []
    for article_id, label, title, action, schema, score in radar_plan:
        article = by_id.get(article_id, {})
        radar.append({
            "label": label,
            "title": title,
            "action": action,
            "category": article.get("editorialCategory"),
            "impactLabel": article.get("impactLabel"),
            "id": article_id,
            "schema": schema,
            "score": score,
            "why": article.get("decisionHint") or article.get("summary"),
        })
    return {
        "generatedAt": _today_iso(),
        "mode": "semi-live-curated",
        "headline": items[0] if items else None,
        "radar": radar,
        "methodology": "Sources officielles ou outils reconnus, curation IA Match, date de vérification, impact et conseil actionnable. Le live brut n’est pas publié sans revue.",
    }


def _infer_editorial_category(item: Dict) -> str:
    h = " ".join(str(item.get(k, "")) for k in ("category", "title", "summary", "tag", "body")).lower()
    if any(w in h for w in ["image", "vidéo", "video", "midjourney", "runway", "canva"]):
        return "image-video"
    if any(w in h for w in ["code", "agent", "cursor", "copilot", "zapier", "make", "n8n"]):
        return "code-agents"
    if any(w in h for w in ["prix", "tarif", "abonnement", "business", "pro"]):
        return "business-prix"
    if any(w in h for w in ["local", "open", "llama", "ollama", "mistral"]):
        return "open-local"
    if any(w in h for w in ["régulation", "regulation", "confiance", "source", "privacy"]):
        return "confiance"
    if any(w in h for w in ["débutant", "apprendre", "pédagog"]):
        return "debutants"
    if any(w in h for w in ["gpt", "claude", "gemini", "modèle", "model"]):
        return "modeles"
    return "outils"
