"""Editorial content for IA Match: news (Actue), lessons + templates (Academy), resources."""

# ----- ACTUE -----
# Articles complets, pédagogiques, accessibles aux novices, structurés.
NEWS = [
    {
        "id": "n1",
        "category": "DÉCRYPTAGE",
        "title": "GPT-5.2 simplifie le prompt stack",
        "summary": "OpenAI publie une nouvelle guidance : moins de structure, plus de critères de réussite. Notre Academy a été synchronisée.",
        "publishedAt": "2026-04-28",
        "readMinutes": 5,
        "tag": "OpenAI",
        "highlight": "5.2",
        "author": "Rédaction IA Match",
        "intro": "OpenAI a publié fin avril 2026 un nouveau guide officiel sur la manière de prompter GPT-5.2. Surprise : la firme recommande désormais d'écrire **moins** mais de **mieux qualifier le résultat attendu**. On t'explique pourquoi c'est un tournant pédagogique.",
        "body": "## Ce qui change concrètement\n\nDepuis trois ans, la communauté répétait la même règle : empiler les blocs (rôle, contexte, contraintes, exemples, étapes). C'était efficace avec GPT-4 et Claude 3, mais GPT-5.2 raisonne désormais en interne avec un module appelé *internal scratchpad*. Concrètement, le modèle s'auto-organise. Lui imposer la structure devient redondant et peut même brouiller son raisonnement.\n\n## Le nouveau réflexe : décrire le succès\n\nOpenAI propose une formule courte : **OBJECTIF + CRITÈRES DE RÉUSSITE + FORMAT**. Plutôt que de dérouler une recette, tu décris à quoi ressemble une excellente sortie.\n\nExemple avant/après pour rédiger une fiche produit :\n\n- **Avant** : 'Tu es copywriter senior. Audience : 30-40 ans. Ton sobre. Pas de superlatif. Donne 3 paragraphes structurés ainsi…'\n- **Après** : 'Rédige une fiche produit pour un sac à dos premium. Critères de réussite : un acheteur exigeant comprend en 10 secondes pourquoi ce sac mérite 250€, sans aucun mot publicitaire générique. Format : 100 mots max + 3 puces.'\n\n## Pourquoi ça marche mieux\n\nUn modèle de raisonnement teste plusieurs hypothèses en interne. Lui donner un critère de succès clair, c'est lui donner une **fonction objectif**. Il peut alors auto-évaluer ses brouillons. À l'inverse, des consignes trop précises ferment des angles potentiellement meilleurs.\n\n## Ce que ça implique pour toi\n\n1. **Garde tes anciens prompts**, ils restent valides.\n2. **Teste la nouvelle formule** sur tes 3 cas les plus fréquents.\n3. **Compare** la qualité subjective sur 5 sorties.\n4. **Mesure** : si la nouvelle formule est plus simple ET produit aussi bien, tu gagnes du temps tous les jours.\n\n## L'angle Academy\n\nNotre leçon 'La méthode des 7 blocs' reste pertinente pour les modèles plus anciens et pour les cas vraiment complexes. Mais on ajoute maintenant 'OBJECTIF + CRITÈRES + FORMAT' comme premier réflexe pour GPT-5.2 et Claude 4.6.\n\n## Verdict\n\nOpenAI ne dit pas 'oubliez tout'. Il dit : 'arrêtez de surstructurer'. C'est une bonne nouvelle : prompter devient plus humain. Tu décris ce que tu veux comme tu l'expliquerais à un collègue compétent, pas à une machine.",
    },
    {
        "id": "n2",
        "category": "COMPARATIF",
        "title": "Sora vs Runway : laquelle choisir pour une pub courte ?",
        "summary": "Mouvements de caméra, continuité, durée. Notre verdict honnête après 30 prompts identiques sur les deux moteurs.",
        "publishedAt": "2026-04-22",
        "readMinutes": 7,
        "tag": "Vidéo",
        "author": "Rédaction IA Match",
        "intro": "Tu veux générer une publicité de 15 secondes pour ton produit. Deux outils dominent : **Sora** (OpenAI) et **Runway Gen-3 Turbo**. Ils n'ont pas la même philosophie. Voici ce qu'on a appris en testant les deux sur 30 prompts identiques.",
        "body": "## La promesse de chaque outil\n\n**Sora** vise le rendu cinématographique : longues prises, mouvements de caméra fluides, photoréalisme. Sa force : la cohérence visuelle entre plusieurs plans.\n\n**Runway** est une suite complète : génération + montage + effets. Sa force : la rapidité d'itération et le contrôle fin avec les *Motion Brushes*.\n\n## Méthodologie\n\nOn a soumis 30 prompts identiques aux deux outils, répartis en trois familles : objet en mouvement, scène urbaine, portrait expressif. On a noté la cohérence (1-5), le réalisme (1-5), la fidélité au prompt (1-5).\n\n## Résultats\n\n- **Cohérence** : Sora 4.4 / Runway 3.6\n- **Réalisme** : Sora 4.5 / Runway 4.1\n- **Fidélité** : Sora 4.0 / Runway 4.3\n- **Vitesse** : Sora 60s / Runway 25s\n- **Coût** : Sora ≈ 0.50€ / clip / Runway ≈ 0.30€ / clip\n\n## Quand choisir Sora\n\n- Tu veux un plan de 8-10 secondes avec un mouvement de caméra continu.\n- Tu vises un rendu type bande-annonce.\n- Tu peux attendre 1 minute par génération.\n\n## Quand choisir Runway\n\n- Tu itères rapidement sur 20+ variantes.\n- Tu as besoin de Motion Brush ou d'inpainting vidéo.\n- Tu veux un workflow complet sans changer d'outil.\n\n## Notre conseil pour une pub 15 secondes\n\n**Génère le plan principal avec Sora**, puis fais le *finishing* dans Runway (recadrage, color grading, ajout de texte). Tu profites du meilleur des deux mondes pour environ 1€ par version.\n\n## Le piège classique\n\nNe demande jamais 'une pub virale qui convertit'. Le modèle ne sait pas convertir. Décris **le plan**, **l'objet**, **l'ambiance**, **la lumière**. La conversion, c'est ton brief marketing en amont.\n\n## Verdict\n\nSora gagne sur la qualité par plan. Runway gagne sur le workflow complet. Si tu débutes : Runway. Si tu vises l'excellence visuelle : Sora.",
    },
    {
        "id": "n3",
        "category": "TUTORIEL",
        "title": "Édition d'image conversationnelle : la méthode 'Garder · Changer · Exclure'",
        "summary": "Modifier une image générée sans tout casser. La technique simple en 3 listes qui change la productivité créative.",
        "publishedAt": "2026-04-18",
        "readMinutes": 6,
        "tag": "Image",
        "author": "Rédaction IA Match",
        "intro": "Tu génères une image presque parfaite, mais le visage n'est pas le bon. Avant, tu relançais tout. Aujourd'hui, les meilleurs modèles d'édition d'image (Nano Banana 2, Flux Edit) acceptent une grammaire simple : **garder, changer, exclure**. On t'apprend la méthode.",
        "body": "## Le problème classique\n\nTu obtiens une image avec une bonne lumière, une bonne composition, mais un détail à corriger. Si tu reprompts à zéro, tu perds tout. Si tu décris vaguement la modif, le modèle change trop.\n\n## La solution : 3 listes\n\n1. **GARDER** : ce qui doit rester strictement identique.\n2. **CHANGER** : ce qui doit évoluer, avec une direction précise.\n3. **EXCLURE** : ce qui ne doit jamais apparaître dans la nouvelle version.\n\n## Exemple concret\n\nImage de départ : un homme en costume bleu marine devant une fenêtre, lumière douce du soir.\n\n**Mauvais prompt d'édition** : 'change le costume'.\n\n**Bon prompt d'édition** :\n- GARDER : la pose, la fenêtre, la lumière du soir, le cadrage à mi-corps.\n- CHANGER : le costume devient un pull col roulé en cachemire beige.\n- EXCLURE : tout accessoire, cravate, badge, motif visible.\n\nLe modèle exécute exactement la modification voulue, sans toucher au reste.\n\n## Pourquoi ça marche\n\nTu donnes au modèle une **fonction de stabilité** explicite. Sans cette liste de 'garder', il considère qu'il peut tout modifier. Avec, il a une zone interdite.\n\n## La règle du 1-2-1\n\n- **1** : ne change qu'**un seul** élément à la fois.\n- **2** : si tu enchaînes, garde **2 itérations max** sur la même image (au-delà, la qualité dérive).\n- **1** : sauvegarde **chaque** version intermédiaire.\n\n## Cas d'usage qui marchent très bien\n\n- Changer une couleur précise (vêtement, mur, voiture).\n- Remplacer un objet par un autre dans la même position.\n- Enlever une personne ou un objet (utilise EXCLURE).\n- Ajouter un élément discret (lumière, ombre, accessoire).\n\n## Cas où ça marche mal\n\n- Changer la pose d'un personnage tout en gardant l'expression.\n- Modifier la lumière de manière drastique.\n- Reconstruire une zone occlusée par un autre objet.\n\nDans ces cas, accepte de relancer à zéro avec un prompt mieux écrit.\n\n## Verdict\n\nLa méthode 'Garder · Changer · Exclure' n'est pas magique : c'est de la communication précise. Comme avec un humain. La maîtriser te fait gagner 60% du temps de retouche créative.",
    },
    {
        "id": "n4",
        "category": "AGENT",
        "title": "Comprendre les agents IA en 5 minutes",
        "summary": "Un 'agent' n'est pas juste un chatbot. Voici ce qui change vraiment, sans hype ni jargon.",
        "publishedAt": "2026-04-14",
        "readMinutes": 5,
        "tag": "Concepts",
        "author": "Rédaction IA Match",
        "intro": "Tu lis partout 'agents autonomes', 'agentic AI', 'multi-agent systems'. C'est flou. Cet article explique simplement la différence entre un chatbot, un assistant et un agent — avec des exemples du quotidien.",
        "body": "## La hiérarchie en 3 niveaux\n\n### Niveau 1 — Le chatbot\nIl répond à une question. Une entrée, une sortie. ChatGPT en mode 'pose ta question'.\n\n### Niveau 2 — L'assistant outillé\nIl peut utiliser des outils (recherche web, calculatrice, lecture de fichier). Il décide quel outil mobiliser. Mais il attend ta validation à chaque étape importante.\n\n### Niveau 3 — L'agent autonome\nIl reçoit un objectif, fait un plan, exécute, vérifie son propre travail, ajuste, recommence si besoin. Tu interviens seulement aux check-points.\n\n## Exemple concret : 'organise un voyage à Lisbonne'\n\n- **Chatbot** : te donne 5 idées de visite.\n- **Assistant** : te montre les vols disponibles, mais c'est toi qui réserves.\n- **Agent** : compare les vols, choisit le meilleur compromis prix/horaire selon tes préférences, te demande validation avant paiement, réserve, met l'événement dans ton calendrier, prévient ton hôte.\n\n## Pourquoi c'est nouveau\n\nDeux capacités ont été débloquées récemment :\n\n1. **Tool use fiable** : le modèle sait utiliser un outil sans halluciner les paramètres.\n2. **Self-reflection** : le modèle peut critiquer sa propre sortie et la corriger.\n\nSans ces deux briques, un agent dérape vite.\n\n## Les 3 risques actuels\n\n- **Boucle infinie** : l'agent ré-essaie sans progresser.\n- **Coût qui dérape** : chaque step coûte des tokens.\n- **Décisions opaques** : l'agent prend une action que tu n'aurais pas validée.\n\nLa parade : **toujours** définir un budget (max 10 étapes, max 1€) et exiger un journal de raisonnement.\n\n## Comment commencer sans te brûler\n\n1. **Identifie une tâche répétitive** (rapport hebdo, tri de mails, veille).\n2. **Décris-la pas à pas** comme à un nouveau stagiaire.\n3. **Donne au stagiaire les bons outils** (accès calendrier, lecture inbox).\n4. **Surveille les 5 premières exécutions**.\n5. **Lâche progressivement** la main quand la fiabilité est prouvée.\n\n## Outils recommandés en 2026\n\n- Cursor (code), Replit Agent (apps), Zapier Agents (workflows business), n8n (open-source self-host), Make (no-code grand public).\n\n## Verdict\n\nUn agent, c'est un assistant à qui tu fais confiance pour exécuter sans te demander à chaque clic. La confiance se construit. Commence petit. Mesure. Itère.",
    },
    {
        "id": "n5",
        "category": "PRATIQUE",
        "title": "5 erreurs qui te font perdre du temps avec ChatGPT",
        "summary": "Les pièges quotidiens des utilisateurs, et comment les éviter en 30 secondes.",
        "publishedAt": "2026-04-09",
        "readMinutes": 5,
        "tag": "Productivité",
        "author": "Rédaction IA Match",
        "intro": "On a observé 50 utilisateurs débutants pendant 1 mois. Cinq erreurs reviennent sans cesse et coûtent en moyenne 40 minutes par jour. Bonne nouvelle : chacune se corrige en 30 secondes.",
        "body": "## Erreur 1 — Demander 'rédige-moi un email'\n\nLe modèle ne sait ni à qui, ni pourquoi, ni dans quel ton. Il produit un email générique que tu vas réécrire à 80%.\n\n**Correction** : 'Rédige un email à [destinataire] pour [objectif précis]. Ton : [adjectif unique]. 5 lignes max.'\n\n## Erreur 2 — Coller un texte sans cadrer la sortie\n\nTu colles 4 pages et tu écris 'que penses-tu ?'. Tu reçois une analyse vague.\n\n**Correction** : pose **une question précise** sur le texte. 'Quelles sont les 3 plus grandes faiblesses argumentatives ?' ou 'Résume en 80 mots pour un investisseur'.\n\n## Erreur 3 — Continuer une conversation devenue trop longue\n\nAprès 30 messages, le modèle perd le fil. Il commence à se contredire.\n\n**Correction** : à partir du moment où la sortie se dégrade, démarre une **nouvelle conversation** en collant un résumé de l'avancement.\n\n## Erreur 4 — Faire confiance aux chiffres et aux citations\n\nLes modèles inventent des chiffres et des citations qui paraissent crédibles.\n\n**Correction** : pour tout chiffre ou citation, utilise un outil avec **sources** (Perplexity, ChatGPT en mode Browse, Gemini). Vérifie deux fois avant de publier.\n\n## Erreur 5 — Ne jamais sauvegarder ses bons prompts\n\nTu trouves la formule parfaite pour résumer un PDF, et tu la perds. Tu réinventes chaque semaine.\n\n**Correction** : ouvre un document 'Mes prompts' (ou utilise notre Academy). Sauvegarde 3 catégories : Écrit, Recherche, Code. Réutilise.\n\n## Bonus : la règle des 30 secondes\n\nAvant d'envoyer un prompt, demande-toi 30 secondes : 'si je donnais ça à un humain compétent qui ne connaît pas mon contexte, comprendrait-il ?'. Si non, ajoute le contexte manquant. Tu gagneras 10 minutes derrière.\n\n## Verdict\n\nL'IA ne lit pas dans tes pensées. Plus tu lui donnes de cadrage utile (et seulement utile), plus elle est précise. Les utilisateurs qui doublent leur productivité ne tapent pas plus vite : ils écrivent **plus précisément**.",
    },
    {
        "id": "n6",
        "category": "INDUSTRIE",
        "title": "Mistral lève 1Md€ pour son Le Chat Pro",
        "summary": "Le champion européen accélère sur l'agent et le code. Disponibilité française renforcée.",
        "publishedAt": "2026-04-04",
        "readMinutes": 4,
        "tag": "Mistral",
        "author": "Rédaction IA Match",
        "intro": "Mistral AI a annoncé une levée de 1 milliard d'euros, principalement portée par des fonds européens. Voici ce qui change concrètement pour les utilisateurs et les entreprises françaises.",
        "body": "## Ce que finance la levée\n\nL'argent va sur trois axes :\n\n1. **Le Chat Pro** : version premium pour entreprises avec stockage data en France.\n2. **Mistral Code** : modèle dédié au code, optimisé pour les langages européens (PHP, Python, TypeScript).\n3. **Mistral Agent** : agent autonome avec accès direct aux suites Office 365 et Workspace.\n\n## Pourquoi c'est important pour toi\n\nSi tu travailles dans le secteur public, la santé, la banque, ou tout métier réglementé en Europe, **la souveraineté data n'est plus un nice-to-have**. Hébergement français, RGPD strict, contrats clairs. Mistral coche les cases.\n\n## Les chiffres clés\n\n- **40%** : part de Mistral dans les déploiements LLM dans les administrations françaises (avril 2026).\n- **60%** : croissance trimestrielle des déploiements Le Chat Pro.\n- **9** : nouveaux pays européens couverts officiellement.\n\n## Le positionnement\n\nMistral ne cherche pas à battre OpenAI sur le benchmark MMLU. Il cherche à être **le meilleur partenaire IA pour l'Europe régulée**. Stratégie payante : les RFP enterprise européens favorisent les acteurs locaux.\n\n## Verdict\n\nLa souveraineté n'est pas un argument marketing : c'est devenu une exigence. Mistral capitalise dessus avec rigueur. Si tu déploies de l'IA en entreprise européenne, **mets Mistral dans ta short-list par défaut**.",
    },
    {
        "id": "n7",
        "category": "MARCHÉ",
        "title": "Le marché de l'IA générative atteint 280 Md$ en 2026",
        "summary": "Les 'agents' croissent 4x plus vite que les modèles. Lecture des chiffres pour les non-spécialistes.",
        "publishedAt": "2026-04-02",
        "readMinutes": 6,
        "tag": "Marché",
        "author": "Rédaction IA Match",
        "intro": "Les chiffres tombent : le marché mondial de l'IA générative pèse 280 Md$ en 2026, contre 130 Md$ en 2024. Mais le vrai signal est ailleurs : la croissance se déplace des modèles vers les agents.",
        "body": "## Le chiffre brut\n\n**280 Md$**. C'est plus que le chiffre d'affaires mondial du cinéma (~80 Md$) et de la musique (~30 Md$) réunis. C'est l'équivalent du PIB de la Finlande.\n\n## La répartition\n\n- **Modèles fondations** (OpenAI, Anthropic, Google, Mistral) : 95 Md$. Croissance ~80%/an.\n- **Applications verticales** (NotebookLM, Cursor, Suno) : 110 Md$. Croissance ~150%/an.\n- **Agents et automatisation** (Zapier, Make, Replit Agent) : 75 Md$. Croissance ~320%/an.\n\n## L'enseignement clé\n\nLes modèles bruts deviennent une **commodité**. La valeur se concentre sur :\n\n1. **Les workflows pré-câblés** (verticaux).\n2. **Les agents** qui exécutent au lieu de répondre.\n\nC'est cohérent avec ce qu'on observe dans le SaaS depuis 10 ans : la valeur s'éloigne de la techno pour aller vers le résultat business.\n\n## Pour un utilisateur final\n\n- **2024** : tu choisissais ton LLM.\n- **2025** : tu choisissais ton outil vertical (Cursor, Notion AI…).\n- **2026** : tu choisis ton **agent** qui orchestre les outils.\n\n## Pour une entreprise\n\nLa question n'est plus 'quel LLM ?' mais 'quels processus puis-je automatiser à 80% avec un agent fiable ?'. Le ROI se mesure en heures d'humains libérées, pas en accuracy.\n\n## Le piège à éviter\n\nNe pas confondre **hype** et **adoption durable**. Beaucoup d'agents marketés en 2026 ne fonctionnent pas en production. Critères à exiger :\n\n- Journal complet des décisions prises par l'agent.\n- Mode 'dry run' avant exécution réelle.\n- Budget en tokens et en € fixé d'avance.\n- Test sur 50 cas réels avant déploiement.\n\n## Verdict\n\nLe marché est massif et la croissance solide. Mais elle se concentre sur les **agents qui livrent**, pas sur les modèles purs. Si tu construis aujourd'hui, vise la couche supérieure : workflow, contexte métier, expérience utilisateur.",
    },
]


# ----- ACADEMY (Lessons) -----
LESSONS = [
    {
        "id": "l1",
        "order": 1,
        "level": "DÉBUTANT",
        "minutes": 8,
        "title": "Comprendre ce qu'un modèle attend réellement",
        "intro": "Un bon prompt n'est pas une phrase magique. C'est un mini-brief.",
        "body": "Le modèle doit savoir ce qu'il doit produire, pour qui, avec quelles contraintes et sous quel format. Plus la sortie attendue est importante, plus il faut préciser les critères de réussite.",
        "framework": "OBJECTIF · CONTEXTE · CONTRAINTES · FORMAT",
        "steps": [
            "Formule l'objectif en une phrase.",
            "Ajoute le contexte utile.",
            "Liste les contraintes non négociables.",
            "Décris le format final.",
            "Ajoute les critères de qualité.",
        ],
        "before": "Fais-moi un bon texte sur mon projet.",
        "after": "Rédige une présentation de 120 mots pour mon application IA Match. Audience : entrepreneurs non techniques. Objectif : donner envie de tester. Ton : premium, clair, direct. Format : 1 paragraphe + 3 puces de bénéfices.",
    },
    {
        "id": "l2",
        "order": 2,
        "level": "DÉBUTANT",
        "minutes": 10,
        "title": "La méthode des 7 blocs",
        "intro": "Une structure simple à mémoriser pour ne plus jamais oublier l'essentiel.",
        "body": "Rôle, Objectif, Audience, Contexte, Contraintes, Format, Critères de qualité — sept blocs qui couvrent 95% des situations.",
        "framework": "RÔLE · OBJECTIF · AUDIENCE · CONTEXTE · CONTRAINTES · FORMAT · CRITÈRES",
        "steps": [
            "Donne un rôle précis.",
            "Définis l'objectif unique.",
            "Décris l'audience finale.",
            "Donne le contexte nécessaire.",
            "Liste contraintes hard et soft.",
            "Impose un format de sortie.",
            "Ajoute 2-3 critères de qualité.",
        ],
        "before": "Écris une lettre de motivation.",
        "after": "Tu es coach carrière senior. Objectif : lettre de motivation de 200 mots. Audience : DRH d'un cabinet de conseil. Contexte : mon CV en pièce jointe, poste 'Consultant junior'. Contraintes : ton sobre, 0 superlatif. Format : 3 paragraphes. Critères : prouve la valeur, pas la motivation.",
    },
    {
        "id": "l3",
        "order": 3,
        "level": "INTERMÉDIAIRE",
        "minutes": 9,
        "title": "Donner des exemples pour obtenir le bon style",
        "intro": "Le 'few-shot prompting' est la cheat-code la plus sous-exploitée.",
        "body": "Donne 2-3 exemples concrets de la sortie attendue avant ta vraie demande. Le modèle imite le style mieux qu'il ne le décrit.",
        "framework": "FEW-SHOT (2-3 exemples + tâche réelle)",
        "steps": [
            "Choisis 2 ou 3 exemples représentatifs.",
            "Format identique pour chaque exemple.",
            "Sépare exemples et vraie demande.",
            "Demande la sortie au même format.",
        ],
        "before": "Écris-moi des slogans pour ma marque.",
        "after": "Voici 3 slogans premium que j'aime : 'Think different.', 'Just do it.', 'Hello again.'. Crée 5 slogans dans le même esprit minimal pour ma marque IA Match (assistant qui aide à choisir l'IA idéale).",
    },
    {
        "id": "l4",
        "order": 4,
        "level": "INTERMÉDIAIRE",
        "minutes": 8,
        "title": "Itérer sans repartir de zéro",
        "intro": "L'art de raffiner sans tout casser.",
        "body": "Au lieu de relancer tout, demande des modifications ciblées. Le modèle garde le reste du contexte.",
        "framework": "GARDER · CHANGER · EXCLURE",
        "steps": [
            "Liste ce qui doit rester identique.",
            "Liste ce qui doit changer.",
            "Liste ce qui ne doit jamais apparaître.",
            "Demande la même structure de sortie.",
        ],
        "before": "Refais-le.",
        "after": "Garde : la structure 3 paragraphes et le ton sobre. Change : rends le 2e paragraphe plus concret avec un chiffre. Exclus : tout adverbe en -ment.",
    },
    {
        "id": "l5",
        "order": 5,
        "level": "AVANCÉ",
        "minutes": 12,
        "title": "Contrôler le format JSON, tableau ou checklist",
        "intro": "La sortie structurée déverrouille l'automatisation.",
        "body": "Spécifie un schéma exact, donne un exemple, demande une seule chose : 'réponds uniquement avec ce JSON valide'.",
        "framework": "SCHEMA-FIRST",
        "steps": [
            "Définis le schéma précis (champs, types).",
            "Donne 1 exemple complet du JSON attendu.",
            "Impose 'aucun texte avant ou après'.",
            "Ajoute 'sors un JSON valide' explicitement.",
        ],
        "before": "Donne-moi les 3 idées principales.",
        "after": "Réponds UNIQUEMENT avec ce JSON valide, aucun texte autour : {\"ideas\": [{\"title\": string, \"summary\": string, \"impact\": 1-5}]}. Donne-moi 3 idées pour le pitch IA Match.",
    },
]


# ----- ACADEMY (Templates) -----
TEMPLATES = [
    {"id": "t1", "level": "BEGINNER", "title": "Optimiser un CV pour un poste",
     "body": "Tu es recruteur senior spécialisé dans {sector}. Améliore mon CV pour le poste de {target_role}. Contexte : {experience_level}, compétences clés : {skills}, contraintes : {constraints}. Donne : 1) diagnostic rapide, 2) version améliorée des expériences, 3) mots-clés ATS, 4) 3 questions pour me préparer à l'entretien.",
     "variables": ["sector", "target_role", "experience_level", "skills", "constraints"]},
    {"id": "t2", "level": "BEGINNER", "title": "Résumé exécutif d'un document",
     "body": "Analyse le document suivant pour {audience}. Objectif : {decision_or_goal}. Format : résumé exécutif en 8 lignes, 5 points clés, risques, opportunités, décisions à prendre, questions ouvertes. Signale les informations incertaines ou absentes. Document : {document_text}",
     "variables": ["audience", "decision_or_goal", "document_text"]},
    {"id": "t3", "level": "INTERMEDIATE", "title": "Recherche web sourcée",
     "body": "Recherche {topic} sur la période {timeframe}. Priorise les sources suivantes : {source_policy}. Compare les informations selon {criteria}. Donne un résumé, un tableau, les sources, les désaccords éventuels et un niveau de confiance par point important.",
     "variables": ["topic", "timeframe", "source_policy", "criteria"]},
    {"id": "t4", "level": "INTERMEDIATE", "title": "Déboguer une erreur de code",
     "body": "Contexte projet : {project_context}. Fichiers concernés : {files}. Erreur exacte : {error_message}. Comportement attendu : {expected_behavior}. Contraintes : {constraints}. Propose la cause probable, le correctif minimal, puis les tests à lancer. Ne modifie pas d'autres parties du code.",
     "variables": ["project_context", "files", "error_message", "expected_behavior", "constraints"]},
    {"id": "t5", "level": "ADVANCED", "title": "Cahier des charges MVP pour app builder",
     "body": "Construis une application {app_name}. Objectif utilisateur : {user_goal}. Personas : {personas}. Pages : {pages}. Fonctionnalités MVP : {features}. Données : {data_model}. Design system : {design}. Contraintes techniques : {tech_constraints}.",
     "variables": ["app_name", "user_goal", "personas", "pages", "features", "data_model", "design", "tech_constraints"]},
    {"id": "t6", "level": "BEGINNER", "title": "Visuel publicitaire premium",
     "body": "Crée un visuel publicitaire pour {product}. Sujet principal : {subject}. Décor : {setting}. Style : {style}. Composition : {composition}. Lighting : {lighting}. Palette : {palette}. Texte : {text}. Format : {format}. À éviter : {negative}.",
     "variables": ["product", "subject", "setting", "style", "composition", "lighting", "palette", "text", "format", "negative"]},
    {"id": "t7", "level": "ADVANCED", "title": "Plan éditorial trimestriel",
     "body": "Tu es Head of Content B2B. Crée un plan éditorial pour {company} sur {quarter}. Audiences : {audiences}. Objectifs : {objectives}. Canaux : {channels}. Cadence : {cadence}. Donne : thèmes piliers, calendrier hebdo, idées d'articles avec angle et CTA, KPIs.",
     "variables": ["company", "quarter", "audiences", "objectives", "channels", "cadence"]},
    {"id": "t8", "level": "INTERMEDIATE", "title": "Pitch deck investisseurs",
     "body": "Rédige un pitch deck investisseurs pour {startup}. Stade : {stage}. Marché : {market}. Problème : {problem}. Solution : {solution}. Traction : {traction}. Équipe : {team}. Demande : {ask}. Format : 12 slides max avec titre + 3 puces + chiffre clé.",
     "variables": ["startup", "stage", "market", "problem", "solution", "traction", "team", "ask"]},
]


# ----- LIENS UTILES (Resources) -----
RESOURCES = [
    {"id": "r1", "category": "YOUTUBE", "title": "Underscore_", "author": "Micode",
     "summary": "Vulgarisation IA en français, format long, accessible aux curieux.",
     "url": "https://www.youtube.com/@Underscore_"},
    {"id": "r2", "category": "YOUTUBE", "title": "Two Minute Papers", "author": "Károly Zsolnai-Fehér",
     "summary": "Les dernières publications académiques expliquées en 2 minutes.",
     "url": "https://www.youtube.com/@TwoMinutePapers"},
    {"id": "r3", "category": "YOUTUBE", "title": "AI Explained", "author": "AI Explained",
     "summary": "Analyses approfondies des annonces majeures (GPT, Claude, Gemini).",
     "url": "https://www.youtube.com/@aiexplained-official"},
    {"id": "r4", "category": "BLOG", "title": "Anthropic — Prompt engineering guide", "author": "Anthropic",
     "summary": "La documentation officielle pour bien prompter Claude.",
     "url": "https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview"},
    {"id": "r5", "category": "BLOG", "title": "OpenAI Cookbook", "author": "OpenAI",
     "summary": "Recettes officielles, exemples concrets, bonnes pratiques GPT.",
     "url": "https://cookbook.openai.com/"},
    {"id": "r6", "category": "BLOG", "title": "Simon Willison's blog", "author": "Simon Willison",
     "summary": "Veille IA quotidienne d'un des meilleurs experts indépendants.",
     "url": "https://simonwillison.net/"},
    {"id": "r7", "category": "PODCAST", "title": "Lex Fridman Podcast", "author": "Lex Fridman",
     "summary": "Interviews longues avec les fondateurs (Altman, Karpathy, Hinton).",
     "url": "https://lexfridman.com/podcast/"},
    {"id": "r8", "category": "PODCAST", "title": "No Priors", "author": "Sarah Guo & Elad Gil",
     "summary": "Vue VC sur les tendances IA, focus business et marché.",
     "url": "https://www.nopriors.com/"},
    {"id": "r9", "category": "NEWSLETTER", "title": "Ben's Bites", "author": "Ben Tossell",
     "summary": "Newsletter quotidienne, format court, anglais accessible.",
     "url": "https://bensbites.beehiiv.com/"},
    {"id": "r10", "category": "NEWSLETTER", "title": "TLDR AI", "author": "TLDR",
     "summary": "5 minutes par jour, l'essentiel des annonces tech IA.",
     "url": "https://tldr.tech/ai"},
    {"id": "r11", "category": "OUTIL", "title": "Hugging Face", "author": "Hugging Face",
     "summary": "Le hub open-source des modèles, datasets et démos.",
     "url": "https://huggingface.co"},
    {"id": "r12", "category": "OUTIL", "title": "Papers with Code", "author": "Meta AI",
     "summary": "Les benchmarks de référence avec code source associé.",
     "url": "https://paperswithcode.com/"},
]
