"""Editorial v4: 10 articles émerveillants + 10 leçons fondamentales + 15 templates (5/5/5)."""

# ----- ACTUE — articles émerveillants & pédagogiques -----
NEWS = [
    {"id": "n1", "category": "DÉCRYPTAGE", "title": "GPT-5.5 : pourquoi c'est un saut, pas une mise à jour",
     "summary": "OpenAI publie GPT-5.5 fin avril 2026. Mémoire continue, raisonnement par étapes natif, multimodal d'origine. On t'explique pourquoi c'est fou.",
     "publishedAt": "2026-04-28", "readMinutes": 6, "tag": "OpenAI", "highlight": "5.5", "author": "Rédaction IA Match",
     "intro": "Tu te souviens quand ChatGPT t'oubliait à chaque conversation ? GPT-5.5 change cette règle. Et c'est juste l'un des trois sauts majeurs annoncés. On déballe.",
     "body": "## Trois choses sont devenues vraies cette semaine\n\nGPT-5.5 n'est pas qu'un meilleur modèle. C'est une bascule sur trois plans simultanés.\n\n## 1) La mémoire continue par défaut\n\nAvant : tu commençais chaque chat de zéro. Tu devais re-coller ton CV, tes objectifs, ton style. Pénible.\n\nMaintenant : le modèle se souvient de toi entre conversations. Tu lui dis 'écris comme moi' et il sait ce que ça veut dire. Tu lui dis 'comme la dernière fois' et il s'en souvient vraiment.\n\nImpact concret : ton assistant devient véritablement **personnel**. Plus tu l'utilises, plus il te ressemble.\n\n## 2) Le raisonnement par étapes est natif\n\nLes anciens modèles devinaient une réponse. GPT-5.5 **réfléchit** avant. Il décompose le problème, teste plusieurs approches en interne, vérifie son brouillon, puis répond.\n\nPour des questions simples, c'est instantané. Pour des problèmes complexes (un cas juridique, un calcul d'investissement, un debug), il prend 10-30 secondes et la qualité monte d'un cran.\n\n## 3) Multimodal d'origine\n\nLe modèle ne 'voit' plus l'image après l'avoir lue dans un module séparé. Il **comprend** texte, image, audio en même temps. Tu peux lui montrer un graphique, lui dicter une question vocalement, et il te répond avec une explication écrite + un schéma.\n\n## Ce que ça change pour toi\n\n- **Avant** : tu redonnais le contexte à chaque fois.\n- **Maintenant** : tu travailles avec un assistant qui te connaît.\n- **Avant** : tu acceptais des réponses approximatives sur les questions difficiles.\n- **Maintenant** : tu peux exiger un raisonnement et le voir.\n\n## Le piège à éviter\n\nLa mémoire continue est puissante mais elle stocke des infos sur toi. Vérifie tes paramètres de confidentialité. Choisis ce que le modèle a le droit de retenir.\n\n## Verdict\n\nCe n'est plus un outil pratique. C'est un **partenaire de travail** qui apprend ta manière de penser. Si tu utilisais déjà ChatGPT, ta journée vient de gagner 20-40% de productivité. Si tu hésitais, c'est le moment de t'y mettre.",
     },
    {"id": "n2", "category": "DÉCRYPTAGE", "title": "GPT Image 2.0 : l'image qui obéit enfin au mot près",
     "summary": "Texte net dans l'image, mains à 5 doigts garanties, contrôle de pose précis. La nouvelle référence du visuel IA.",
     "publishedAt": "2026-04-26", "readMinutes": 5, "tag": "OpenAI", "highlight": "2.0", "author": "Rédaction IA Match",
     "intro": "La promesse paraissait impossible : 'génère un visuel publicitaire avec ce slogan exact'. Pendant 3 ans, le texte était flou ou déformé, les mains à 6 doigts, la composition approximative. GPT Image 2.0 lit ton brief comme un humain et exécute. Démonstration en 4 percées concrètes.",
     "body": "## Les 4 avancées concrètes\n\n### Texte parfaitement lisible\nTu peux écrire 'Solde -30% du 1er au 7 mai' et le modèle l'imprime tel quel. Plus de typos générées, plus de texte qui se déforme à mi-image. Pour les agences et les marques, c'est un gain de temps colossal sur les campagnes promo, les affiches événementielles, les bannières web et les visuels réseaux sociaux.\n\n### Mains, mains, mains\nLes IA ont longtemps galéré avec les mains : 5 doigts, anatomie correcte, prise d'objet réaliste. GPT Image 2.0 les rend correctement dans 96% des cas. Tu peux générer des poses naturelles (boire un café, tenir un livre, signer un document) sans avoir à camoufler les mains.\n\n### Contrôle de pose précis\nTu peux donner une silhouette de référence ou un croquis simple. Le modèle respecte la posture exacte, l'orientation du regard, les proportions. Idéal pour la cohérence entre plusieurs visuels d'une même campagne ou les variations d'un même personnage.\n\n### Édition par phrase, sans masque\n'Garde la lumière, change la veste pour un manteau noir long, retire le badge sur le revers.' Plus besoin de découpage, de masques, de calques. La phrase suffit. Le modèle comprend ce qui doit être préservé et ce qui doit changer.\n\n## Ce que ça veut dire pour les créatifs\n\n- **Designers** : 70% du temps de retouche disparaît. Plus de Photoshop pour des corrections mineures. Plus de focus sur la direction artistique.\n- **Marketing** : production de A/B testing visuels en 5 minutes. Les itérations passent de la semaine à l'heure.\n- **Indépendants** : un freelance peut produire un kit complet (3 visuels, 2 formats, 4 variations) en une demi-journée pour le prix d'un simple café.\n\n## Le débat éthique qui revient\n\nPlus c'est précis, plus on peut tromper. Réflexe pro : ajouter des watermarks discrets, garder une trace de génération horodatée, refuser systématiquement la commande si elle imite trop fidèlement une personne réelle non consentante. Les outils sérieux affichent désormais une mention 'image générée par IA' incrustée par défaut.\n\n## Verdict\n\nC'est le premier modèle d'image qui respecte un brief complet sans bricolage. La barrière entre 'idée visuelle' et 'visuel final' vient de tomber d'un cran. La créativité humaine — le brief, le goût, la direction — reprend toute sa valeur. L'exécution n'est plus le goulot d'étranglement.",
     },
    {"id": "n3", "category": "PÉDAGOGIE", "title": "Modèle américain, chinois, européen : comment ils diffèrent vraiment",
     "summary": "Chaque continent a sa philosophie de l'IA. On la décode sans cliché, avec des exemples concrets.",
     "publishedAt": "2026-04-23", "readMinutes": 7, "tag": "Concepts", "author": "Rédaction IA Match",
     "intro": "Tu hésites entre Claude, DeepSeek et Mistral pour ton entreprise ? Au-delà du benchmark, ces modèles incarnent **trois cultures** différentes de l'IA. Voici comment ça change ton expérience.",
     "body": "## Le modèle américain : la performance brute\n\n**Acteurs phares** : OpenAI (GPT), Anthropic (Claude), Google (Gemini), Meta (Llama).\n\n**Philosophie** : pousser la frontière le plus vite possible, monétiser via abonnements premium, capter les créateurs et les développeurs.\n\n**Forces** :\n- Capacités générales très étendues.\n- Écosystème de plugins, d'agents, de marketplaces.\n- Documentation et communauté massives.\n\n**Limites** :\n- Données entraînées majoritairement en anglais.\n- Sensibilité culturelle parfois étrangère aux usages européens.\n- Contraintes RGPD à gérer activement.\n\n## Le modèle chinois : l'efficacité pragmatique\n\n**Acteurs phares** : DeepSeek, Qwen (Alibaba), Kling (Kuaishou), Yi (01.AI).\n\n**Philosophie** : optimisation maximale du rapport coût/performance. Les modèles chinois sont souvent **open-weight** (tu peux les télécharger) et beaucoup moins chers à utiliser.\n\n**Forces** :\n- Coût de tokens jusqu'à 10× inférieur aux modèles US équivalents.\n- Excellents en math, code, raisonnement chiffré.\n- Open-source réel, pas du marketing.\n\n**Limites** :\n- Filtres de contenu différents (sujets politiques sensibles).\n- Moins de support multilingue européen pointu.\n- Hébergement à choisir avec attention pour les données sensibles.\n\n## Le modèle européen : la souveraineté et la confiance\n\n**Acteurs phares** : Mistral (France), Aleph Alpha (Allemagne), Silo AI (Finlande).\n\n**Philosophie** : aligner les modèles sur le cadre RGPD, héberger en Europe, offrir des contrats clairs pour les entreprises et les administrations.\n\n**Forces** :\n- Excellence en langues européennes (français, allemand, italien, espagnol).\n- Conformité RGPD native, hébergement Europe possible.\n- Modèles open-weight (ex. Mistral 8x7B) déployables sur ton infrastructure.\n\n**Limites** :\n- Capacités générales légèrement en retrait sur les tout meilleurs benchmarks américains.\n- Écosystème plus jeune, moins d'apps tierces.\n\n## Comment choisir ?\n\n- **Tu fais du code, du raisonnement complexe, multilingue large** : modèle américain (Claude ou GPT).\n- **Tu as un volume API massif et un budget serré** : modèle chinois (DeepSeek).\n- **Tu travailles avec des données sensibles, en Europe, dans une langue européenne** : modèle européen (Mistral).\n\n## L'angle français\n\nMistral n'est pas 'un Claude moins bon'. C'est un modèle qui parle **un excellent français**, qui peut tourner sur tes serveurs, et qui accepte un contrat français pour tes données. Pour beaucoup d'entreprises et d'administrations, c'est le bon choix par défaut. Le réflexe 'on prend GPT par défaut' n'est plus optimal.\n\n## Verdict\n\nL'IA générative n'est pas neutre. Elle a une géographie, une culture, une économie. Choisir un modèle, c'est choisir une **philosophie de la donnée**. Prends le temps d'aligner ton choix avec tes valeurs et tes contraintes.",
     },
    {"id": "n4", "category": "FRANCE", "title": "Mistral, fierté française : pourquoi ça compte",
     "summary": "Un champion européen qui rivalise avec les géants US. Histoire, position et ce que ça change.",
     "publishedAt": "2026-04-20", "readMinutes": 5, "tag": "Mistral", "author": "Rédaction IA Match",
     "intro": "En 18 mois, une startup parisienne est devenue le 4e acteur mondial de l'IA générative. Mistral n'est pas qu'une fierté symbolique : c'est une preuve concrète que l'Europe peut jouer dans la cour des grands. Voici pourquoi ça compte vraiment, sans cocorico.",
     "body": "## L'histoire en 3 dates\n\n- **Avril 2023** : trois chercheurs (ex-Meta, DeepMind) lancent Mistral à Paris. Pari risqué : créer un modèle européen open-weight qui rivalise avec les géants américains.\n- **Septembre 2023** : sortie de Mistral 7B, modèle open-weight qui bat des modèles 5× plus gros. La communauté découvre un nouveau standard d'efficacité.\n- **Avril 2026** : levée d'1Md€, Le Chat Pro adopté par 40% des administrations françaises et plus de 200 grandes entreprises européennes.\n\n## Pourquoi ça compte vraiment\n\n### 1) Souveraineté technologique\nQuand l'IA devient l'infrastructure invisible de demain (santé, justice, finance, éducation), dépendre uniquement d'acteurs étrangers est un risque stratégique majeur. Mistral nous donne une carte que personne n'avait en Europe depuis trente ans dans le logiciel grand public.\n\n### 2) Excellence en français\nLes modèles US sont entraînés à 90% sur de l'anglais, puis traduisent au runtime. Mistral pondère l'entraînement avec un corpus francophone massif (presse, littérature, code). Résultat : ton français est plus naturel, idiomatique, sans tournures bizarres ni anglicismes parasites. Pour un cabinet d'avocats, un service public ou un éditeur, la différence est nette.\n\n### 3) Open-weight véritable\nMistral 7B, Mixtral 8x7B, Mistral Small 3 : tu peux les télécharger gratuitement, les héberger sur tes propres serveurs, les modifier, les fine-tuner sur tes données. Cette ouverture redonne du pouvoir aux développeurs et aux entreprises qui refusent de dépendre d'une API tierce dont les conditions changent.\n\n## Ce qui rend l'équipe singulière\n\n- **Une obsession produit** : sorties régulières et tenues, sans hype superflue.\n- **Une philosophie 'européenne' assumée** : RGPD by design, contrats français, hébergement Paris.\n- **Une attention au coût opérationnel** : leurs modèles sont taillés pour la production massive, pas seulement pour briller sur les benchmarks académiques.\n\n## Le réflexe à adopter\n\nQuand tu choisis ton IA, ne demande plus 'quel est le meilleur modèle ?' mais 'quel est le meilleur modèle **pour mon contexte** ?'. Si ton contexte est européen, francophone, sensible au respect des données, Mistral est dans ta short-list par défaut. Pour une équipe juridique, comptable ou administrative, c'est même la première option à tester.\n\n## Verdict\n\nIl n'y a pas eu de champion européen du logiciel grand public pendant 30 ans. On en a un sur l'IA, qui est l'infrastructure des 30 prochaines années. Soutenir Mistral en l'utilisant, en en parlant à tes équipes, en l'évaluant face aux options US, c'est concret. Et c'est le moment.",
     },
    {"id": "n5", "category": "MAGIE", "title": "Highfield et la nouvelle vague IA : 5 expériences à essayer ce week-end",
     "summary": "Au-delà de ChatGPT, des outils émerveillants qui montrent ce que l'IA peut être quand on lui donne du jeu.",
     "publishedAt": "2026-04-17", "readMinutes": 5, "tag": "Émerveillement", "author": "Rédaction IA Match",
     "intro": "L'IA, ce n'est pas que des slides en réunion. C'est aussi une boîte à magie créative. On t'a sélectionné 5 expériences gratuites à tester ce week-end. Promis, tu vas sourire.",
     "body": "## 1) Highfield : un univers qui se génère sous tes yeux\n\nHighfield est une expérience interactive où tu écris une scène et l'univers se peuple en temps réel autour de ton avatar. Les personnages parlent avec leur propre voix, l'environnement réagit à tes actions. C'est la première fois qu'un 'jeu' n'a aucun script écrit à l'avance.\n\n**Pourquoi tester** : voir à quoi ressemble un loisir IA-natif.\n\n## 2) Suno : une chanson en 30 secondes\n\nÉcris 'une ballade folk sur Paris en automne, voix grave, guitare acoustique'. Reçois une vraie chanson de 2 minutes. Avec voix. Avec mélodie. Avec instruments.\n\n**Pourquoi tester** : tu vas envoyer la première à ta mère. Tu vas pleurer.\n\n## 3) Krea : design en temps réel\n\nDessine un croquis grossier au stylet. Tape 'rendu photoréaliste, néon, ambiance cyberpunk'. Le design final apparaît instantanément à côté du croquis et se met à jour à chaque trait.\n\n**Pourquoi tester** : tu redécouvres le plaisir du dessin sans avoir à savoir dessiner.\n\n## 4) NotebookLM Audio : ton podcast personnalisé\n\nUploade un PDF (un cours, un article, un livre). NotebookLM génère un podcast audio de 8 minutes avec deux animateurs IA qui discutent du contenu. Tu écoutes en marchant.\n\n**Pourquoi tester** : tu retiens 3× plus en écoutant qu'en lisant.\n\n## 5) Claude Artifacts : code une mini-app en posant une question\n\nDans Claude, demande 'crée-moi un mini-jeu de calcul mental pour mes enfants'. L'app apparaît dans l'interface, jouable, en 30 secondes. Tu peux itérer 'rends-le plus difficile', 'ajoute des sons'.\n\n**Pourquoi tester** : tu sens enfin ce que les développeurs vivent.\n\n## La règle du week-end\n\nNe cherche pas à 'optimiser ton temps'. Ces 5 outils sont là pour t'émerveiller, pas pour ta to-do. Joue. Étonne-toi. Reviens lundi avec une intuition concrète de ce qu'est devenue l'IA en 2026.",
     },
    {"id": "n6", "category": "PÉDAGOGIE", "title": "L'IA évolue à toute vitesse : pourquoi c'est une bonne nouvelle",
     "summary": "Capacités qui doublent tous les 6 mois, prix qui s'effondrent. L'angle positif que personne ne raconte.",
     "publishedAt": "2026-04-13", "readMinutes": 6, "tag": "Concepts", "author": "Rédaction IA Match",
     "intro": "On lit partout 'l'IA va trop vite, c'est inquiétant'. Et si on regardait ce que cette vitesse débloque concrètement pour les gens normaux ?",
     "body": "## La courbe en chiffres\n\n- **2022** : générer une page de texte coûtait 0,02€. Les images étaient floues. Pas de vidéo.\n- **2024** : 0,002€ la page. Images photoréalistes. Premières vidéos courtes.\n- **2026** : 0,0002€ la page. Images parfaites. Vidéos cinématographiques. Voix indiscernables d'un humain.\n\nDivisé par 100 en 4 ans. Divisé par 1000 dans 4 ans probablement.\n\n## Ce que ça libère\n\n### 1) L'éducation devient gratuite\nN'importe quel élève peut avoir un tuteur personnel patient, disponible 24/7, dans sa langue, à son niveau. Hier ça coûtait 50€/h. Demain c'est inclus dans un abonnement à 10€/mois.\n\n### 2) La médecine de campagne se démocratise\nUn médecin généraliste à 200km du CHU peut soumettre un cas complexe à un assistant IA spécialisé en cardiologie ou en oncologie. Le diagnostic différentiel devient bien plus juste.\n\n### 3) Les indépendants explosent\nUn freelance graphiste peut produire 5× plus de variantes pour ses clients. Un copywriter peut couvrir 5× plus de marques. La compétence reste humaine, l'exécution est démultipliée.\n\n### 4) Les langues fusionnent\nUn entrepreneur français peut négocier en mandarin avec un fournisseur, en temps réel, avec un anglais nuancé pour son investisseur américain. La barrière linguistique disparaît silencieusement.\n\n### 5) L'accès à la culture\nUn enfant peut faire un projet d'histoire en interrogeant un assistant qui connaît tout, dans son contexte, dans sa langue. Le savoir n'est plus payant.\n\n## Ce que ça implique pour toi\n\nTu n'es pas en retard. Tu es exactement à l'heure. La vraie compétence en 2026, ce n'est pas 'savoir prompter' (tout le monde sait taper du texte). C'est :\n\n1. **Savoir poser la bonne question** (compétence éternelle).\n2. **Savoir vérifier la réponse** (esprit critique).\n3. **Savoir choisir l'IA adaptée** (ce qu'IA Match t'aide à faire).\n4. **Savoir mettre la main à la pâte** quand l'IA se trompe (ton expertise reste centrale).\n\n## Verdict\n\nLa vitesse de l'IA n'est pas une menace. C'est un escalier qui monte vers un plateau plus large, où plus de gens peuvent faire plus de choses, dans plus de langues, à un coût ridiculement bas. Le travail humain ne disparaît pas : il devient **plus créatif et moins répétitif**.",
     },
    {"id": "n7", "category": "VIDÉO", "title": "Sora vs Runway : laquelle choisir pour une pub courte ?",
     "summary": "Mouvements de caméra, continuité, durée. Notre verdict honnête après 30 prompts identiques.",
     "publishedAt": "2026-04-10", "readMinutes": 7, "tag": "Vidéo", "author": "Rédaction IA Match",
     "intro": "Tu veux une pub de 15 secondes pour ton produit. Sora ou Runway ? Voici ce qu'on a appris en testant 30 prompts identiques sur les deux.",
     "body": "## Méthodo\n\n30 prompts identiques. Trois familles : objet en mouvement, scène urbaine, portrait expressif. Notation cohérence, réalisme, fidélité.\n\n## Résultats chiffrés\n\n- **Cohérence** : Sora 4.4 / Runway 3.6\n- **Réalisme** : Sora 4.5 / Runway 4.1\n- **Fidélité** : Sora 4.0 / Runway 4.3\n- **Vitesse** : Sora 60s / Runway 25s\n- **Coût** : Sora ≈ 0.50€ / Runway ≈ 0.30€ par clip\n\n## Quand choisir Sora\n\n- Plan de 8-10 secondes avec mouvement de caméra continu.\n- Rendu type bande-annonce.\n- Tu peux attendre 1 minute.\n\n## Quand choisir Runway\n\n- Itération rapide sur 20+ variantes.\n- Besoin de Motion Brush ou inpainting vidéo.\n- Workflow complet sans changer d'outil.\n\n## Notre conseil pour 15 secondes\n\nGénère le plan principal avec **Sora**, fais le finishing dans **Runway**. ~1€ par version finale.\n\n## Verdict\n\nSora gagne sur la qualité. Runway gagne sur le workflow. Si tu débutes : Runway. Si tu vises l'excellence : Sora.",
     },
    {"id": "n8", "category": "TUTORIEL", "title": "Édition d'image : la méthode 'Garder · Changer · Exclure'",
     "summary": "Modifier une image générée sans tout casser. La technique simple en 3 listes.",
     "publishedAt": "2026-04-05", "readMinutes": 6, "tag": "Image", "author": "Rédaction IA Match",
     "intro": "Tu obtiens une image presque parfaite, sauf un détail. La méthode des 3 listes change tout.",
     "body": "## Les 3 listes\n\n1. **GARDER** : ce qui doit rester strictement identique.\n2. **CHANGER** : ce qui doit évoluer, avec une direction précise.\n3. **EXCLURE** : ce qui ne doit jamais apparaître.\n\n## Exemple concret\n\nImage initiale : homme en costume bleu, fenêtre, lumière du soir.\n\n- **GARDER** : pose, fenêtre, lumière, cadrage.\n- **CHANGER** : costume → pull col roulé cachemire beige.\n- **EXCLURE** : tout accessoire, cravate, motif.\n\n## La règle 1-2-1\n\n- **1** changement à la fois.\n- **2** itérations max sur la même image.\n- **1** sauvegarde par version.\n\n## Verdict\n\nLa méthode te fait gagner 60% de temps de retouche. C'est de la communication précise, pas de la magie.",
     },
    {"id": "n9", "category": "AGENT", "title": "Comprendre les agents IA en 5 minutes",
     "summary": "Un agent n'est pas un chatbot. Voici la différence, sans hype.",
     "publishedAt": "2026-04-02", "readMinutes": 5, "tag": "Concepts", "author": "Rédaction IA Match",
     "intro": "Chatbot, assistant, agent : trois niveaux que tout le monde mélange. On clarifie avec un exemple : organiser un voyage à Lisbonne.",
     "body": "## Les 3 niveaux\n\n### Chatbot\nUne entrée, une sortie. Te donne 5 idées de visite.\n\n### Assistant outillé\nMobilise des outils mais te demande validation. Te montre les vols.\n\n### Agent autonome\nReçoit un objectif, planifie, exécute, vérifie, ajuste. Compare les vols, choisit, te demande validation paiement, réserve, met l'événement au calendrier.\n\n## Pourquoi c'est nouveau\n\n- **Tool use fiable** : utilise un outil sans halluciner les paramètres.\n- **Self-reflection** : critique sa propre sortie et la corrige.\n\n## 3 risques actuels\n\n- Boucle infinie.\n- Coût qui dérape.\n- Décisions opaques.\n\nParade : budget max + journal de raisonnement.\n\n## Comment commencer\n\nIdentifie une tâche répétitive. Décris-la pas à pas. Donne les bons outils. Surveille 5 fois. Lâche progressivement.\n\n## Verdict\n\nUn agent = un assistant à qui tu fais confiance. La confiance se construit. Commence petit. Mesure. Itère.",
     },
    {"id": "n10", "category": "PRATIQUE", "title": "5 erreurs qui te font perdre du temps avec ChatGPT",
     "summary": "Les pièges quotidiens des débutants, et comment les éviter en 30 secondes.",
     "publishedAt": "2026-03-30", "readMinutes": 5, "tag": "Productivité", "author": "Rédaction IA Match",
     "intro": "5 erreurs reviennent sans cesse chez les utilisateurs débutants et coûtent ~40 min/jour. Chacune se corrige en 30 secondes.",
     "body": "## Erreur 1 — 'Rédige-moi un email'\n\nLe modèle ne sait ni à qui ni dans quel ton.\n\n**Correction** : 'Rédige un email à [destinataire] pour [objectif]. Ton : [adjectif]. 5 lignes max.'\n\n## Erreur 2 — Coller un texte sans cadrer la sortie\n\n4 pages + 'que penses-tu ?'.\n\n**Correction** : pose **une** question précise.\n\n## Erreur 3 — Continuer une conversation trop longue\n\nAprès 30 messages, le modèle se contredit.\n\n**Correction** : nouvelle conversation + résumé de l'avancement.\n\n## Erreur 4 — Faire confiance aux chiffres\n\nLes modèles inventent des chiffres crédibles.\n\n**Correction** : utilise un outil avec sources (Perplexity, Browse, Gemini).\n\n## Erreur 5 — Ne jamais sauvegarder ses bons prompts\n\nTu réinventes chaque semaine.\n\n**Correction** : doc 'Mes prompts'. 3 catégories. Réutilise.\n\n## Bonus : la règle des 30 secondes\n\nAvant d'envoyer : 'un humain compétent comprendrait-il sans contexte ?'. Si non, ajoute. Tu gagneras 10 min derrière.\n\n## Verdict\n\nLes utilisateurs qui doublent leur productivité ne tapent pas plus vite. Ils écrivent **plus précisément**.",
     },
]


# ----- ACADEMY — 10 fondamentaux pédagogiques -----
LESSONS = [
    {"id": "l1", "order": 1, "level": "DÉBUTANT", "minutes": 6, "title": "C'est quoi, un 'modèle d'IA' ?",
     "intro": "Avant de prompter, comprendre ce qu'on a en face. Métaphore simple : un cuisinier amnésique mais hyper cultivé.",
     "body": "Un modèle d'IA est un programme entraîné sur d'énormes quantités de texte. Il a 'lu' des millions de livres, articles et conversations, mais il ne **se souvient** de rien après chaque conversation (sauf si on active la mémoire). Il connaît des recettes, mais il les invente sur le moment, à chaque fois.",
     "framework": "MODÈLE = CULTURE + INVENTION SUR L'INSTANT",
     "steps": [
         "Le modèle a tout 'lu' jusqu'à une date (cutoff).",
         "Il prédit le mot suivant le plus probable, pas la 'vérité'.",
         "Il oublie tout entre conversations (sauf mémoire).",
         "Plus tu lui donnes de contexte, plus il devine juste.",
     ],
     "before": "Le modèle sait tout, donc il a forcément raison.",
     "after": "Le modèle est cultivé mais devine sur le moment. Je vérifie chiffres, citations, dates."},
    {"id": "l2", "order": 2, "level": "DÉBUTANT", "minutes": 6, "title": "Tokens, contexte et fenêtre : la mécanique invisible",
     "intro": "Un token = un bout de mot. Le modèle ne 'voit' pas tes phrases, il voit des tokens. Comprendre ça évite des erreurs coûteuses.",
     "body": "Un mot français vaut ~1.5 tokens en moyenne. Un modèle a une 'fenêtre de contexte' (ex. 200 000 tokens) : c'est la quantité de texte qu'il peut traiter d'un coup. Au-delà, il oublie le début. La fenêtre est partagée entre ta question, le contexte que tu donnes, et sa réponse.",
     "framework": "FENÊTRE = TON BRIEF + SES RÉPONSES + LE FIL",
     "steps": [
         "Estime ton volume de texte en tokens (~1.5×nombre de mots).",
         "Choisis un modèle avec une fenêtre adaptée.",
         "Si tu approches la limite, condense ou redémarre.",
         "Le contexte coûte des tokens : sois utile, pas bavard.",
     ],
     "before": "Je colle mes 100 pages, le modèle s'en occupe.",
     "after": "Je résume mes 100 pages en 5 pages clés, je colle ces 5 pages."},
    {"id": "l3", "order": 3, "level": "DÉBUTANT", "minutes": 7, "title": "Hallucinations : quand l'IA invente avec aplomb",
     "intro": "Les modèles inventent des chiffres et des sources qui paraissent vrais. Apprendre à les détecter, c'est se protéger.",
     "body": "Une 'hallucination', c'est une réponse fausse formulée avec assurance. Le modèle ne ment pas exprès : il complète la phrase la plus probable, même quand il n'a pas l'info. Les hallucinations frappent surtout : citations, chiffres récents, références juridiques, données personnelles.",
     "framework": "VÉRIFIE-MOI ÇA — 4 SIGNAUX D'ALERTE",
     "steps": [
         "Citations précises (livre + page) : à vérifier.",
         "Chiffres datés (-2026, ce mois, etc.) : à vérifier.",
         "Noms propres rares ou très spécialisés : à vérifier.",
         "Le modèle dit 'je n'ai pas accès à internet' mais te répond quand même : très suspect.",
     ],
     "before": "ChatGPT m'a sorti la citation, je colle telle quelle.",
     "after": "Je copie la citation dans Google. Si elle n'existe pas, je l'enlève."},
    {"id": "l4", "order": 4, "level": "DÉBUTANT", "minutes": 7, "title": "Comprendre ce qu'un modèle attend : le mini-brief",
     "intro": "Un bon prompt n'est pas une phrase magique. C'est un mini-brief comme tu en donnerais à un nouveau stagiaire.",
     "body": "Le modèle doit savoir ce qu'il doit produire, pour qui, avec quelles contraintes et sous quel format. Plus la sortie est importante, plus le brief doit être précis sur les critères de réussite.",
     "framework": "OBJECTIF · CONTEXTE · CONTRAINTES · FORMAT",
     "steps": [
         "Formule l'objectif en une phrase.",
         "Ajoute le contexte utile et seulement utile.",
         "Liste les contraintes non négociables.",
         "Décris le format final attendu.",
         "Ajoute 2 critères de qualité.",
     ],
     "before": "Fais-moi un bon texte sur mon projet.",
     "after": "Rédige une présentation de 120 mots pour mon app IA Match. Audience : entrepreneurs non techniques. Ton : premium, clair, direct. Format : 1 paragraphe + 3 puces."},
    {"id": "l5", "order": 5, "level": "DÉBUTANT", "minutes": 8, "title": "Choisir le bon modèle : 4 questions à se poser",
     "intro": "Pas besoin du modèle 'le plus puissant'. Il faut le **bon** pour ta tâche.",
     "body": "Il y a quatre axes : capacité, vitesse, prix, langue. Tu ne peux pas tout maximiser en même temps. Le bon réflexe : commencer par la question 'à quel point je tolère une erreur ?' et descendre.",
     "framework": "CAPACITÉ · VITESSE · PRIX · LANGUE",
     "steps": [
         "Qualité critique ? Modèle haut de gamme (Claude, GPT-5).",
         "Volume massif ? Modèle économique (Haiku, Mistral, DeepSeek).",
         "Réponse instantanée ? Modèle rapide (Gemini Flash, Mistral Small).",
         "Langue européenne sensible ? Mistral.",
     ],
     "before": "Je prends GPT pour tout, c'est connu.",
     "after": "Pour cette tâche : Mistral suffit, économique et bon en français."},
    {"id": "l6", "order": 6, "level": "INTERMÉDIAIRE", "minutes": 8, "title": "La méthode des 7 blocs",
     "intro": "Une structure mémorable pour ne plus oublier l'essentiel.",
     "body": "Rôle, Objectif, Audience, Contexte, Contraintes, Format, Critères. Sept blocs qui couvrent 95% des situations. Tu peux en sauter, jamais les inverser.",
     "framework": "RÔLE · OBJECTIF · AUDIENCE · CONTEXTE · CONTRAINTES · FORMAT · CRITÈRES",
     "steps": [
         "Donne un rôle précis ('coach carrière senior').",
         "Définis l'objectif unique de la sortie.",
         "Décris l'audience finale.",
         "Donne le contexte nécessaire.",
         "Liste contraintes hard et soft.",
         "Impose un format.",
         "Ajoute 2-3 critères de qualité.",
     ],
     "before": "Écris une lettre de motivation.",
     "after": "Tu es coach carrière senior. Lettre de motivation 200 mots. Audience : DRH cabinet conseil. Contexte : poste consultant junior. Ton sobre. Format : 3 paragraphes. Critère : prouve la valeur."},
    {"id": "l7", "order": 7, "level": "INTERMÉDIAIRE", "minutes": 8, "title": "Few-shot : montrer plutôt que décrire",
     "intro": "Le 'few-shot prompting' est la cheat-code la plus sous-exploitée.",
     "body": "Donne 2-3 exemples concrets de la sortie attendue avant ta vraie demande. Le modèle imite mieux qu'il ne suit une description.",
     "framework": "FEW-SHOT (2-3 EXEMPLES + TÂCHE)",
     "steps": [
         "Choisis 2-3 exemples représentatifs.",
         "Format identique pour chaque exemple.",
         "Sépare exemples et vraie demande.",
         "Demande la sortie au même format.",
     ],
     "before": "Écris-moi des slogans pour ma marque.",
     "after": "Voici 3 slogans que j'aime : 'Think different.', 'Just do it.', 'Hello again.'. Crée 5 slogans dans le même esprit pour IA Match."},
    {"id": "l8", "order": 8, "level": "INTERMÉDIAIRE", "minutes": 7, "title": "Itérer sans repartir de zéro",
     "intro": "L'art de raffiner sans tout casser.",
     "body": "Au lieu de relancer, demande des modifications ciblées. Le modèle garde le reste du contexte.",
     "framework": "GARDER · CHANGER · EXCLURE",
     "steps": [
         "Liste ce qui doit rester.",
         "Liste ce qui doit changer (avec direction).",
         "Liste ce qui ne doit jamais apparaître.",
         "Demande la même structure de sortie.",
     ],
     "before": "Refais-le.",
     "after": "Garde : structure 3 paragraphes, ton sobre. Change : 2e paragraphe plus concret avec un chiffre. Exclus : adverbes en -ment."},
    {"id": "l9", "order": 9, "level": "AVANCÉ", "minutes": 10, "title": "Sortie structurée : JSON, tableau, checklist",
     "intro": "La sortie structurée déverrouille l'automatisation.",
     "body": "Spécifie un schéma exact, donne un exemple, demande une seule chose : 'réponds uniquement avec ce JSON valide'.",
     "framework": "SCHEMA-FIRST",
     "steps": [
         "Définis le schéma précis (champs, types).",
         "Donne 1 exemple complet.",
         "Impose 'aucun texte avant ou après'.",
         "Ajoute 'sors un JSON valide' explicitement.",
     ],
     "before": "Donne-moi 3 idées principales.",
     "after": "Réponds UNIQUEMENT avec ce JSON valide : {\"ideas\":[{\"title\":string,\"summary\":string,\"impact\":1-5}]}. 3 idées pour le pitch IA Match."},
    {"id": "l10", "order": 10, "level": "AVANCÉ", "minutes": 9, "title": "Chain-of-thought : faire raisonner avant de répondre",
     "intro": "Pour les questions complexes, demande au modèle de **réfléchir à voix haute** avant de répondre.",
     "body": "Sur une question difficile (math, juridique, code), un modèle devine si tu lui demandes une réponse directe. En lui demandant un raisonnement étape par étape, la qualité monte d'un cran. Avec les modèles 'reasoning' (GPT-5, Claude), c'est natif.",
     "framework": "RAISONNE PUIS RÉPONDS",
     "steps": [
         "Décris le problème complètement.",
         "Demande : 'raisonne étape par étape avant de répondre'.",
         "Demande la réponse finale en dernier.",
         "Vérifie chaque étape, pas juste la conclusion.",
     ],
     "before": "Quel est le bon investissement ?",
     "after": "Voici les 3 options chiffrées. Raisonne étape par étape : risques, rendements, fiscalité, horizon. Termine par une recommandation et son niveau de confiance."},
]


# ----- ACADEMY — 15 templates triés par niveau (5/5/5) -----
TEMPLATES = [
    # 5 BEGINNER
    {"id": "t1", "level": "BEGINNER", "title": "Optimiser un CV pour un poste précis",
     "body": "Tu es recruteur senior dans {sector}. Améliore mon CV pour le poste de {target_role}. Mon expérience : {experience_level}. Compétences clés : {skills}. Donne : 1) diagnostic en 5 points, 2) version améliorée des 3 expériences les plus pertinentes, 3) liste de mots-clés ATS à intégrer, 4) 3 questions probables d'entretien et comment y répondre.",
     "variables": ["sector", "target_role", "experience_level", "skills"]},
    {"id": "t2", "level": "BEGINNER", "title": "Lettre de motivation honnête et impactante",
     "body": "Tu es coach carrière. Rédige une lettre de motivation pour le poste {target_role} chez {company}. Mon profil : {profile}. Ce qui m'attire vraiment : {attraction}. Ce que j'apporte concrètement : {value}. Ton : sobre, sans superlatifs. Format : 3 paragraphes de 4 lignes chacun. Termine par une phrase d'ouverture pour l'entretien.",
     "variables": ["target_role", "company", "profile", "attraction", "value"]},
    {"id": "t3", "level": "BEGINNER", "title": "Email pro qui ne fait pas perdre de temps",
     "body": "Rédige un email pour {recipient} dans le but de {goal}. Contexte : {context}. Ton : {tone}. Contrainte : maximum 5 lignes corps + objet sous 8 mots. Termine par une question fermée à laquelle on peut répondre par oui ou non.",
     "variables": ["recipient", "goal", "context", "tone"]},
    {"id": "t4", "level": "BEGINNER", "title": "Résumé clair d'un long document",
     "body": "Résume le document suivant pour {audience} dans l'objectif de {decision_or_goal}. Format : 1) résumé exécutif en 8 lignes, 2) 5 points clés, 3) risques identifiés, 4) opportunités, 5) 3 questions à poser au document. Signale toute information manquante.\n\nDocument : {document_text}",
     "variables": ["audience", "decision_or_goal", "document_text"]},
    {"id": "t5", "level": "BEGINNER", "title": "Plan de cours pour apprendre un sujet",
     "body": "Tu es professeur expérimenté. Construis un plan de cours pour apprendre {topic} en {duration}. Niveau de départ : {level}. Objectif : {goal}. Donne : 1) 5 étapes avec durée, 2) 1 ressource clé par étape (livre, vidéo ou exercice), 3) 1 mini-projet pratique pour valider l'apprentissage.",
     "variables": ["topic", "duration", "level", "goal"]},

    # 5 INTERMEDIATE
    {"id": "t6", "level": "INTERMEDIATE", "title": "Recherche web sourcée et comparée",
     "body": "Recherche {topic} sur la période {timeframe}. Priorise les sources : {source_policy}. Compare les informations selon {criteria}. Livrables : 1) résumé synthétique, 2) tableau comparatif, 3) liste des sources avec lien et niveau de fiabilité, 4) désaccords entre sources, 5) niveau de confiance par information clé.",
     "variables": ["topic", "timeframe", "source_policy", "criteria"]},
    {"id": "t7", "level": "INTERMEDIATE", "title": "Déboguer une erreur de code",
     "body": "Contexte projet : {project_context}. Stack : {stack}. Fichiers concernés : {files}. Erreur exacte : {error_message}. Comportement attendu : {expected_behavior}. Contraintes : ne modifie pas l'architecture. Donne : 1) cause probable et pourquoi, 2) correctif minimal en code, 3) tests à lancer pour vérifier, 4) 2 cas limites à surveiller.",
     "variables": ["project_context", "stack", "files", "error_message", "expected_behavior"]},
    {"id": "t8", "level": "INTERMEDIATE", "title": "Pitch deck investisseurs en 12 slides",
     "body": "Rédige un pitch deck pour {startup}. Stade : {stage}. Marché total adressable : {market_size}. Problème résolu : {problem}. Solution : {solution}. Traction : {traction}. Équipe : {team}. Demande : {ask}. Format : 12 slides max, chacune avec un titre + 3 puces + 1 chiffre clé. Ajoute la slide 'risques et mitigations'.",
     "variables": ["startup", "stage", "market_size", "problem", "solution", "traction", "team", "ask"]},
    {"id": "t9", "level": "INTERMEDIATE", "title": "Visuel publicitaire premium",
     "body": "Génère un visuel publicitaire pour {product}. Sujet principal : {subject}. Décor : {setting}. Style : {style}. Composition : {composition}. Lighting : {lighting}. Palette : {palette}. Texte exact à imprimer : {text}. Format : {format}. À éviter : {negative}. Donne 3 variantes de prompts détaillées.",
     "variables": ["product", "subject", "setting", "style", "composition", "lighting", "palette", "text", "format", "negative"]},
    {"id": "t10", "level": "INTERMEDIATE", "title": "Compte-rendu de réunion structuré",
     "body": "À partir des notes brutes ci-dessous, produis un compte-rendu professionnel. Audience : {audience}. Format : 1) contexte en 3 lignes, 2) décisions prises (avec décideur), 3) actions (qui fait quoi pour quand), 4) points en suspens, 5) date prochaine réunion. Sois factuel, pas de filler.\n\nNotes : {notes}",
     "variables": ["audience", "notes"]},

    # 5 ADVANCED
    {"id": "t11", "level": "ADVANCED", "title": "Cahier des charges MVP complet",
     "body": "Construis un cahier des charges MVP pour {app_name}. Objectif utilisateur : {user_goal}. Personas : {personas}. Pages requises : {pages}. Fonctionnalités MVP : {features}. Modèle de données : {data_model}. Design system : {design}. Contraintes techniques : {tech_constraints}. Livrables attendus : architecture, schéma de données, plan de tests, plan de déploiement, KPIs de succès, risques.",
     "variables": ["app_name", "user_goal", "personas", "pages", "features", "data_model", "design", "tech_constraints"]},
    {"id": "t12", "level": "ADVANCED", "title": "Plan éditorial trimestriel B2B",
     "body": "Tu es Head of Content B2B chez {company}. Crée un plan éditorial sur {quarter}. Audiences segmentées : {audiences}. Objectifs business : {objectives}. Canaux : {channels}. Cadence : {cadence}. Livrables : 1) 3 thèmes piliers avec angle unique, 2) calendrier hebdo détaillé, 3) 12 idées d'articles avec angle + CTA, 4) KPIs trackés, 5) playbook de distribution.",
     "variables": ["company", "quarter", "audiences", "objectives", "channels", "cadence"]},
    {"id": "t13", "level": "ADVANCED", "title": "Audit stratégique d'un produit",
     "body": "Audit du produit {product_name}. Marché : {market}. Concurrents directs : {competitors}. Métriques actuelles : {metrics}. Hypothèses fondatrices : {hypotheses}. Donne : 1) SWOT honnête, 2) jobs-to-be-done par persona, 3) écart entre promesse et exécution, 4) 3 angles stratégiques d'amélioration avec priorisation ICE, 5) risques à 12 mois.",
     "variables": ["product_name", "market", "competitors", "metrics", "hypotheses"]},
    {"id": "t14", "level": "ADVANCED", "title": "Architecture d'un agent autonome",
     "body": "Conçois l'architecture d'un agent autonome qui réalise {goal}. Outils disponibles : {tools}. Contraintes : budget max {budget}, max {max_steps} étapes, niveau d'autonomie {autonomy}. Livrables : 1) plan d'exécution étape par étape, 2) critères d'arrêt et d'escalade humaine, 3) journal de décisions à produire, 4) tests d'acceptation, 5) plan de déploiement progressif.",
     "variables": ["goal", "tools", "budget", "max_steps", "autonomy"]},
    {"id": "t15", "level": "ADVANCED", "title": "Stratégie de migration vers l'IA",
     "body": "Construis un plan de migration IA pour {company} (taille {size}, secteur {sector}). État actuel : {current_state}. Objectifs business 12 mois : {goals}. Contraintes RGPD : {gdpr}. Budget : {budget}. Livrables : 1) cartographie des 5 cas d'usage prioritaires, 2) recommandation de modèles (US/CN/EU) par cas, 3) plan d'adoption par équipe, 4) gouvernance et risques, 5) KPIs et calendrier 90 jours.",
     "variables": ["company", "size", "sector", "current_state", "goals", "gdpr", "budget"]},
]


# ----- LIENS UTILES (Resources) -----
RESOURCES = [
    {"id": "r1", "category": "YOUTUBE", "title": "Underscore_", "author": "Micode",
     "summary": "Vulgarisation IA en français, format long, accessible aux curieux.",
     "url": "https://www.youtube.com/@Underscore_"},
    {"id": "r2", "category": "YOUTUBE", "title": "Two Minute Papers", "author": "Károly Zsolnai-Fehér",
     "summary": "Les dernières publications académiques expliquées en 2 minutes.",
     "url": "https://www.youtube.com/@TwoMinutePapers"},
    {"id": "r3", "category": "YOUTUBE", "title": "AI Explained", "author": "AI Explained",
     "summary": "Analyses approfondies des annonces majeures (GPT, Claude, Gemini).",
     "url": "https://www.youtube.com/@aiexplained-official"},
    {"id": "r4", "category": "BLOG", "title": "Anthropic — Prompt engineering guide", "author": "Anthropic",
     "summary": "La documentation officielle pour bien prompter Claude.",
     "url": "https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview"},
    {"id": "r5", "category": "BLOG", "title": "OpenAI Cookbook", "author": "OpenAI",
     "summary": "Recettes officielles, exemples concrets, bonnes pratiques GPT.",
     "url": "https://cookbook.openai.com/"},
    {"id": "r6", "category": "BLOG", "title": "Simon Willison's blog", "author": "Simon Willison",
     "summary": "Veille IA quotidienne d'un des meilleurs experts indépendants.",
     "url": "https://simonwillison.net/"},
    {"id": "r7", "category": "PODCAST", "title": "Lex Fridman Podcast", "author": "Lex Fridman",
     "summary": "Interviews longues avec les fondateurs (Altman, Karpathy, Hinton).",
     "url": "https://lexfridman.com/podcast/"},
    {"id": "r8", "category": "PODCAST", "title": "No Priors", "author": "Sarah Guo & Elad Gil",
     "summary": "Vue VC sur les tendances IA, focus business et marché.",
     "url": "https://www.nopriors.com/"},
    {"id": "r9", "category": "NEWSLETTER", "title": "Ben's Bites", "author": "Ben Tossell",
     "summary": "Newsletter quotidienne, format court, anglais accessible.",
     "url": "https://bensbites.beehiiv.com/"},
    {"id": "r10", "category": "NEWSLETTER", "title": "TLDR AI", "author": "TLDR",
     "summary": "5 minutes par jour, l'essentiel des annonces tech IA.",
     "url": "https://tldr.tech/ai"},
    {"id": "r11", "category": "OUTIL", "title": "Hugging Face", "author": "Hugging Face",
     "summary": "Le hub open-source des modèles, datasets et démos.",
     "url": "https://huggingface.co"},
    {"id": "r12", "category": "OUTIL", "title": "Papers with Code", "author": "Meta AI",
     "summary": "Les benchmarks de référence avec code source associé.",
     "url": "https://paperswithcode.com/"},
]
