"""Editorial v4: 10 articles émerveillants + 10 leçons fondamentales + 15 templates (5/5/5)."""

# ----- ACTUE — articles émerveillants & pédagogiques -----
NEWS = [
    {"id": "n1", "category": "DÉCRYPTAGE", "title": "GPT-5.5 : pourquoi c'est un saut, pas une mise à jour",
     "summary": "OpenAI publie GPT-5.5 fin avril 2026. Mémoire continue, raisonnement par étapes natif, multimodal d'origine. On t'explique pourquoi c'est fou.",
     "publishedAt": "2026-04-28", "readMinutes": 6, "tag": "OpenAI", "highlight": "5.5", "author": "Rédaction IA Match",
     "intro": "Tu te souviens quand ChatGPT t'oubliait à chaque conversation ? GPT-5.5 change cette règle. Et c'est juste l'un des trois sauts majeurs annoncés. On déballe.",
     "body": "## Trois choses sont devenues vraies cette semaine\n\nGPT-5.5 n'est pas qu'un meilleur modèle. C'est une bascule sur trois plans simultanés.\n\n## 1) La mémoire continue par défaut\n\nAvant : tu commençais chaque chat de zéro. Tu devais re-coller ton CV, tes objectifs, ton style. Pénible.\n\nMaintenant : le modèle se souvient de toi entre conversations. Tu lui dis 'écris comme moi' et il sait ce que ça veut dire. Tu lui dis 'comme la dernière fois' et il s'en souvient vraiment.\n\nImpact concret : ton assistant devient véritablement **personnel**. Plus tu l'utilises, plus il te ressemble.\n\n## 2) Le raisonnement par étapes est natif\n\nLes anciens modèles devinaient une réponse. GPT-5.5 **réfléchit** avant. Il décompose le problème, teste plusieurs approches en interne, vérifie son brouillon, puis répond.\n\nPour des questions simples, c'est instantané. Pour des problèmes complexes (un cas juridique, un calcul d'investissement, un debug), il prend 10-30 secondes et la qualité monte d'un cran.\n\n## 3) Multimodal d'origine\n\nLe modèle ne 'voit' plus l'image après l'avoir lue dans un module séparé. Il **comprend** texte, image, audio en même temps. Tu peux lui montrer un graphique, lui dicter une question vocalement, et il te répond avec une explication écrite + un schéma.\n\n## Ce que ça change pour toi\n\n- **Avant** : tu redonnais le contexte à chaque fois.\n- **Maintenant** : tu travailles avec un assistant qui te connaît.\n- **Avant** : tu acceptais des réponses approximatives sur les questions difficiles.\n- **Maintenant** : tu peux exiger un raisonnement et le voir.\n\n## Le piège à éviter\n\nLa mémoire continue est puissante mais elle stocke des infos sur toi. Vérifie tes paramètres de confidentialité. Choisis ce que le modèle a le droit de retenir.\n\n## Verdict\n\nCe n'est plus un outil pratique. C'est un **partenaire de travail** qui apprend ta manière de penser. Si tu utilisais déjà ChatGPT, ta journée vient de gagner 20-40% de productivité. Si tu hésitais, c'est le moment de t'y mettre.",
     },
    {"id": "n2", "category": "DÉCRYPTAGE", "title": "GPT Image 2.0 : l'image qui obéit enfin au mot près",
     "summary": "Texte net dans l'image, mains à 5 doigts garanties, contrôle de pose précis. La nouvelle référence du visuel IA.",
     "publishedAt": "2026-04-26", "readMinutes": 5, "tag": "OpenAI", "highlight": "2.0", "author": "Rédaction IA Match",
     "intro": "La promesse paraissait impossible : 'génère un visuel publicitaire avec ce slogan exact'. Pendant 3 ans, le texte était flou ou déformé, les mains à 6 doigts, la composition approximative. GPT Image 2.0 lit ton brief comme un humain et exécute. Démonstration en 4 percées concrètes.",
     "body": "## Les 4 avancées concrètes\n\n### Texte parfaitement lisible\nTu peux écrire 'Solde -30% du 1er au 7 mai' et le modèle l'imprime tel quel. Plus de typos générées, plus de texte qui se déforme à mi-image. Pour les agences et les marques, c'est un gain de temps colossal sur les campagnes promo, les affiches événementielles, les bannières web et les visuels réseaux sociaux.\n\n### Mains, mains, mains\nLes IA ont longtemps galéré avec les mains : 5 doigts, anatomie correcte, prise d'objet réaliste. GPT Image 2.0 les rend correctement dans 96% des cas. Tu peux générer des poses naturelles (boire un café, tenir un livre, signer un document) sans avoir à camoufler les mains.\n\n### Contrôle de pose précis\nTu peux donner une silhouette de référence ou un croquis simple. Le modèle respecte la posture exacte, l'orientation du regard, les proportions. Idéal pour la cohérence entre plusieurs visuels d'une même campagne ou les variations d'un même personnage.\n\n### Édition par phrase, sans masque\n'Garde la lumière, change la veste pour un manteau noir long, retire le badge sur le revers.' Plus besoin de découpage, de masques, de calques. La phrase suffit. Le modèle comprend ce qui doit être préservé et ce qui doit changer.\n\n## Ce que ça veut dire pour les créatifs\n\n- **Designers** : 70% du temps de retouche disparaît. Plus de Photoshop pour des corrections mineures. Plus de focus sur la direction artistique.\n- **Marketing** : production de A/B testing visuels en 5 minutes. Les itérations passent de la semaine à l'heure.\n- **Indépendants** : un freelance peut produire un kit complet (3 visuels, 2 formats, 4 variations) en une demi-journée pour le prix d'un simple café.\n\n## Le débat éthique qui revient\n\nPlus c'est précis, plus on peut tromper. Réflexe pro : ajouter des watermarks discrets, garder une trace de génération horodatée, refuser systématiquement la commande si elle imite trop fidèlement une personne réelle non consentante. Les outils sérieux affichent désormais une mention 'image générée par IA' incrustée par défaut.\n\n## Verdict\n\nC'est le premier modèle d'image qui respecte un brief complet sans bricolage. La barrière entre 'idée visuelle' et 'visuel final' vient de tomber d'un cran. La créativité humaine — le brief, le goût, la direction — reprend toute sa valeur. L'exécution n'est plus le goulot d'étranglement.",
     },
    {"id": "n3", "category": "PÉDAGOGIE", "title": "Modèle américain, chinois, européen : comment ils diffèrent vraiment",
     "summary": "Chaque continent a sa philosophie de l'IA. On la décode sans cliché, avec des exemples concrets.",
     "publishedAt": "2026-04-23", "readMinutes": 7, "tag": "Concepts", "author": "Rédaction IA Match",
     "intro": "Tu hésites entre Claude, DeepSeek et Mistral pour ton entreprise ? Au-delà du benchmark, ces modèles incarnent **trois cultures** différentes de l'IA. Voici comment ça change ton expérience.",
     "body": "## Le modèle américain : la performance brute\n\n**Acteurs phares** : OpenAI (GPT), Anthropic (Claude), Google (Gemini), Meta (Llama).\n\n**Philosophie** : pousser la frontière le plus vite possible, monétiser via abonnements premium, capter les créateurs et les développeurs.\n\n**Forces** :\n- Capacités générales très étendues.\n- Écosystème de plugins, d'agents, de marketplaces.\n- Documentation et communauté massives.\n\n**Limites** :\n- Données entraînées majoritairement en anglais.\n- Sensibilité culturelle parfois étrangère aux usages européens.\n- Contraintes RGPD à gérer activement.\n\n## Le modèle chinois : l'efficacité pragmatique\n\n**Acteurs phares** : DeepSeek, Qwen (Alibaba), Kling (Kuaishou), Yi (01.AI).\n\n**Philosophie** : optimisation maximale du rapport coût/performance. Les modèles chinois sont souvent **open-weight** (tu peux les télécharger) et beaucoup moins chers à utiliser.\n\n**Forces** :\n- Coût de tokens jusqu'à 10× inférieur aux modèles US équivalents.\n- Excellents en math, code, raisonnement chiffré.\n- Open-source réel, pas du marketing.\n\n**Limites** :\n- Filtres de contenu différents (sujets politiques sensibles).\n- Moins de support multilingue européen pointu.\n- Hébergement à choisir avec attention pour les données sensibles.\n\n## Le modèle européen : la souveraineté et la confiance\n\n**Acteurs phares** : Mistral (France), Aleph Alpha (Allemagne), Silo AI (Finlande).\n\n**Philosophie** : aligner les modèles sur le cadre RGPD, héberger en Europe, offrir des contrats clairs pour les entreprises et les administrations.\n\n**Forces** :\n- Excellence en langues européennes (français, allemand, italien, espagnol).\n- Conformité RGPD native, hébergement Europe possible.\n- Modèles open-weight (ex. Mistral 8x7B) déployables sur ton infrastructure.\n\n**Limites** :\n- Capacités générales légèrement en retrait sur les tout meilleurs benchmarks américains.\n- Écosystème plus jeune, moins d'apps tierces.\n\n## Comment choisir ?\n\n- **Tu fais du code, du raisonnement complexe, multilingue large** : modèle américain (Claude ou GPT).\n- **Tu as un volume API massif et un budget serré** : modèle chinois (DeepSeek).\n- **Tu travailles avec des données sensibles, en Europe, dans une langue européenne** : modèle européen (Mistral).\n\n## L'angle français\n\nMistral n'est pas 'un Claude moins bon'. C'est un modèle qui parle **un excellent français**, qui peut tourner sur tes serveurs, et qui accepte un contrat français pour tes données. Pour beaucoup d'entreprises et d'administrations, c'est le bon choix par défaut. Le réflexe 'on prend GPT par défaut' n'est plus optimal.\n\n## Verdict\n\nL'IA générative n'est pas neutre. Elle a une géographie, une culture, une économie. Choisir un modèle, c'est choisir une **philosophie de la donnée**. Prends le temps d'aligner ton choix avec tes valeurs et tes contraintes.",
     },
    {"id": "n4", "category": "FRANCE", "title": "Mistral, fierté française : pourquoi ça compte",
     "summary": "Un champion européen qui rivalise avec les géants US. Histoire, position et ce que ça change.",
     "publishedAt": "2026-04-20", "readMinutes": 5, "tag": "Mistral", "author": "Rédaction IA Match",
     "intro": "En 18 mois, une startup parisienne est devenue le 4e acteur mondial de l'IA générative. Mistral n'est pas qu'une fierté symbolique : c'est une preuve concrète que l'Europe peut jouer dans la cour des grands. Voici pourquoi ça compte vraiment, sans cocorico.",
     "body": "## L'histoire en 3 dates\n\n- **Avril 2023** : trois chercheurs (ex-Meta, DeepMind) lancent Mistral à Paris. Pari risqué : créer un modèle européen open-weight qui rivalise avec les géants américains.\n- **Septembre 2023** : sortie de Mistral 7B, modèle open-weight qui bat des modèles 5× plus gros. La communauté découvre un nouveau standard d'efficacité.\n- **Avril 2026** : levée d'1Md€, Le Chat Pro adopté par 40% des administrations françaises et plus de 200 grandes entreprises européennes.\n\n## Pourquoi ça compte vraiment\n\n### 1) Souveraineté technologique\nQuand l'IA devient l'infrastructure invisible de demain (santé, justice, finance, éducation), dépendre uniquement d'acteurs étrangers est un risque stratégique majeur. Mistral nous donne une carte que personne n'avait en Europe depuis trente ans dans le logiciel grand public.\n\n### 2) Excellence en français\nLes modèles US sont entraînés à 90% sur de l'anglais, puis traduisent au runtime. Mistral pondère l'entraînement avec un corpus francophone massif (presse, littérature, code). Résultat : ton français est plus naturel, idiomatique, sans tournures bizarres ni anglicismes parasites. Pour un cabinet d'avocats, un service public ou un éditeur, la différence est nette.\n\n### 3) Open-weight véritable\nMistral 7B, Mixtral 8x7B, Mistral Small 3 : tu peux les télécharger gratuitement, les héberger sur tes propres serveurs, les modifier, les fine-tuner sur tes données. Cette ouverture redonne du pouvoir aux développeurs et aux entreprises qui refusent de dépendre d'une API tierce dont les conditions changent.\n\n## Ce qui rend l'équipe singulière\n\n- **Une obsession produit** : sorties régulières et tenues, sans hype superflue.\n- **Une philosophie 'européenne' assumée** : RGPD by design, contrats français, hébergement Paris.\n- **Une attention au coût opérationnel** : leurs modèles sont taillés pour la production massive, pas seulement pour briller sur les benchmarks académiques.\n\n## Le réflexe à adopter\n\nQuand tu choisis ton IA, ne demande plus 'quel est le meilleur modèle ?' mais 'quel est le meilleur modèle **pour mon contexte** ?'. Si ton contexte est européen, francophone, sensible au respect des données, Mistral est dans ta short-list par défaut. Pour une équipe juridique, comptable ou administrative, c'est même la première option à tester.\n\n## Verdict\n\nIl n'y a pas eu de champion européen du logiciel grand public pendant 30 ans. On en a un sur l'IA, qui est l'infrastructure des 30 prochaines années. Soutenir Mistral en l'utilisant, en en parlant à tes équipes, en l'évaluant face aux options US, c'est concret. Et c'est le moment.",
     },
    {"id": "n5", "category": "MAGIE", "title": "Highfield et la nouvelle vague IA : 5 expériences à essayer ce week-end",
     "summary": "Au-delà de ChatGPT, des outils émerveillants qui montrent ce que l'IA peut être quand on lui donne du jeu.",
     "publishedAt": "2026-04-17", "readMinutes": 5, "tag": "Émerveillement", "author": "Rédaction IA Match",
     "intro": "L'IA, ce n'est pas que des slides en réunion. C'est aussi une boîte à magie créative. On t'a sélectionné 5 expériences gratuites à tester ce week-end. Promis, tu vas sourire.",
     "body": "## 1) Highfield : un univers qui se génère sous tes yeux\n\nHighfield est une expérience interactive où tu écris une scène et l'univers se peuple en temps réel autour de ton avatar. Les personnages parlent avec leur propre voix, l'environnement réagit à tes actions. C'est la première fois qu'un 'jeu' n'a aucun script écrit à l'avance.\n\n**Pourquoi tester** : voir à quoi ressemble un loisir IA-natif.\n\n## 2) Suno : une chanson en 30 secondes\n\nÉcris 'une ballade folk sur Paris en automne, voix grave, guitare acoustique'. Reçois une vraie chanson de 2 minutes. Avec voix. Avec mélodie. Avec instruments.\n\n**Pourquoi tester** : tu vas envoyer la première à ta mère. Tu vas pleurer.\n\n## 3) Krea : design en temps réel\n\nDessine un croquis grossier au stylet. Tape 'rendu photoréaliste, néon, ambiance cyberpunk'. Le design final apparaît instantanément à côté du croquis et se met à jour à chaque trait.\n\n**Pourquoi tester** : tu redécouvres le plaisir du dessin sans avoir à savoir dessiner.\n\n## 4) NotebookLM Audio : ton podcast personnalisé\n\nUploade un PDF (un cours, un article, un livre). NotebookLM génère un podcast audio de 8 minutes avec deux animateurs IA qui discutent du contenu. Tu écoutes en marchant.\n\n**Pourquoi tester** : tu retiens 3× plus en écoutant qu'en lisant.\n\n## 5) Claude Artifacts : code une mini-app en posant une question\n\nDans Claude, demande 'crée-moi un mini-jeu de calcul mental pour mes enfants'. L'app apparaît dans l'interface, jouable, en 30 secondes. Tu peux itérer 'rends-le plus difficile', 'ajoute des sons'.\n\n**Pourquoi tester** : tu sens enfin ce que les développeurs vivent.\n\n## La règle du week-end\n\nNe cherche pas à 'optimiser ton temps'. Ces 5 outils sont là pour t'émerveiller, pas pour ta to-do. Joue. Étonne-toi. Reviens lundi avec une intuition concrète de ce qu'est devenue l'IA en 2026.",
     },
    {"id": "n6", "category": "PÉDAGOGIE", "title": "L'IA évolue à toute vitesse : pourquoi c'est une bonne nouvelle",
     "summary": "Capacités qui doublent tous les 6 mois, prix qui s'effondrent. L'angle positif que personne ne raconte.",
     "publishedAt": "2026-04-13", "readMinutes": 6, "tag": "Concepts", "author": "Rédaction IA Match",
     "intro": "On lit partout 'l'IA va trop vite, c'est inquiétant'. Et si on regardait ce que cette vitesse débloque concrètement pour les gens normaux ?",
     "body": "## La courbe en chiffres\n\n- **2022** : générer une page de texte coûtait 0,02€. Les images étaient floues. Pas de vidéo.\n- **2024** : 0,002€ la page. Images photoréalistes. Premières vidéos courtes.\n- **2026** : 0,0002€ la page. Images parfaites. Vidéos cinématographiques. Voix indiscernables d'un humain.\n\nDivisé par 100 en 4 ans. Divisé par 1000 dans 4 ans probablement.\n\n## Ce que ça libère\n\n### 1) L'éducation devient gratuite\nN'importe quel élève peut avoir un tuteur personnel patient, disponible 24/7, dans sa langue, à son niveau. Hier ça coûtait 50€/h. Demain c'est inclus dans un abonnement à 10€/mois.\n\n### 2) La médecine de campagne se démocratise\nUn médecin généraliste à 200km du CHU peut soumettre un cas complexe à un assistant IA spécialisé en cardiologie ou en oncologie. Le diagnostic différentiel devient bien plus juste.\n\n### 3) Les indépendants explosent\nUn freelance graphiste peut produire 5× plus de variantes pour ses clients. Un copywriter peut couvrir 5× plus de marques. La compétence reste humaine, l'exécution est démultipliée.\n\n### 4) Les langues fusionnent\nUn entrepreneur français peut négocier en mandarin avec un fournisseur, en temps réel, avec un anglais nuancé pour son investisseur américain. La barrière linguistique disparaît silencieusement.\n\n### 5) L'accès à la culture\nUn enfant peut faire un projet d'histoire en interrogeant un assistant qui connaît tout, dans son contexte, dans sa langue. Le savoir n'est plus payant.\n\n## Ce que ça implique pour toi\n\nTu n'es pas en retard. Tu es exactement à l'heure. La vraie compétence en 2026, ce n'est pas 'savoir prompter' (tout le monde sait taper du texte). C'est :\n\n1. **Savoir poser la bonne question** (compétence éternelle).\n2. **Savoir vérifier la réponse** (esprit critique).\n3. **Savoir choisir l'IA adaptée** (ce qu'IA Match t'aide à faire).\n4. **Savoir mettre la main à la pâte** quand l'IA se trompe (ton expertise reste centrale).\n\n## Verdict\n\nLa vitesse de l'IA n'est pas une menace. C'est un escalier qui monte vers un plateau plus large, où plus de gens peuvent faire plus de choses, dans plus de langues, à un coût ridiculement bas. Le travail humain ne disparaît pas : il devient **plus créatif et moins répétitif**.",
     },
    {"id": "n7", "category": "DÉCRYPTAGE", "title": "Claude 4.5 Sonnet : le maître du long format",
     "summary": "Anthropic frappe fort avec un Claude qui digère 1 million de tokens et raisonne sans s'épuiser. Pourquoi les pros l'adorent.",
     "publishedAt": "2026-04-09", "readMinutes": 6, "tag": "Anthropic", "highlight": "4.5", "author": "Rédaction IA Match",
     "intro": "Anthropic vient de publier Claude 4.5 Sonnet. Sur le papier, c'est une mise à jour. Dans la pratique, c'est le modèle préféré des avocats, des analystes et des écrivains. Voici pourquoi.",
     "body": "## La signature Anthropic\n\nAnthropic a toujours visé une niche : la **qualité d'écriture** et le **raisonnement nuancé**. Pendant qu'OpenAI courait après le multimodal, Claude affinait sa plume.\n\n## Trois forces qui changent la donne\n\n### 1) Fenêtre 1 million de tokens\nTu peux coller un livre entier (300 pages) et discuter avec lui. Tu peux passer un dossier juridique de 80 documents et obtenir une synthèse honnête. La capacité d'absorption est juste **5×** supérieure à GPT-5.5.\n\n### 2) Artefacts version 2\nQuand tu demandes du code ou un mini-outil, Claude crée un 'artefact' interactif sur le côté. Tu peux itérer dessus en parlant, sans copier-coller. C'est devenu l'outil n°1 des designers UX et des product managers.\n\n### 3) Refus argumenté\nSur les sujets sensibles, Claude ne refuse pas brutalement : il explique son raisonnement. C'est inestimable pour les équipes juridiques et conformité qui doivent comprendre pourquoi un modèle dit non.\n\n## Quand choisir Claude plutôt que ChatGPT\n\n- **Audit juridique** : long doc, citations à conserver intactes.\n- **Écriture longue** : un essai de 5000 mots cohérent, pas haché.\n- **Code complexe** : refactoring multi-fichiers avec explication.\n- **Conversations sensibles** : RH, médical, conformité.\n\n## Le piège\n\nClaude est plus lent que les modèles concurrents (200-300ms par token). Pour un assistant temps réel grand public, GPT ou Gemini conviennent mieux. Pour un travail de fond, Claude gagne presque toujours.\n\n## Verdict\n\nClaude 4.5 Sonnet est le **outil de bureau** du travailleur intellectuel sérieux. Si tu écris pour vivre, si tu raisonnes pour décider, abonne-toi. C'est le meilleur 20€/mois que tu dépenseras cette année.",
     },
    {"id": "n8", "category": "DÉCRYPTAGE", "title": "Gemini 3 Ultra : Google reprend la main sur le multimodal",
     "summary": "Vidéo, audio, code, image : Gemini 3 traite tout en même temps. Et c'est gratuit pour la plupart des usages.",
     "publishedAt": "2026-04-04", "readMinutes": 5, "tag": "Google", "highlight": "3", "author": "Rédaction IA Match",
     "intro": "Pendant deux ans, Google a couru après OpenAI. Avec Gemini 3 Ultra, le rapport de force change : pour la première fois, Google offre un modèle plus complet que ses concurrents, et largement gratuit.",
     "body": "## Le multimodal vraiment natif\n\nGemini 3 ne 'lit' pas une vidéo après l'avoir convertie en texte. Il la **regarde** réellement, frame par frame. Tu peux uploader 1 heure de vidéo et lui demander 'à quel moment précis le client a hésité ?'. Il pointe la timestamp à la seconde près.\n\n## Quatre cas d'usage qui surprennent\n\n### 1) Analyser des screenshots de tableaux complexes\nFini la galère d'extraction OCR : tu uploads, tu poses ta question. Précision proche de 100%.\n\n### 2) Sous-titrer un podcast en 8 langues\nUpload audio + 'sous-titre en français, anglais, espagnol, allemand, italien, japonais, coréen, mandarin'. Tu reçois 8 fichiers prêts à l'emploi.\n\n### 3) Coder une app à partir d'un Figma\nUpload du PNG du design, 'code-moi cette page en React Native'. Le résultat est étonnamment proche.\n\n### 4) Générer un script vidéo à partir d'une conférence\nUpload de la vidéo, 'écris un fil Twitter et un article Medium à partir de cette présentation'. Cohérence parfaite, citations exactes.\n\n## Le tarif imbattable\n\nLa plupart de ces usages sont **gratuits** dans l'app Gemini. Pour les développeurs, l'API est environ 60% moins chère que GPT à qualité équivalente. Google joue clairement la carte du volume.\n\n## La limite\n\nGemini reste légèrement moins fort que Claude sur l'écriture longue et le raisonnement profond. Pour un usage 'écriveur', Claude gagne. Pour un usage 'multimodal' (vidéo, image, audio simultanés), Gemini est imbattable.\n\n## Verdict\n\nSi tu travailles avec du contenu visuel (vidéo, image, screenshot, PDF) tous les jours, Gemini 3 Ultra est ton nouveau couteau suisse. Et le tarif gratuit fait de lui un excellent point d'entrée si tu débutes en IA.",
     },
    {"id": "n9", "category": "FRANCE", "title": "Mistral Le Chat Pro : le pari souverain s'amplifie",
     "summary": "Le Chat Pro version 2026 ajoute un agent autonome, le mode entreprise et l'hébergement Paris/Francfort. Décryptage.",
     "publishedAt": "2026-03-30", "readMinutes": 6, "tag": "Mistral", "author": "Rédaction IA Match",
     "intro": "Quand Mistral a lancé Le Chat en 2024, c'était un produit minimaliste. Deux ans plus tard, Le Chat Pro 2026 rivalise sérieusement avec ChatGPT Plus, avec un avantage décisif : il vit en France.",
     "body": "## Trois nouveautés qui changent tout pour les entreprises\n\n### 1) Mistral Agent intégré\nLe Chat Pro embarque désormais un agent autonome. Tu lui dis 'compile-moi un rapport de veille sur les tendances cyber en Europe'. Il fait sa recherche, croise les sources, te livre un rapport sourcé en 4 minutes. L'agent peut aussi se connecter à ton Outlook, ton Drive, ton CRM (avec les bons droits).\n\n### 2) Hébergement Paris ou Francfort, au choix\nPour les administrations et les entreprises sous RGPD strict, Mistral propose un hébergement 100% européen avec contrat français. Aucun transit par les États-Unis. C'est juridiquement un argument décisif pour les RFP du secteur public.\n\n### 3) Mode 'Confidentialité maximale'\nTu peux activer un mode où aucune de tes conversations n'est utilisée pour entraîner les futurs modèles, même de manière anonymisée. Garantie contractuelle, pas juste paramètre coché.\n\n## La preuve par les chiffres\n\n- **40%** : part de Mistral dans les appels d'offres IA des administrations françaises (avril 2026).\n- **60%** : croissance trimestrielle de Le Chat Pro.\n- **9** : nouveaux pays européens couverts officiellement.\n- **<200ms** : latence moyenne en France métropolitaine.\n\n## Le réflexe à adopter\n\nSi ton entreprise est française ou européenne, **mets Mistral dans ta short-list par défaut**. Ce n'est plus un choix patriotique : c'est un choix opérationnel. Pour le code, l'écriture en français, la conformité RGPD, le rapport qualité/prix, Mistral est désormais à parité ou supérieur sur de nombreux usages.\n\n## Verdict\n\nLe Chat Pro 2026 confirme la trajectoire : Mistral est devenu un acteur sérieux. Tu peux y aller les yeux fermés pour 80% des usages bureau, et tu fais un choix industriellement responsable pour ton entreprise.",
     },
    {"id": "n10", "category": "MAGIE", "title": "Grok 4 et DeepSeek R2 : les outsiders qui secouent le marché",
     "summary": "Un Grok temps réel branché sur X, un DeepSeek 10x moins cher : les modèles 'moins connus' qui mériteraient ta curiosité.",
     "publishedAt": "2026-03-25", "readMinutes": 6, "tag": "Émerveillement", "author": "Rédaction IA Match",
     "intro": "On parle toujours d'OpenAI, Anthropic, Google, Mistral. Mais deux modèles secouent vraiment le marché en ce moment : Grok 4 (xAI/Elon Musk) et DeepSeek R2 (Chine). Voici pourquoi ça vaut le coup d'y jeter un œil.",
     "body": "## Grok 4 : le modèle qui voit l'actualité en direct\n\n### La force unique\nGrok 4 a un accès **temps réel** à l'ensemble du flux X (ex-Twitter). Tu lui poses une question d'actualité brûlante, il a déjà vu les 200 derniers tweets sur le sujet. Aucun autre modèle ne peut faire ça aussi vite.\n\n### Cas d'usage qui marchent\n- Veille concurrentielle 'que disent les utilisateurs de X produit ?'\n- Réactivité éditoriale sur l'actu (pour rédacteurs et community managers).\n- Détection de signaux faibles avant qu'ils explosent.\n\n### La limite\n- Plus libre dans ses réponses, parfois trop. À utiliser avec recul.\n- Excellent en anglais, correct en français.\n- Inclus dans Premium X (~16€/mois).\n\n## DeepSeek R2 : la révolution coût/performance\n\n### La force unique\nDeepSeek R2 atteint le niveau de raisonnement de GPT-5 sur les maths et le code, mais coûte **10× moins cher** par token. Et il est **open-weight** : tu peux le télécharger et l'héberger toi-même gratuitement.\n\n### Cas d'usage qui marchent\n- Volume API massif (millions de prompts/mois).\n- Math complexes, dérivations, optimisations.\n- Code review automatisé sur de gros monorepos.\n- Self-hosting pour les boîtes qui veulent zéro cloud.\n\n### La limite\n- Filtres chinois sur certains sujets politiques.\n- Excellent en anglais et chinois, correct en français.\n- Documentation moins fournie que ses concurrents US.\n\n## Pourquoi tester ces deux outsiders\n\nLa diversité des modèles n'est pas seulement un confort de choix. C'est un **garde-fou stratégique**. Si tu construis une app sur GPT seul, tu es à la merci d'OpenAI. Si tu mixes 2-3 modèles selon les besoins, tu deviens résilient et tu optimises tes coûts.\n\n## Le réflexe à adopter\n\nUne fois par mois, prends une heure pour tester un modèle 'outsider'. Tu ne perdras rien et tu trouveras peut-être ta nouvelle pépite cachée.\n\n## Verdict\n\nLes leaders ne sont pas seuls. Grok ouvre une fenêtre temps réel unique. DeepSeek casse les codes économiques du marché. Garde l'œil ouvert : la prochaine grande surprise viendra probablement d'un modèle dont tu n'as pas encore entendu parler.",
     },
]


# ----- ACADEMY — 10 fondamentaux pédagogiques -----
LESSONS = [
    {"id": "l1", "order": 1, "level": "DÉBUTANT", "minutes": 6, "title": "C'est quoi, un 'modèle d'IA' ?",
     "intro": "Avant de prompter, comprendre ce qu'on a en face. Métaphore simple : un cuisinier amnésique mais hyper cultivé.",
     "body": "Un modèle d'IA est un programme entraîné sur d'énormes quantités de texte. Il a 'lu' des millions de livres, articles et conversations, mais il ne **se souvient** de rien après chaque conversation (sauf si on active la mémoire). Il connaît des recettes, mais il les invente sur le moment, à chaque fois.",
     "framework": "MODÈLE = CULTURE + INVENTION SUR L'INSTANT",
     "steps": [
         "Le modèle a tout 'lu' jusqu'à une date (cutoff).",
         "Il prédit le mot suivant le plus probable, pas la 'vérité'.",
         "Il oublie tout entre conversations (sauf mémoire).",
         "Plus tu lui donnes de contexte, plus il devine juste.",
     ],
     "before": "Le modèle sait tout, donc il a forcément raison.",
     "after": "Le modèle est cultivé mais devine sur le moment. Je vérifie chiffres, citations, dates."},
    {"id": "l2", "order": 2, "level": "DÉBUTANT", "minutes": 6, "title": "Tokens, contexte et fenêtre : la mécanique invisible",
     "intro": "Un token = un bout de mot. Le modèle ne 'voit' pas tes phrases, il voit des tokens. Comprendre ça évite des erreurs coûteuses.",
     "body": "Un mot français vaut ~1.5 tokens en moyenne. Un modèle a une 'fenêtre de contexte' (ex. 200 000 tokens) : c'est la quantité de texte qu'il peut traiter d'un coup. Au-delà, il oublie le début. La fenêtre est partagée entre ta question, le contexte que tu donnes, et sa réponse.",
     "framework": "FENÊTRE = TON BRIEF + SES RÉPONSES + LE FIL",
     "steps": [
         "Estime ton volume de texte en tokens (~1.5×nombre de mots).",
         "Choisis un modèle avec une fenêtre adaptée.",
         "Si tu approches la limite, condense ou redémarre.",
         "Le contexte coûte des tokens : sois utile, pas bavard.",
     ],
     "before": "Je colle mes 100 pages, le modèle s'en occupe.",
     "after": "Je résume mes 100 pages en 5 pages clés, je colle ces 5 pages."},
    {"id": "l3", "order": 3, "level": "DÉBUTANT", "minutes": 7, "title": "Hallucinations : quand l'IA invente avec aplomb",
     "intro": "Les modèles inventent des chiffres et des sources qui paraissent vrais. Apprendre à les détecter, c'est se protéger.",
     "body": "Une 'hallucination', c'est une réponse fausse formulée avec assurance. Le modèle ne ment pas exprès : il complète la phrase la plus probable, même quand il n'a pas l'info. Les hallucinations frappent surtout : citations, chiffres récents, références juridiques, données personnelles.",
     "framework": "VÉRIFIE-MOI ÇA — 4 SIGNAUX D'ALERTE",
     "steps": [
         "Citations précises (livre + page) : à vérifier.",
         "Chiffres datés (-2026, ce mois, etc.) : à vérifier.",
         "Noms propres rares ou très spécialisés : à vérifier.",
         "Le modèle dit 'je n'ai pas accès à internet' mais te répond quand même : très suspect.",
     ],
     "before": "ChatGPT m'a sorti la citation, je colle telle quelle.",
     "after": "Je copie la citation dans Google. Si elle n'existe pas, je l'enlève."},
    {"id": "l4", "order": 4, "level": "DÉBUTANT", "minutes": 7, "title": "Comprendre ce qu'un modèle attend : le mini-brief",
     "intro": "Un bon prompt n'est pas une phrase magique. C'est un mini-brief comme tu en donnerais à un nouveau stagiaire.",
     "body": "Le modèle doit savoir ce qu'il doit produire, pour qui, avec quelles contraintes et sous quel format. Plus la sortie est importante, plus le brief doit être précis sur les critères de réussite.",
     "framework": "OBJECTIF · CONTEXTE · CONTRAINTES · FORMAT",
     "steps": [
         "Formule l'objectif en une phrase.",
         "Ajoute le contexte utile et seulement utile.",
         "Liste les contraintes non négociables.",
         "Décris le format final attendu.",
         "Ajoute 2 critères de qualité.",
     ],
     "before": "Fais-moi un bon texte sur mon projet.",
     "after": "Rédige une présentation de 120 mots pour mon app IA Match. Audience : entrepreneurs non techniques. Ton : premium, clair, direct. Format : 1 paragraphe + 3 puces."},
    {"id": "l5", "order": 5, "level": "DÉBUTANT", "minutes": 8, "title": "Choisir le bon modèle : 4 questions à se poser",
     "intro": "Pas besoin du modèle 'le plus puissant'. Il faut le **bon** pour ta tâche.",
     "body": "Il y a quatre axes : capacité, vitesse, prix, langue. Tu ne peux pas tout maximiser en même temps. Le bon réflexe : commencer par la question 'à quel point je tolère une erreur ?' et descendre.",
     "framework": "CAPACITÉ · VITESSE · PRIX · LANGUE",
     "steps": [
         "Qualité critique ? Modèle haut de gamme (Claude, GPT-5).",
         "Volume massif ? Modèle économique (Haiku, Mistral, DeepSeek).",
         "Réponse instantanée ? Modèle rapide (Gemini Flash, Mistral Small).",
         "Langue européenne sensible ? Mistral.",
     ],
     "before": "Je prends GPT pour tout, c'est connu.",
     "after": "Pour cette tâche : Mistral suffit, économique et bon en français."},
    {"id": "l6", "order": 6, "level": "INTERMÉDIAIRE", "minutes": 8, "title": "La méthode des 7 blocs",
     "intro": "Une structure mémorable pour ne plus oublier l'essentiel.",
     "body": "Rôle, Objectif, Audience, Contexte, Contraintes, Format, Critères. Sept blocs qui couvrent 95% des situations. Tu peux en sauter, jamais les inverser.",
     "framework": "RÔLE · OBJECTIF · AUDIENCE · CONTEXTE · CONTRAINTES · FORMAT · CRITÈRES",
     "steps": [
         "Donne un rôle précis ('coach carrière senior').",
         "Définis l'objectif unique de la sortie.",
         "Décris l'audience finale.",
         "Donne le contexte nécessaire.",
         "Liste contraintes hard et soft.",
         "Impose un format.",
         "Ajoute 2-3 critères de qualité.",
     ],
     "before": "Écris une lettre de motivation.",
     "after": "Tu es coach carrière senior. Lettre de motivation 200 mots. Audience : DRH cabinet conseil. Contexte : poste consultant junior. Ton sobre. Format : 3 paragraphes. Critère : prouve la valeur."},
    {"id": "l7", "order": 7, "level": "INTERMÉDIAIRE", "minutes": 8, "title": "Few-shot : montrer plutôt que décrire",
     "intro": "Le 'few-shot prompting' est la cheat-code la plus sous-exploitée.",
     "body": "Donne 2-3 exemples concrets de la sortie attendue avant ta vraie demande. Le modèle imite mieux qu'il ne suit une description.",
     "framework": "FEW-SHOT (2-3 EXEMPLES + TÂCHE)",
     "steps": [
         "Choisis 2-3 exemples représentatifs.",
         "Format identique pour chaque exemple.",
         "Sépare exemples et vraie demande.",
         "Demande la sortie au même format.",
     ],
     "before": "Écris-moi des slogans pour ma marque.",
     "after": "Voici 3 slogans que j'aime : 'Think different.', 'Just do it.', 'Hello again.'. Crée 5 slogans dans le même esprit pour IA Match."},
    {"id": "l8", "order": 8, "level": "INTERMÉDIAIRE", "minutes": 7, "title": "Itérer sans repartir de zéro",
     "intro": "L'art de raffiner sans tout casser.",
     "body": "Au lieu de relancer, demande des modifications ciblées. Le modèle garde le reste du contexte.",
     "framework": "GARDER · CHANGER · EXCLURE",
     "steps": [
         "Liste ce qui doit rester.",
         "Liste ce qui doit changer (avec direction).",
         "Liste ce qui ne doit jamais apparaître.",
         "Demande la même structure de sortie.",
     ],
     "before": "Refais-le.",
     "after": "Garde : structure 3 paragraphes, ton sobre. Change : 2e paragraphe plus concret avec un chiffre. Exclus : adverbes en -ment."},
    {"id": "l9", "order": 9, "level": "AVANCÉ", "minutes": 10, "title": "Sortie structurée : JSON, tableau, checklist",
     "intro": "La sortie structurée déverrouille l'automatisation.",
     "body": "Spécifie un schéma exact, donne un exemple, demande une seule chose : 'réponds uniquement avec ce JSON valide'.",
     "framework": "SCHEMA-FIRST",
     "steps": [
         "Définis le schéma précis (champs, types).",
         "Donne 1 exemple complet.",
         "Impose 'aucun texte avant ou après'.",
         "Ajoute 'sors un JSON valide' explicitement.",
     ],
     "before": "Donne-moi 3 idées principales.",
     "after": "Réponds UNIQUEMENT avec ce JSON valide : {\"ideas\":[{\"title\":string,\"summary\":string,\"impact\":1-5}]}. 3 idées pour le pitch IA Match."},
    {"id": "l10", "order": 10, "level": "AVANCÉ", "minutes": 9, "title": "Chain-of-thought : faire raisonner avant de répondre",
     "intro": "Pour les questions complexes, demande au modèle de **réfléchir à voix haute** avant de répondre.",
     "body": "Sur une question difficile (math, juridique, code), un modèle devine si tu lui demandes une réponse directe. En lui demandant un raisonnement étape par étape, la qualité monte d'un cran. Avec les modèles 'reasoning' (GPT-5, Claude), c'est natif.",
     "framework": "RAISONNE PUIS RÉPONDS",
     "steps": [
         "Décris le problème complètement.",
         "Demande : 'raisonne étape par étape avant de répondre'.",
         "Demande la réponse finale en dernier.",
         "Vérifie chaque étape, pas juste la conclusion.",
     ],
     "before": "Quel est le bon investissement ?",
     "after": "Voici les 3 options chiffrées. Raisonne étape par étape : risques, rendements, fiscalité, horizon. Termine par une recommandation et son niveau de confiance."},
]


# ----- ACADEMY — 15 templates triés par niveau (5/5/5) -----
TEMPLATES = [
    # 5 BEGINNER
    {"id": "t1", "level": "BEGINNER", "title": "Optimiser un CV pour un poste précis",
     "body": "Tu es recruteur senior dans {sector}. Améliore mon CV pour le poste de {target_role}. Mon expérience : {experience_level}. Compétences clés : {skills}. Donne : 1) diagnostic en 5 points, 2) version améliorée des 3 expériences les plus pertinentes, 3) liste de mots-clés ATS à intégrer, 4) 3 questions probables d'entretien et comment y répondre.",
     "variables": ["sector", "target_role", "experience_level", "skills"]},
    {"id": "t2", "level": "BEGINNER", "title": "Lettre de motivation honnête et impactante",
     "body": "Tu es coach carrière. Rédige une lettre de motivation pour le poste {target_role} chez {company}. Mon profil : {profile}. Ce qui m'attire vraiment : {attraction}. Ce que j'apporte concrètement : {value}. Ton : sobre, sans superlatifs. Format : 3 paragraphes de 4 lignes chacun. Termine par une phrase d'ouverture pour l'entretien.",
     "variables": ["target_role", "company", "profile", "attraction", "value"]},
    {"id": "t3", "level": "BEGINNER", "title": "Email pro qui ne fait pas perdre de temps",
     "body": "Rédige un email pour {recipient} dans le but de {goal}. Contexte : {context}. Ton : {tone}. Contrainte : maximum 5 lignes corps + objet sous 8 mots. Termine par une question fermée à laquelle on peut répondre par oui ou non.",
     "variables": ["recipient", "goal", "context", "tone"]},
    {"id": "t4", "level": "BEGINNER", "title": "Résumé clair d'un long document",
     "body": "Résume le document suivant pour {audience} dans l'objectif de {decision_or_goal}. Format : 1) résumé exécutif en 8 lignes, 2) 5 points clés, 3) risques identifiés, 4) opportunités, 5) 3 questions à poser au document. Signale toute information manquante.\n\nDocument : {document_text}",
     "variables": ["audience", "decision_or_goal", "document_text"]},
    {"id": "t5", "level": "BEGINNER", "title": "Plan de cours pour apprendre un sujet",
     "body": "Tu es professeur expérimenté. Construis un plan de cours pour apprendre {topic} en {duration}. Niveau de départ : {level}. Objectif : {goal}. Donne : 1) 5 étapes avec durée, 2) 1 ressource clé par étape (livre, vidéo ou exercice), 3) 1 mini-projet pratique pour valider l'apprentissage.",
     "variables": ["topic", "duration", "level", "goal"]},

    # 5 INTERMEDIATE
    {"id": "t6", "level": "INTERMEDIATE", "title": "Recherche web sourcée et comparée",
     "body": "Recherche {topic} sur la période {timeframe}. Priorise les sources : {source_policy}. Compare les informations selon {criteria}. Livrables : 1) résumé synthétique, 2) tableau comparatif, 3) liste des sources avec lien et niveau de fiabilité, 4) désaccords entre sources, 5) niveau de confiance par information clé.",
     "variables": ["topic", "timeframe", "source_policy", "criteria"]},
    {"id": "t7", "level": "INTERMEDIATE", "title": "Déboguer une erreur de code",
     "body": "Contexte projet : {project_context}. Stack : {stack}. Fichiers concernés : {files}. Erreur exacte : {error_message}. Comportement attendu : {expected_behavior}. Contraintes : ne modifie pas l'architecture. Donne : 1) cause probable et pourquoi, 2) correctif minimal en code, 3) tests à lancer pour vérifier, 4) 2 cas limites à surveiller.",
     "variables": ["project_context", "stack", "files", "error_message", "expected_behavior"]},
    {"id": "t8", "level": "INTERMEDIATE", "title": "Pitch deck investisseurs en 12 slides",
     "body": "Rédige un pitch deck pour {startup}. Stade : {stage}. Marché total adressable : {market_size}. Problème résolu : {problem}. Solution : {solution}. Traction : {traction}. Équipe : {team}. Demande : {ask}. Format : 12 slides max, chacune avec un titre + 3 puces + 1 chiffre clé. Ajoute la slide 'risques et mitigations'.",
     "variables": ["startup", "stage", "market_size", "problem", "solution", "traction", "team", "ask"]},
    {"id": "t9", "level": "INTERMEDIATE", "title": "Visuel publicitaire premium",
     "body": "Génère un visuel publicitaire pour {product}. Sujet principal : {subject}. Décor : {setting}. Style : {style}. Composition : {composition}. Lighting : {lighting}. Palette : {palette}. Texte exact à imprimer : {text}. Format : {format}. À éviter : {negative}. Donne 3 variantes de prompts détaillées.",
     "variables": ["product", "subject", "setting", "style", "composition", "lighting", "palette", "text", "format", "negative"]},
    {"id": "t10", "level": "INTERMEDIATE", "title": "Compte-rendu de réunion structuré",
     "body": "À partir des notes brutes ci-dessous, produis un compte-rendu professionnel. Audience : {audience}. Format : 1) contexte en 3 lignes, 2) décisions prises (avec décideur), 3) actions (qui fait quoi pour quand), 4) points en suspens, 5) date prochaine réunion. Sois factuel, pas de filler.\n\nNotes : {notes}",
     "variables": ["audience", "notes"]},

    # 5 ADVANCED
    {"id": "t11", "level": "ADVANCED", "title": "Cahier des charges MVP complet",
     "body": "Construis un cahier des charges MVP pour {app_name}. Objectif utilisateur : {user_goal}. Personas : {personas}. Pages requises : {pages}. Fonctionnalités MVP : {features}. Modèle de données : {data_model}. Design system : {design}. Contraintes techniques : {tech_constraints}. Livrables attendus : architecture, schéma de données, plan de tests, plan de déploiement, KPIs de succès, risques.",
     "variables": ["app_name", "user_goal", "personas", "pages", "features", "data_model", "design", "tech_constraints"]},
    {"id": "t12", "level": "ADVANCED", "title": "Plan éditorial trimestriel B2B",
     "body": "Tu es Head of Content B2B chez {company}. Crée un plan éditorial sur {quarter}. Audiences segmentées : {audiences}. Objectifs business : {objectives}. Canaux : {channels}. Cadence : {cadence}. Livrables : 1) 3 thèmes piliers avec angle unique, 2) calendrier hebdo détaillé, 3) 12 idées d'articles avec angle + CTA, 4) KPIs trackés, 5) playbook de distribution.",
     "variables": ["company", "quarter", "audiences", "objectives", "channels", "cadence"]},
    {"id": "t13", "level": "ADVANCED", "title": "Audit stratégique d'un produit",
     "body": "Audit du produit {product_name}. Marché : {market}. Concurrents directs : {competitors}. Métriques actuelles : {metrics}. Hypothèses fondatrices : {hypotheses}. Donne : 1) SWOT honnête, 2) jobs-to-be-done par persona, 3) écart entre promesse et exécution, 4) 3 angles stratégiques d'amélioration avec priorisation ICE, 5) risques à 12 mois.",
     "variables": ["product_name", "market", "competitors", "metrics", "hypotheses"]},
    {"id": "t14", "level": "ADVANCED", "title": "Architecture d'un agent autonome",
     "body": "Conçois l'architecture d'un agent autonome qui réalise {goal}. Outils disponibles : {tools}. Contraintes : budget max {budget}, max {max_steps} étapes, niveau d'autonomie {autonomy}. Livrables : 1) plan d'exécution étape par étape, 2) critères d'arrêt et d'escalade humaine, 3) journal de décisions à produire, 4) tests d'acceptation, 5) plan de déploiement progressif.",
     "variables": ["goal", "tools", "budget", "max_steps", "autonomy"]},
    {"id": "t15", "level": "ADVANCED", "title": "Stratégie de migration vers l'IA",
     "body": "Construis un plan de migration IA pour {company} (taille {size}, secteur {sector}). État actuel : {current_state}. Objectifs business 12 mois : {goals}. Contraintes RGPD : {gdpr}. Budget : {budget}. Livrables : 1) cartographie des 5 cas d'usage prioritaires, 2) recommandation de modèles (US/CN/EU) par cas, 3) plan d'adoption par équipe, 4) gouvernance et risques, 5) KPIs et calendrier 90 jours.",
     "variables": ["company", "size", "sector", "current_state", "goals", "gdpr", "budget"]},
]


# ----- LIENS UTILES — 100% sources françaises vérifiées -----
RESOURCES = [
    {"id": "r1", "category": "YOUTUBE", "title": "Underscore_", "author": "Micode",
     "summary": "Tech et IA expliquées avec rigueur en français. Format long, pédagogique, sans hype.",
     "url": "https://www.youtube.com/@Underscore_"},
    {"id": "r2", "category": "YOUTUBE", "title": "Defend Intelligence", "author": "Anis Ayari",
     "summary": "Décryptages IA en français par un data scientist. Pédagogie pour curieux et pros.",
     "url": "https://www.youtube.com/@DefendIntelligence-tech"},
    {"id": "r3", "category": "YOUTUBE", "title": "Le Vortex", "author": "Le Vortex",
     "summary": "Émission tech française qui couvre régulièrement les nouveautés IA.",
     "url": "https://www.youtube.com/@LeVortex"},
    {"id": "r4", "category": "YOUTUBE", "title": "Science4All", "author": "Lê Nguyên Hoang",
     "summary": "Vulgarisation scientifique de qualité avec une série solide sur l'IA et le ML.",
     "url": "https://www.youtube.com/@le_science4all"},
    {"id": "r5", "category": "YOUTUBE", "title": "Cocadmin", "author": "Cocadmin",
     "summary": "Tech et culture web en français, avec analyses régulières des outils IA.",
     "url": "https://www.youtube.com/@cocadmin"},
    {"id": "r6", "category": "BLOG", "title": "Korben.info", "author": "Korben",
     "summary": "Référence française tech depuis 20 ans. Couverture quotidienne des outils IA.",
     "url": "https://korben.info/category/intelligence-artificielle"},
    {"id": "r7", "category": "BLOG", "title": "Numerama", "author": "Rédaction Numerama",
     "summary": "Média tech français de référence. Articles pédagogiques et analyses sur l'IA.",
     "url": "https://www.numerama.com/tech/intelligence-artificielle/"},
    {"id": "r8", "category": "BLOG", "title": "ActuIA", "author": "Rédaction ActuIA",
     "summary": "Magazine 100% IA en français. Actualité, dossiers, interviews d'experts français.",
     "url": "https://www.actuia.com/"},
    {"id": "r9", "category": "BLOG", "title": "Frandroid — IA", "author": "Rédaction Frandroid",
     "summary": "Tests d'outils IA grand public, analyses comparatives en français.",
     "url": "https://www.frandroid.com/tag/intelligence-artificielle"},
    {"id": "r10", "category": "BLOG", "title": "Siècle Digital — IA", "author": "Rédaction Siècle Digital",
     "summary": "Veille business et stratégie autour de l'IA, en français, ton accessible.",
     "url": "https://siecledigital.fr/intelligence-artificielle/"},
    {"id": "r11", "category": "PODCAST", "title": "Trench Tech", "author": "Mick Levy",
     "summary": "Podcast français exigeant sur l'éthique et la stratégie de l'IA.",
     "url": "https://trench-tech.fr/"},
    {"id": "r12", "category": "PODCAST", "title": "L'IA aujourd'hui", "author": "Le Monde",
     "summary": "Quotidien audio du Monde sur l'actualité IA, en français, format court.",
     "url": "https://www.lemonde.fr/podcasts/"},
    {"id": "r13", "category": "PODCAST", "title": "Génération Do It Yourself", "author": "Matthieu Stéfani",
     "summary": "Interviews longues d'entrepreneurs français, plusieurs épisodes consacrés à l'IA.",
     "url": "https://www.gdiy.fr/"},
    {"id": "r14", "category": "NEWSLETTER", "title": "Le Tech Report", "author": "Stéphane Tissot",
     "summary": "Newsletter française hebdo sur la tech et l'IA, ton accessible et structuré.",
     "url": "https://letechreport.substack.com/"},
    {"id": "r15", "category": "NEWSLETTER", "title": "Olivier Ezratty — Opinions Libres", "author": "Olivier Ezratty",
     "summary": "Analyses approfondies en français par un expert reconnu de l'écosystème IA français.",
     "url": "https://www.oezratty.net/wordpress/"},
    {"id": "r16", "category": "OUTIL", "title": "Hugging Face France", "author": "Hugging Face",
     "summary": "La plateforme open-source mondiale, avec une forte communauté française.",
     "url": "https://huggingface.co"},
    {"id": "r17", "category": "YOUTUBE", "title": "Shubham Sharma", "author": "Shubham Sharma",
     "summary": "Chaîne tech avec démonstrations pratiques d'outils IA, tutos no-code et workflows IA appliqués.",
     "url": "https://www.youtube.com/@Shubham_Sharma"},
    {"id": "r18", "category": "YOUTUBE", "title": "Renaud Dekode", "author": "Renaud Dekode",
     "summary": "Décryptage clair des outils IA et tutos en français : prompt engineering, automatisations et productivité.",
     "url": "https://www.youtube.com/@RenaudDekode"},
]
