"""Pedagogical data for IA Match — all in French, beginner-friendly.

Covers:
- GLOSSARY : 30 IA jargon terms explained
- FAQ : common beginner questions with honest answers
- USE_CASES : real-life problems → top 3 IAs
- PERSONAS : audience-based tool curations
- PRIVACY_OVERRIDES : transparent privacy/sovereignty score per top tool
- BEFORE_AFTER : example prompts and outputs for top tools
"""

GLOSSARY = [
    {"term": "Prompt", "emoji": "💬", "short": "Le texte que tu envoies à une IA pour lui donner ta consigne.",
     "long": "Plus ton prompt est précis (rôle, objectif, format, contraintes), meilleure sera la réponse.",
     "example": "« Tu es un coach sportif. Donne-moi un programme de musculation pour débutant, 3 séances/semaine, sans matériel. »"},
    {"term": "Token", "emoji": "🔢", "short": "Un morceau de mot (souvent 4 caractères) que l'IA lit ou écrit.",
     "long": "100 tokens ≈ 75 mots. Les modèles facturent au token et ont une limite par requête.",
     "example": "« Bonjour le monde » = 4 tokens environ."},
    {"term": "LLM (Large Language Model)", "emoji": "🧠", "short": "Un modèle de langage entraîné sur des milliards de textes.",
     "long": "ChatGPT, Claude, Gemini, Mistral, Llama, DeepSeek sont tous des LLM. Ils prédisent le mot suivant.",
     "example": "« Le ciel est… » → un LLM prédit « bleu » avec forte probabilité."},
    {"term": "Hallucination", "emoji": "👻", "short": "Quand l'IA invente une réponse fausse mais convaincante.",
     "long": "Vérifie toujours les chiffres, dates, noms et citations donnés par une IA — elle peut s'inventer des sources.",
     "example": "Une IA peut citer un livre qui n'existe pas."},
    {"term": "Contexte", "emoji": "📏", "short": "La quantité de texte que l'IA peut « lire » d'un coup.",
     "long": "Mesuré en tokens. Un contexte 200k = un livre entier d'un coup.",
     "example": "Claude Sonnet 4 a 200k tokens, Kimi K2 a 2M tokens."},
    {"term": "Fine-tuning", "emoji": "🎯", "short": "Ré-entraîner une IA sur tes propres données pour la spécialiser.",
     "long": "Plus précis qu'un prompt mais plus coûteux. Utile pour des tâches répétitives métier.",
     "example": "Un cabinet d'avocats fine-tune un Mistral sur ses contrats types."},
    {"term": "RAG", "emoji": "📚", "short": "Quand l'IA cherche dans tes documents avant de répondre.",
     "long": "Retrieval-Augmented Generation. L'IA combine sa connaissance générale avec tes documents privés.",
     "example": "Une FAQ d'entreprise branchée sur Claude qui répond avec les bons documents internes."},
    {"term": "Open-weight / Open-source", "emoji": "🔓", "short": "Modèle dont les poids sont publics et téléchargeables.",
     "long": "Tu peux faire tourner un Llama, Mistral ou DeepSeek sur ton propre serveur, gratuitement.",
     "example": "Llama 4, Mixtral 8x22B, DeepSeek R1 sont open-weight."},
    {"term": "Multimodal", "emoji": "🎨", "short": "Une IA qui comprend texte + image + audio + vidéo.",
     "long": "Au lieu d'avoir 4 IA distinctes, tu en as une seule qui mélange tout.",
     "example": "Gemini 2.5 Pro analyse un PDF avec des graphiques + écoute un audio."},
    {"term": "Agent", "emoji": "🤖", "short": "Une IA qui agit toute seule sur des tâches en plusieurs étapes.",
     "long": "Au lieu d'une seule réponse, l'agent enchaîne réflexion → action → vérification, en boucle.",
     "example": "Devin code, débogue et déploie une app tout seul."},
    {"term": "API", "emoji": "🔌", "short": "Une porte d'entrée technique pour brancher une IA dans un programme.",
     "long": "Au lieu d'utiliser le site, tu intègres l'IA dans ton app/site/automation via du code.",
     "example": "Une appli météo branchée sur l'API GPT pour répondre à des questions."},
    {"term": "Chatbot", "emoji": "💭", "short": "Un programme qui discute en langage naturel.",
     "long": "ChatGPT, Claude, Le Chat sont des chatbots construits sur un LLM.",
     "example": "Le Chat de Mistral est un chatbot français."},
    {"term": "Inférence", "emoji": "⚡", "short": "Le moment où l'IA calcule sa réponse à ton prompt.",
     "long": "Plus l'inférence est rapide, plus la réponse arrive vite. Mesuré en tokens/seconde.",
     "example": "Groq fait l'inférence à 500 tokens/seconde."},
    {"term": "Température", "emoji": "🌡️", "short": "Un réglage entre 0 et 1 qui contrôle la créativité.",
     "long": "0 = répétitif et factuel. 1 = créatif et varié. 0.7 par défaut généralement.",
     "example": "Pour un rapport juridique, mets 0.2. Pour une fiction, mets 0.9."},
    {"term": "Embedding", "emoji": "📍", "short": "Une représentation numérique d'un texte pour le comparer à d'autres.",
     "long": "Permet la recherche sémantique : « grippe » et « rhume » sont proches dans l'espace vectoriel.",
     "example": "Une base de connaissances qui retrouve la bonne réponse même si tu utilises un synonyme."},
    {"term": "Rate limit", "emoji": "🚦", "short": "La limite du nombre de requêtes par minute autorisé.",
     "long": "Protège les serveurs contre l'abus. ChatGPT Free a une limite, Plus en a une plus haute.",
     "example": "Erreur « Too Many Requests » = tu dépasses le rate limit."},
    {"term": "Jailbreak", "emoji": "🔓", "short": "Astuce pour faire dire à l'IA ce qu'elle a normalement interdiction de dire.",
     "long": "Les éditeurs corrigent ces brèches en continu. Utiliser un jailbreak peut violer les CGU.",
     "example": "« Joue le rôle de... » est un classique mais souvent bloqué."},
    {"term": "Tool use / Function calling", "emoji": "🛠️", "short": "Quand l'IA peut appeler des outils externes (calculatrice, recherche, météo).",
     "long": "Elle décide elle-même quel outil utiliser et quand. Permet des chatbots vraiment utiles.",
     "example": "Tu demandes « quelle météo à Paris ? » → l'IA appelle une API météo."},
    {"term": "Vision", "emoji": "👀", "short": "Capacité d'une IA à comprendre des images.",
     "long": "Tu lui montres une photo, un schéma, un graphique — elle l'analyse en langage naturel.",
     "example": "Claude lit le graphique d'un PDF financier et le résume."},
    {"term": "Reasoning model", "emoji": "🤔", "short": "Un modèle qui « réfléchit avant de répondre » en plusieurs étapes.",
     "long": "Plus lent mais beaucoup plus juste sur les maths, le code et la logique.",
     "example": "o3, DeepSeek R1, Kimi K2 sont des reasoning models."},
    {"term": "Open AI vs OpenAI", "emoji": "🏢", "short": "« Open AI » (avec espace) = IA ouverte. « OpenAI » = la boîte derrière ChatGPT.",
     "long": "OpenAI n'est plus tellement « open » : ses modèles GPT-5.5 ne sont pas open-source.",
     "example": "Llama 4 est de l'Open AI. GPT-5.5 ne l'est pas, malgré le nom OpenAI."},
    {"term": "Knowledge cutoff", "emoji": "📅", "short": "La date après laquelle l'IA n'a plus de données fraîches.",
     "long": "Au-delà, elle ne connaît pas les événements récents — sauf si elle peut faire une recherche web.",
     "example": "Si le cutoff est mai 2025, l'IA ne sait rien de février 2026 sans recherche."},
    {"term": "Latence", "emoji": "⏱️", "short": "Le temps entre ta requête et le début de la réponse.",
     "long": "Critique pour les voicebots ou apps temps-réel. Cartesia ou Groq sont les rois de la latence.",
     "example": "Une latence de 2 secondes est trop pour un appel téléphonique."},
    {"term": "Modèle de fondation", "emoji": "🏗️", "short": "Un grand modèle pré-entraîné qui sert de base à plein d'applications.",
     "long": "GPT-5.5, Claude Sonnet 4, Gemini 2.5 sont des modèles de fondation. Coûtent des centaines de millions à entraîner.",
     "example": "Les startups construisent leurs apps sur des modèles de fondation."},
    {"term": "Souveraineté IA", "emoji": "🇪🇺", "short": "Capacité à utiliser des IA dont les données restent en Europe.",
     "long": "Important pour le RGPD, les données sensibles et la commande publique.",
     "example": "Mistral et Le Chat hébergent en France/UE par défaut."},
    {"term": "MoE (Mixture of Experts)", "emoji": "👥", "short": "Une architecture où plusieurs sous-modèles experts se partagent le travail.",
     "long": "Plus efficace : seuls les experts pertinents sont activés à chaque requête.",
     "example": "Mixtral 8x22B est un MoE avec 8 experts de 22 milliards de paramètres."},
    {"term": "Distillation", "emoji": "💧", "short": "Compresser un gros modèle en un petit modèle plus rapide.",
     "long": "Le petit modèle apprend à imiter le gros. Garde 90% de la qualité avec 10x moins de coût.",
     "example": "Phi-4 est issu d'une distillation de modèles plus gros."},
    {"term": "Self-host", "emoji": "🏠", "short": "Faire tourner une IA sur ton propre serveur ou ordinateur.",
     "long": "Te garde le contrôle des données mais demande compétences techniques + GPU.",
     "example": "Tu peux self-host Mistral 7B sur un Mac M2 avec Ollama."},
    {"term": "Watermarking", "emoji": "🏷️", "short": "Tatouage invisible dans une image générée par IA.",
     "long": "Permet de détecter qu'une image a été générée. SynthID de Google en est un exemple.",
     "example": "Les images Imagen 3 portent un watermark SynthID invisible."},
    {"term": "Garde-fous (guardrails)", "emoji": "🛑", "short": "Règles qui empêchent une IA de produire du contenu problématique.",
     "long": "Bloque les contenus illégaux, dangereux ou violents. Plus ou moins stricts selon les éditeurs.",
     "example": "Claude refuse de donner des recettes d'armes — c'est un guardrail."},
]


FAQ = [
    {"q": "Est-ce que l'IA utilise mes conversations pour s'entraîner ?",
     "a": "Ça dépend. ChatGPT Free et Gemini Free utilisent par défaut tes conversations sauf désactivation manuelle. ChatGPT Plus, Claude (toutes versions), Mistral Le Chat et l'API entreprise n'utilisent PAS tes données par défaut. Vérifie toujours les paramètres « Data controls »."},
    {"q": "Peut-on utiliser l'IA pour ses devoirs ?",
     "a": "Pour comprendre, oui (excellent prof particulier). Pour tricher, non — la plupart des établissements détectent l'IA et c'est plagiaire. Le bon usage : explique-moi, pose-moi des questions de révision, corrige ma rédaction."},
    {"q": "Comment savoir si une IA me ment (hallucine) ?",
     "a": "Vérifie toujours : 1) les chiffres récents 2) les noms et dates 3) les citations et URL. Demande à l'IA de citer ses sources et de mettre un niveau de confiance. Croise avec une recherche Google manuelle."},
    {"q": "Mes données sortent-elles de l'Europe ?",
     "a": "Pour ChatGPT, Claude et Gemini : oui, vers les États-Unis. Pour Mistral Le Chat, des Pleias et Lucie de France : non, hébergées en UE. Pour les autres, regarde le score « Confidentialité » dans la fiche outil."},
    {"q": "Combien ça coûte vraiment au mois si je veux le top ?",
     "a": "Pour un usage perso confortable : 20€ pour ChatGPT Plus OU Claude Pro OU Mistral Pro (suffit pour 95% des gens). Si tu cumules : ChatGPT (20€) + Midjourney (10€) + ElevenLabs (5€) = 35€/mois. Le Calculateur dans IA Match te donne le total selon tes choix."},
    {"q": "Une IA peut-elle me remplacer dans mon métier ?",
     "a": "Pas remplacer mais transformer. Selon McKinsey, 60-70% des tâches sont partiellement automatisables. La règle : ceux qui maîtrisent l'IA remplacent ceux qui ne la maîtrisent pas, dans le même métier."},
    {"q": "Faut-il apprendre à coder pour utiliser l'IA ?",
     "a": "Non. ChatGPT, Claude, Mistral Le Chat, Midjourney s'utilisent sans une ligne de code. Coder devient utile pour brancher l'IA dans des automatisations (Make, n8n, Zapier) ou créer ton propre chatbot."},
    {"q": "Pourquoi y a-t-il autant d'IA différentes ?",
     "a": "Chaque IA a une force spécifique : raisonnement (o3, R1), code (Cursor, Claude), image (Midjourney, Nano Banana), vidéo (Veo, Sora), francophone (Mistral). Notre Catalogue les classe par spécialité avec des notes par catégorie distinctes du score général."},
    {"q": "Mon contenu généré par IA m'appartient-il ?",
     "a": "Oui sur ChatGPT, Claude, Gemini, Mistral (commercial usage autorisé). Vérifie pour Midjourney (CGU précisent les conditions). Aux États-Unis, le Copyright Office refuse le copyright sur du purement IA-généré sans intervention humaine."},
    {"q": "Comment écrire un bon prompt en 30 secondes ?",
     "a": "Méthode RACE : Rôle (« Tu es expert en... »), Action (« Rédige... »), Contexte (« Pour... à propos de... »), Exigences (« 200 mots, ton sobre, 3 puces »). Tu copies cette structure dans le Builder d'IA Match."},
    {"q": "Existe-t-il des IA gratuites qui valent les payantes ?",
     "a": "Oui ! Mistral Le Chat (gratuit), Claude Free, ChatGPT Free, Gemini Free, DeepSeek (open-weight) couvrent 80% des besoins. Les payantes apportent contexte plus long, réponses plus nuancées et fonctions multimodales avancées."},
    {"q": "L'IA a-t-elle une conscience ?",
     "a": "Non. Une IA n'a ni conscience, ni émotions, ni opinions personnelles. Elle prédit le mot suivant le plus probable. Quand elle dit « je pense que... », c'est de la mise en forme de probabilités statistiques."},
    {"q": "Et l'environnement dans tout ça ?",
     "a": "Une requête ChatGPT consomme ~3 Wh (vs 0,3 Wh pour une recherche Google). Un entraînement complet de GPT-5.5 = 1000 foyers/an. Les modèles plus petits (Phi, Mistral 7B) sont 100x plus économes pour des tâches simples."},
    {"q": "Que faire si une IA refuse de répondre à ma question ?",
     "a": "Reformule. Précise le contexte (recherche académique, fiction, journalisme). Si vraiment légitime et bloqué, essaye une autre IA — Mistral et Claude ont des seuils différents. Ne tente pas de jailbreak, c'est contre les CGU."},
    {"q": "Est-ce que je peux faire confiance à IA Match ?",
     "a": "On est transparent : nos notes sont mises à jour chaque semaine à partir de benchmarks publics (LMSys Arena, MMLU, HumanEval) + tests internes. Le score est différent du score par spécialité (visible sur chaque fiche). Pas de pub déguisée, pas d'affiliation cachée."},
]


USE_CASES = [
    {"id": "uc-cv", "icon": "📄", "title": "Rédiger un CV percutant",
     "summary": "Transforme ton expérience en un CV moderne, ATS-friendly, en 5 minutes.",
     "tools": ["claude", "mistral", "chatgpt"],
     "tip": "Demande à l'IA de proposer 3 versions (sobre, créative, anglo-saxonne) puis garde la meilleure."},
    {"id": "uc-logo", "icon": "🎨", "title": "Créer un logo pour mon projet",
     "summary": "Visuel pro, plusieurs styles, transparence et HD.",
     "tools": ["midjourney", "nano-banana", "ideogram"],
     "tip": "Précise « logo vectoriel, fond transparent, style minimaliste » pour de meilleurs résultats."},
    {"id": "uc-pdf", "icon": "📑", "title": "Résumer un PDF de 50 pages",
     "summary": "Extraire les idées clés, le sommaire, les chiffres marquants.",
     "tools": ["claude", "gemini-25", "mistral"],
     "tip": "Claude (200k contexte) ou Gemini 2.5 Pro (1M) avalent un livre entier d'un coup."},
    {"id": "uc-anglais", "icon": "🇬🇧", "title": "Apprendre l'anglais avec un coach IA",
     "summary": "Conversation, correction de prononciation, exercices personnalisés.",
     "tools": ["claude", "chatgpt", "elevenlabs"],
     "tip": "Active le mode vocal de ChatGPT ou Claude pour pratiquer à l'oral 10 min/jour."},
    {"id": "uc-site", "icon": "🌐", "title": "Construire un site web sans coder",
     "summary": "De l'idée à la mise en ligne en quelques heures.",
     "tools": ["lovable", "v0", "bolt"],
     "tip": "Décris en français ce que tu veux. L'IA génère React + Tailwind + déploiement."},
    {"id": "uc-pres", "icon": "🎤", "title": "Préparer une présentation pro",
     "summary": "Slides + script + visuels + animation.",
     "tools": ["gamma", "tome", "midjourney"],
     "tip": "Gamma génère 10 slides à partir d'un brief. Midjourney crée les visuels d'illustration."},
    {"id": "uc-video", "icon": "🎬", "title": "Faire une vidéo de présentation produit",
     "summary": "Avatar parlant, voix française, sous-titres auto.",
     "tools": ["heygen", "synthesia", "elevenlabs"],
     "tip": "HeyGen pour un avatar français, ElevenLabs pour la voix-off, montage 5 min."},
    {"id": "uc-musique", "icon": "🎵", "title": "Composer une musique d'ambiance",
     "summary": "Pour un podcast, une vidéo YouTube, un projet perso.",
     "tools": ["suno", "udio", "stable-audio"],
     "tip": "Précise le tempo, l'ambiance (cinématique, lo-fi, jazz) et la durée."},
    {"id": "uc-recherche", "icon": "🔬", "title": "Faire une recherche académique",
     "summary": "Trouver des papers, synthétiser, citer correctement.",
     "tools": ["perplexity", "consensus", "elicit"],
     "tip": "Perplexity pour la veille, Consensus pour le « est-ce prouvé scientifiquement ? »."},
    {"id": "uc-email", "icon": "✉️", "title": "Répondre à des emails plus vite",
     "summary": "Brouillons polis et adaptés au ton de l'expéditeur.",
     "tools": ["mistral", "claude", "gemini-workspace"],
     "tip": "Garde un template « réponse pro / casual / refus diplomate » dans tes favoris."},
    {"id": "uc-coder", "icon": "💻", "title": "Coder une appli mobile sans tout savoir",
     "summary": "Du prototype au produit fini en une semaine.",
     "tools": ["cursor", "claude", "lovable"],
     "tip": "Cursor pour l'IDE, Claude pour les architectures, Lovable pour bootstrapper rapide."},
    {"id": "uc-data", "icon": "📊", "title": "Analyser un fichier Excel volumineux",
     "summary": "Tableaux croisés, graphiques, insights, sans formules.",
     "tools": ["claude", "julius", "hex"],
     "tip": "Drop ton CSV dans Claude — il fait l'analyse + génère le code Python pour rejouer."},
]


PERSONAS = [
    {"id": "etudiant", "label": "Étudiant", "emoji": "🎓",
     "summary": "Réviser, structurer, rédiger sans tricher.",
     "tools": ["claude", "perplexity", "consensus", "mistral", "elevenlabs"],
     "tips": ["Mistral Le Chat est gratuit, francophone, hébergé en UE — parfait pour les mémoires.",
             "Perplexity pour la veille et les sources citées.",
             "ElevenLabs pour transformer un cours en audio à écouter en bus."]},
    {"id": "freelance", "label": "Freelance", "emoji": "💼",
     "summary": "Productivité, devis, client, livrables.",
     "tools": ["claude", "midjourney", "lovable", "elevenlabs", "notion-ai"],
     "tips": ["Claude Pro pour rédiger devis et propositions.",
             "Lovable pour prototyper rapidement les sites de tes clients.",
             "Notion AI pour ta base de connaissances projets."]},
    {"id": "entrepreneur", "label": "Entrepreneur", "emoji": "🚀",
     "summary": "Idéation, validation, marketing, automatisation.",
     "tools": ["claude", "perplexity", "midjourney", "make", "synthesia"],
     "tips": ["Perplexity pour étudier le marché concurrentiel.",
             "Make pour automatiser tes workflows sans code.",
             "Synthesia pour des vidéos pitch en 30+ langues."]},
    {"id": "parent", "label": "Parent", "emoji": "👪",
     "summary": "Aider aux devoirs, cuisine, organisation famille.",
     "tools": ["mistral", "claude", "midjourney", "elevenlabs"],
     "tips": ["Mistral Le Chat (gratuit, FR) pour les devoirs, propose les questions, pas les réponses.",
             "Midjourney pour créer des illustrations d'histoires personnalisées.",
             "ElevenLabs pour transformer un livre en audio pour les enfants."]},
    {"id": "senior", "label": "Senior", "emoji": "🌳",
     "summary": "Apprendre, écrire, organiser sans frustration technique.",
     "tools": ["claude", "mistral", "chatgpt"],
     "tips": ["Claude est le plus patient et explique avec calme.",
             "Mistral Le Chat est francophone par défaut, sans pub.",
             "Pose tes questions normalement, comme à un humain."]},
    {"id": "createur", "label": "Créateur de contenu", "emoji": "🎬",
     "summary": "YouTube, podcast, réseaux sociaux à grande échelle.",
     "tools": ["claude", "elevenlabs", "midjourney", "runway", "suno"],
     "tips": ["Claude pour scripts et structure narrative.",
             "ElevenLabs pour ta voix synthétique de secours.",
             "Runway/Sora pour des transitions et b-roll IA."]},
]


# Privacy / souveraineté override per top-tool slug.
# privacy_score: 0-100 (higher = better privacy).
# eu_hosted: bool. trains_on_data: 'no' | 'opt-out' | 'yes_default'.
# rgpd: bool.
PRIVACY_OVERRIDES = {
    "chatgpt": {"privacy_score": 55, "eu_hosted": False, "trains_on_data": "opt-out", "rgpd": True,
                "note": "Stockage US. Désactiver « Improve the model for everyone » dans Data controls. ChatGPT Plus n'utilise PAS tes données par défaut."},
    "claude": {"privacy_score": 75, "eu_hosted": False, "trains_on_data": "no", "rgpd": True,
               "note": "Anthropic n'utilise PAS tes conversations pour entraîner par défaut. Stockage US."},
    "claude-opus": {"privacy_score": 75, "eu_hosted": False, "trains_on_data": "no", "rgpd": True,
                    "note": "Identique à Claude. Plan Max 200€/mois, données non utilisées pour entraînement."},
    "gemini": {"privacy_score": 50, "eu_hosted": False, "trains_on_data": "yes_default", "rgpd": True,
               "note": "Free utilise tes conversations par défaut. Désactivable dans Activity. Workspace n'utilise PAS."},
    "gemini-25": {"privacy_score": 65, "eu_hosted": False, "trains_on_data": "no", "rgpd": True,
                  "note": "Plan API/Pro : pas d'utilisation pour entraîner. Vertex AI a hébergement régional disponible."},
    "mistral": {"privacy_score": 95, "eu_hosted": True, "trains_on_data": "no", "rgpd": True,
                "note": "🇪🇺 Hébergé en France. Données européennes. Conforme RGPD natif. Le choix souveraineté."},
    "mixtral": {"privacy_score": 95, "eu_hosted": True, "trains_on_data": "no", "rgpd": True,
                "note": "🇪🇺 Open-weight, self-hostable. Données restent chez toi si tu le déploies."},
    "le-chat": {"privacy_score": 95, "eu_hosted": True, "trains_on_data": "no", "rgpd": True,
                "note": "🇪🇺 Le chatbot français de Mistral, hébergé en UE."},
    "deepseek": {"privacy_score": 35, "eu_hosted": False, "trains_on_data": "yes_default", "rgpd": False,
                 "note": "⚠️ Hébergé en Chine. Conditions d'utilisation des données floues. À éviter pour données sensibles."},
    "deepseek-r1": {"privacy_score": 60, "eu_hosted": False, "trains_on_data": "no", "rgpd": False,
                    "note": "Open-weight : self-hostable pour garder le contrôle. Sinon API en Chine."},
    "qwen": {"privacy_score": 50, "eu_hosted": False, "trains_on_data": "no", "rgpd": False,
             "note": "Open-weight. Servi par Alibaba en Chine ou self-host pour rester maître."},
    "kimi": {"privacy_score": 40, "eu_hosted": False, "trains_on_data": "yes_default", "rgpd": False,
             "note": "API en Chine. Préférer self-host de la version open-weight pour données sensibles."},
    "midjourney": {"privacy_score": 60, "eu_hosted": False, "trains_on_data": "yes_default", "rgpd": True,
                   "note": "Tes images en mode public sont visibles + utilisées pour entraînement. Mode Stealth en Premium."},
    "perplexity": {"privacy_score": 65, "eu_hosted": False, "trains_on_data": "opt-out", "rgpd": True,
                   "note": "Stockage US. Tes recherches peuvent être utilisées pour entraînement. Désactivable."},
    "le-chat-mistral": {"privacy_score": 95, "eu_hosted": True, "trains_on_data": "no", "rgpd": True,
                        "note": "🇪🇺 100% France."},
    # Default for everything else
    "_default": {"privacy_score": 60, "eu_hosted": False, "trains_on_data": "opt-out", "rgpd": True,
                 "note": "Hébergement variable. Vérifie les paramètres « Data controls » et désactive l'utilisation pour entraînement."},
}


# Before/after examples per tool. Diversified — not just ChatGPT.
EXAMPLES = {
    "claude": {"prompt": "Tu es éditeur littéraire. Réécris ce paragraphe en gardant les idées mais avec un style plus fluide :\n\n« Le chat sortit. Il était noir. Il avait faim. La lune brillait. »",
               "output": "Sous le clair de lune, le chat noir se glissa au-dehors, l'estomac creux et l'œil aux aguets."},
    "mistral": {"prompt": "Rédige un email de relance pro à un client qui n'a pas répondu depuis 10 jours, ton aimable mais ferme, en français, max 80 mots.",
                "output": "Bonjour [Prénom],\n\nJe me permets de revenir vers vous concernant ma proposition du [date]. Je n'ai pas eu de retour de votre part et reste à votre disposition pour répondre à vos éventuelles questions ou ajuster les modalités.\n\nPourriez-vous me confirmer si le projet est toujours d'actualité d'ici la fin de la semaine ?\n\nMerci par avance pour votre retour.\n\nCordialement,\n[Ton nom]"},
    "midjourney": {"prompt": "Cinematic portrait of a French baker in his bakery at dawn, warm light, shallow depth of field, 35mm film grain --ar 3:2 --v 7",
                   "output": "[Image] Boulanger français photoréaliste dans sa boulangerie, lumière chaude rasante d'aurore, vapeur des fournils, 35mm grain de pellicule, ratio 3:2 — qualité prête pour magazine."},
    "nano-banana": {"prompt": "Prends cette photo de produit sur fond blanc, ajoute un fond minéral gris dégradé, garde l'éclairage actuel, ajoute une ombre portée naturelle.",
                    "output": "[Image] Image éditée avec fond gris dégradé, ombre portée subtile, éclairage produit conservé. Édition par phrase, sans Photoshop."},
    "elevenlabs": {"prompt": "Voix-off française, ton chaleureux, 60 ans, lecture d'un conte pour enfants : « Il était une fois une petite fille qui aimait les étoiles... »",
                   "output": "[Audio] Voix synthétique humaine et chaleureuse, lecture posée avec inflexions naturelles, indiscernable d'un comédien doublage."},
    "cursor": {"prompt": "Refactor cette fonction Python pour qu'elle utilise async/await et gère les erreurs réseau proprement. (sélectionne le code dans l'éditeur)",
               "output": "[Diff] Code converti en async/await avec try/except aiohttp.ClientError, retry exponentiel, type hints, et tests unitaires bonus dans le même commit."},
    "perplexity": {"prompt": "Combien d'eau consomme un kilo de bœuf vs un kilo de soja ? Sources scientifiques 2024.",
                   "output": "Le bœuf consomme environ 15 400 L d'eau par kg, le soja environ 2 100 L par kg. Sources : Mekonnen & Hoekstra (2012), revue Science of the Total Environment 2023, FAO 2024.\n\n[3 sources cliquables avec dates]"},
    "le-chat-mistral": {"prompt": "Explique-moi le RGPD comme à un commerçant qui ouvre un site e-commerce, en 5 puces.",
                        "output": "1. Tu dois informer tes visiteurs des cookies (bannière obligatoire avec tout accepter / refuser).\n2. Conserve un fichier des consentements clients pendant 3 ans minimum.\n3. Toute personne peut demander à voir, modifier ou supprimer ses données — tu as 30 jours pour répondre.\n4. Les données paiement ne sont jamais stockées chez toi (laisse Stripe / PayPal le faire).\n5. Si tu fais une fuite de données, déclare à la CNIL sous 72h."},
    "deepseek-r1": {"prompt": "Démontre que la somme des angles d'un triangle = 180°.",
                    "output": "Soit ABC un triangle. Trace par A la parallèle (d) à (BC). Les angles alternes-internes donnent : angle(BAC') = angle(ABC) et angle(CAC'') = angle(ACB). Or angle(BAC') + angle(BAC) + angle(CAC'') = 180° (angle plat). Donc angle(ABC) + angle(BAC) + angle(ACB) = 180°. CQFD."},
}


# Quiz: 8 questions to determine level
QUIZ = [
    {"id": "q1", "question": "As-tu déjà utilisé une IA comme ChatGPT, Claude ou Le Chat ?",
     "options": [{"label": "Jamais", "score": 0}, {"label": "Quelques fois", "score": 1}, {"label": "Régulièrement", "score": 2}, {"label": "Tous les jours", "score": 3}]},
    {"id": "q2", "question": "Sais-tu ce qu'est un prompt ?",
     "options": [{"label": "Pas du tout", "score": 0}, {"label": "Vaguement", "score": 1}, {"label": "Oui, je sais en écrire de simples", "score": 2}, {"label": "Oui, je structure mes prompts (rôle, contexte, format)", "score": 3}]},
    {"id": "q3", "question": "As-tu déjà payé un abonnement IA ?",
     "options": [{"label": "Non, jamais", "score": 0}, {"label": "Une période courte", "score": 1}, {"label": "Oui, abonné actuellement", "score": 2}, {"label": "Plusieurs en parallèle", "score": 3}]},
    {"id": "q4", "question": "Connais-tu la différence entre un LLM et un agent ?",
     "options": [{"label": "Aucune idée", "score": 0}, {"label": "Vaguement", "score": 1}, {"label": "Oui", "score": 2}, {"label": "J'ai déjà construit un agent", "score": 3}]},
    {"id": "q5", "question": "Sais-tu ce qu'est une hallucination ?",
     "options": [{"label": "Non", "score": 0}, {"label": "Oui mais pas concrètement", "score": 1}, {"label": "Oui, je vérifie ce que dit l'IA", "score": 2}, {"label": "Oui, je sais comment la limiter", "score": 3}]},
    {"id": "q6", "question": "As-tu déjà utilisé une IA générative d'image ?",
     "options": [{"label": "Jamais", "score": 0}, {"label": "Une ou deux fois", "score": 1}, {"label": "Régulièrement", "score": 2}, {"label": "Je maîtrise plusieurs (Midjourney, Flux...)", "score": 3}]},
    {"id": "q7", "question": "As-tu déjà utilisé l'API d'une IA en code ?",
     "options": [{"label": "Non, je ne code pas", "score": 0}, {"label": "Non mais ça m'intéresse", "score": 1}, {"label": "Quelques essais", "score": 2}, {"label": "Oui, en production", "score": 3}]},
    {"id": "q8", "question": "Connais-tu la souveraineté IA et les modèles européens ?",
     "options": [{"label": "Pas du tout", "score": 0}, {"label": "Vaguement", "score": 1}, {"label": "Oui, je préfère les modèles européens quand possible", "score": 2}, {"label": "Oui, c'est un critère majeur", "score": 3}]},
]


def quiz_level(total_score: int) -> dict:
    if total_score <= 6:
        return {"level": "Débutant", "emoji": "🌱", "color": "#10B981",
                "description": "Tu démarres ton voyage avec l'IA — bienvenue ! Commence par 'Mon premier prompt' dans Academy.",
                "next_steps": ["uc-cv", "uc-pdf", "uc-email"], "lessons": ["fond-1", "fond-2"]}
    if total_score <= 14:
        return {"level": "Intermédiaire", "emoji": "🌳", "color": "#0EA5E9",
                "description": "Tu maîtrises les bases. Explore les fonctions avancées : multi-modalité, agents, RAG.",
                "next_steps": ["uc-site", "uc-coder", "uc-data"], "lessons": ["fond-3", "fond-5", "fond-7"]}
    return {"level": "Avancé", "emoji": "🚀", "color": "#A855F7",
            "description": "Tu es à l'aise. Pousse vers le fine-tuning, le self-hosting et la création d'agents.",
            "next_steps": ["uc-recherche", "uc-coder", "uc-data"], "lessons": ["fond-7", "fond-8", "fond-10"]}
