"""Extension to seed_data.py — 60+ additional LLM models & AI pro tools (no consumer chatbots)."""

EXTRA_TOOLS = [
    # ===== LLMs / Text generation =====
    {"slug": "qwen", "name": "Qwen 3", "vendor": "Alibaba", "domain": "qwen.ai",
     "tagline": "Le LLM chinois open-weight ultra-multilingue",
     "description": "Modèle puissant, open-weight, excellent en raisonnement, code et 100+ langues. Variant 235B et MoE.",
     "categorySlugs": ["texte", "code", "recherche"], "speedMs": 220, "accuracyPct": 91,
     "costPerPrompt": 0.0008, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["fr", "en", "zh", "ja", "ko", "es", "de", "ar"],
     "features": ["Open-weight", "Reasoning", "Multilingue", "MoE"],
     "useCases": ["Volume API massif", "Self-hosting", "Multilingue avancé"],
     "keywords": ["qwen", "alibaba", "open", "chinois", "multilingue", "code"],
     "score": 90, "color": "#615CED"},

    {"slug": "kimi", "name": "Kimi K2", "vendor": "Moonshot AI", "domain": "kimi.com",
     "tagline": "Le contexte 2M tokens du chinois Moonshot",
     "description": "Modèle de raisonnement chinois avec contexte ultra-long (2M tokens), excellent en agentique.",
     "categorySlugs": ["texte", "recherche", "agent"], "speedMs": 350, "accuracyPct": 92,
     "costPerPrompt": 0.0006, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["zh", "en", "fr"],
     "features": ["Contexte 2M", "Agent natif", "Open-weight"],
     "useCases": ["Analyser dossiers volumineux", "Agents long-running"],
     "keywords": ["kimi", "moonshot", "long contexte", "agent", "open"],
     "score": 89, "color": "#000000"},

    {"slug": "llama", "name": "Llama 4", "vendor": "Meta", "domain": "llama.com",
     "tagline": "Le LLM open-weight de référence",
     "description": "Famille de modèles Meta open-weight (Scout, Maverick, Behemoth) avec multimodal natif.",
     "categorySlugs": ["texte", "code", "image"], "speedMs": 200, "accuracyPct": 90,
     "costPerPrompt": 0.0003, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["fr", "en", "es", "de", "hi", "pt"],
     "features": ["Open-weight", "Multimodal", "Self-host"],
     "useCases": ["Self-hosting", "Apps embarquées", "Recherche académique"],
     "keywords": ["llama", "meta", "open", "facebook"],
     "score": 91, "color": "#0866FF"},

    {"slug": "command-r", "name": "Command R+", "vendor": "Cohere", "domain": "cohere.com",
     "tagline": "Le LLM enterprise spécialisé RAG",
     "description": "Modèle Cohere optimisé pour le RAG, le tool-use et les workflows entreprise.",
     "categorySlugs": ["texte", "recherche", "agent"], "speedMs": 180, "accuracyPct": 88,
     "costPerPrompt": 0.0025, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["fr", "en", "es", "de", "ja", "ar"],
     "features": ["RAG natif", "Tool-use", "Citations"],
     "useCases": ["Chatbot interne", "Knowledge base", "Tool-use"],
     "keywords": ["cohere", "rag", "enterprise", "command"],
     "score": 86, "color": "#39594D"},

    {"slug": "yi", "name": "Yi-Large", "vendor": "01.AI", "domain": "01.ai",
     "tagline": "Le LLM bilingue de Kai-Fu Lee",
     "description": "Modèle chinois performant, open-weight, fort en chinois-anglais et raisonnement.",
     "categorySlugs": ["texte", "code"], "speedMs": 230, "accuracyPct": 87,
     "costPerPrompt": 0.0007, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["zh", "en"],
     "features": ["Open-weight", "Bilingue ZH-EN"],
     "useCases": ["Apps Chine-Occident", "Self-hosting"],
     "keywords": ["yi", "01.ai", "chinois", "open"],
     "score": 84, "color": "#1F1F1F"},

    {"slug": "glm", "name": "GLM-4", "vendor": "Zhipu AI", "domain": "zhipuai.cn",
     "tagline": "Le LLM chinois multimodal",
     "description": "Famille GLM avec vision, code et raisonnement, déployable en local.",
     "categorySlugs": ["texte", "image", "code"], "speedMs": 240, "accuracyPct": 86,
     "costPerPrompt": 0.0008, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["zh", "en"],
     "features": ["Multimodal", "Vision", "Open-weight"],
     "useCases": ["Self-hosting", "Vision-task"],
     "keywords": ["glm", "zhipu", "chinois", "multimodal"],
     "score": 83, "color": "#0066CC"},

    {"slug": "phi", "name": "Phi-4", "vendor": "Microsoft", "domain": "microsoft.com",
     "tagline": "Le petit modèle qui frappe fort",
     "description": "Modèle compact Microsoft surperformant pour sa taille — idéal embarqué.",
     "categorySlugs": ["texte", "code"], "speedMs": 90, "accuracyPct": 84,
     "costPerPrompt": 0.0001, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["en", "fr"],
     "features": ["Compact", "Open-weight", "Embarqué"],
     "useCases": ["Edge deployment", "Apps mobiles", "Latence ultra-faible"],
     "keywords": ["phi", "microsoft", "petit", "edge", "mobile"],
     "score": 82, "color": "#0078D4"},

    {"slug": "nemotron", "name": "Nemotron", "vendor": "NVIDIA", "domain": "nvidia.com",
     "tagline": "Le LLM Nvidia optimisé inference",
     "description": "Modèle Nvidia hautes performances optimisé pour H100/H200 et workflows agentiques.",
     "categorySlugs": ["texte", "code", "agent"], "speedMs": 150, "accuracyPct": 89,
     "costPerPrompt": 0.0005, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["en", "fr"],
     "features": ["Optimisé Nvidia", "Reward model", "Agentic"],
     "useCases": ["Pipelines GPU", "Agents", "Fine-tuning"],
     "keywords": ["nemotron", "nvidia", "gpu", "agent"],
     "score": 85, "color": "#76B900"},

    {"slug": "mixtral", "name": "Mixtral 8x22B", "vendor": "Mistral AI", "domain": "mistral.ai",
     "tagline": "L'expert MoE européen",
     "description": "Mixture of experts français, ratio qualité/coût exceptionnel, open-weight Apache 2.0.",
     "categorySlugs": ["texte", "code", "recherche"], "speedMs": 160, "accuracyPct": 90,
     "costPerPrompt": 0.0006, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["fr", "en", "es", "de", "it"],
     "features": ["MoE 8x22B", "Apache 2.0", "Self-host"],
     "useCases": ["Volume API", "Self-hosting Europe"],
     "keywords": ["mixtral", "mistral", "moe", "expert", "open", "français"],
     "score": 89, "color": "#FA520F"},

    {"slug": "reka", "name": "Reka Core", "vendor": "Reka AI", "domain": "reka.ai",
     "tagline": "Le multimodal compact",
     "description": "Modèle multimodal natif (texte + image + audio + vidéo) en un seul modèle.",
     "categorySlugs": ["texte", "image", "audio", "video"], "speedMs": 250, "accuracyPct": 86,
     "costPerPrompt": 0.001, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["en", "fr", "ja"],
     "features": ["Multimodal natif", "Vidéo", "Audio"],
     "useCases": ["Apps multimédia", "Indexation vidéo"],
     "keywords": ["reka", "multimodal", "vidéo", "audio"],
     "score": 84, "color": "#7B61FF"},

    {"slug": "jamba", "name": "Jamba 1.5", "vendor": "AI21 Labs", "domain": "ai21.com",
     "tagline": "L'hybride Transformer-Mamba",
     "description": "Architecture hybride avec contexte 256k, latence faible, idéal docs longs.",
     "categorySlugs": ["texte", "recherche"], "speedMs": 140, "accuracyPct": 86,
     "costPerPrompt": 0.0008, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["en", "fr", "es", "de", "ar"],
     "features": ["Hybride Mamba", "Contexte 256k", "Open"],
     "useCases": ["Docs longs", "Latence faible"],
     "keywords": ["jamba", "ai21", "mamba", "long contexte"],
     "score": 82, "color": "#7CB7FF"},

    {"slug": "groq", "name": "Groq", "vendor": "Groq", "domain": "groq.com",
     "tagline": "L'inférence à la vitesse de la lumière",
     "description": "Plateforme inférence LPU ultra-rapide pour Llama, Mixtral, Gemma. 500+ tokens/sec.",
     "categorySlugs": ["texte", "code"], "speedMs": 50, "accuracyPct": 88,
     "costPerPrompt": 0.0003, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["en", "fr"],
     "features": ["LPU", "500 t/s", "Multi-modèles"],
     "useCases": ["Apps temps-réel", "Streaming chat"],
     "keywords": ["groq", "rapide", "lpu", "inférence", "fast"],
     "score": 88, "color": "#F55036"},

    {"slug": "together", "name": "Together AI", "vendor": "Together", "domain": "together.ai",
     "tagline": "Le hub d'inférence open-source",
     "description": "Accès API à 200+ modèles open-source (Llama, Mixtral, DeepSeek, Qwen) à prix cassé.",
     "categorySlugs": ["texte", "image", "code"], "speedMs": 200, "accuracyPct": 87,
     "costPerPrompt": 0.0005, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["en", "fr"],
     "features": ["200+ modèles", "Fine-tuning", "Dedicated"],
     "useCases": ["Comparer modèles open", "Fine-tuning"],
     "keywords": ["together", "open", "hub", "api"],
     "score": 85, "color": "#0F6FFF"},

    {"slug": "fireworks", "name": "Fireworks AI", "vendor": "Fireworks", "domain": "fireworks.ai",
     "tagline": "L'inférence pro pour models open",
     "description": "Inférence rapide et fine-tuning pour modèles open avec tarifs entreprise.",
     "categorySlugs": ["texte", "code", "image"], "speedMs": 180, "accuracyPct": 87,
     "costPerPrompt": 0.0006, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["en", "fr"],
     "features": ["Fine-tune", "FireFunction", "Multi-LoRA"],
     "useCases": ["Production scale", "Fine-tuning custom"],
     "keywords": ["fireworks", "inférence", "open", "fine-tune"],
     "score": 84, "color": "#FF5722"},

    # ===== Image generation =====
    {"slug": "nano-banana", "name": "Nano Banana 2", "vendor": "Google", "domain": "deepmind.google",
     "tagline": "Le modèle image Gemini hyper-fidèle",
     "description": "Modèle image Gemini 2.0 dernière génération, suit le prompt à la lettre, édition par phrase.",
     "categorySlugs": ["image"], "speedMs": 4000, "accuracyPct": 95,
     "costPerPrompt": 0.03, "monthlyPrice": 19.99, "freeTier": True,
     "languages": ["fr", "en", "es", "de", "ja"],
     "features": ["Édition par phrase", "Texte net", "Multi-tour"],
     "useCases": ["Visuels marketing", "Édition image", "Iter rapide"],
     "keywords": ["nano", "banana", "gemini", "image", "google"],
     "score": 92, "color": "#4285F4"},

    {"slug": "imagen", "name": "Imagen 3", "vendor": "Google DeepMind", "domain": "deepmind.google",
     "tagline": "Le photoréalisme Google",
     "description": "Modèle image DeepMind ultra-photoréaliste, intégré à Vertex AI et Gemini.",
     "categorySlugs": ["image"], "speedMs": 5000, "accuracyPct": 92,
     "costPerPrompt": 0.04, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["en", "fr"],
     "features": ["Photoréalisme", "Vertex AI", "SynthID"],
     "useCases": ["Photo produit", "Mode", "Pub"],
     "keywords": ["imagen", "google", "deepmind", "photo"],
     "score": 90, "color": "#4285F4"},

    {"slug": "firefly", "name": "Adobe Firefly", "vendor": "Adobe", "domain": "adobe.com",
     "tagline": "L'IA image safe pour pro",
     "description": "Modèle Adobe entraîné sur contenus licenciés, intégré Photoshop/Illustrator.",
     "categorySlugs": ["image"], "speedMs": 6000, "accuracyPct": 87,
     "costPerPrompt": 0.05, "monthlyPrice": 9.99, "freeTier": True,
     "languages": ["fr", "en", "es", "de", "ja"],
     "features": ["Commercial-safe", "Photoshop", "Vector"],
     "useCases": ["Brand visuels", "Édition Photoshop"],
     "keywords": ["firefly", "adobe", "photoshop", "commercial"],
     "score": 86, "color": "#FA0F00"},

    {"slug": "reve", "name": "Reve", "vendor": "Reve", "domain": "reve.art",
     "tagline": "L'image artistique nouvelle vague",
     "description": "Modèle image au style cinématographique distinctif, prompts naturels.",
     "categorySlugs": ["image"], "speedMs": 5500, "accuracyPct": 89,
     "costPerPrompt": 0.025, "monthlyPrice": 10.0, "freeTier": True,
     "languages": ["en"],
     "features": ["Style cinéma", "Prompt naturel"],
     "useCases": ["Concept art", "Illustration éditoriale"],
     "keywords": ["reve", "cinéma", "art", "concept"],
     "score": 84, "color": "#000000"},

    {"slug": "magnific", "name": "Magnific", "vendor": "Magnific AI", "domain": "magnific.ai",
     "tagline": "L'upscaler IA qui invente du détail",
     "description": "Upscale d'image hallucinant qui invente du détail réaliste, jusqu'à 16x.",
     "categorySlugs": ["image"], "speedMs": 30000, "accuracyPct": 92,
     "costPerPrompt": 0.05, "monthlyPrice": 39.0, "freeTier": False,
     "languages": ["en"],
     "features": ["Upscale 16x", "Détail créatif", "Style transfer"],
     "useCases": ["Restauration photo", "Print HD", "Upscale stock"],
     "keywords": ["magnific", "upscale", "agrandir", "hd", "détail"],
     "score": 88, "color": "#000000"},

    {"slug": "photoroom", "name": "Photoroom", "vendor": "Photoroom", "domain": "photoroom.com",
     "tagline": "Le studio photo IA des e-commerçants",
     "description": "Détourage, fond IA, retouche pour produits e-commerce — outil français.",
     "categorySlugs": ["image"], "speedMs": 1500, "accuracyPct": 90,
     "costPerPrompt": 0.0, "monthlyPrice": 12.99, "freeTier": True,
     "languages": ["fr", "en", "es", "de", "ja"],
     "features": ["Détourage IA", "Fond produit", "Batch"],
     "useCases": ["Photo produit", "E-commerce", "Marketplace"],
     "keywords": ["photoroom", "détourage", "fond", "e-commerce", "produit", "français"],
     "score": 87, "color": "#FF1744"},

    {"slug": "removebg", "name": "Remove.bg", "vendor": "Kaleido AI", "domain": "remove.bg",
     "tagline": "Le détourage en 1 clic",
     "description": "Suppression de fond IA ultra-précise pour photos produit, portraits, graphismes.",
     "categorySlugs": ["image"], "speedMs": 800, "accuracyPct": 92,
     "costPerPrompt": 0.0, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["fr", "en", "es", "de"],
     "features": ["Détourage", "API", "Batch", "PNG transparent"],
     "useCases": ["Détourage rapide", "Photo produit", "Portrait"],
     "keywords": ["remove", "fond", "détourage", "background", "transparent"],
     "score": 84, "color": "#FF5500"},

    {"slug": "topaz", "name": "Topaz Photo AI", "vendor": "Topaz Labs", "domain": "topazlabs.com",
     "tagline": "L'amélioration photo de référence",
     "description": "Suite IA pour réduction bruit, netteté, upscale et restauration photo.",
     "categorySlugs": ["image"], "speedMs": 8000, "accuracyPct": 91,
     "costPerPrompt": 0.0, "monthlyPrice": 199.0, "freeTier": False,
     "languages": ["en", "fr"],
     "features": ["Denoise", "Sharpen", "Upscale 6x"],
     "useCases": ["Pro photo", "Restauration", "Print"],
     "keywords": ["topaz", "denoise", "netteté", "photo", "pro"],
     "score": 86, "color": "#FF6B00"},

    # ===== Video =====
    {"slug": "veo", "name": "Veo 3", "vendor": "Google DeepMind", "domain": "deepmind.google",
     "tagline": "La vidéo IA cinéma de Google",
     "description": "Modèle vidéo dernière génération avec audio synchronisé et 1080p natif.",
     "categorySlugs": ["video", "audio"], "speedMs": 60000, "accuracyPct": 93,
     "costPerPrompt": 0.6, "monthlyPrice": 19.99, "freeTier": False,
     "languages": ["en", "fr"],
     "features": ["Audio sync", "1080p", "Cinéma"],
     "useCases": ["Pub vidéo", "Court-métrage"],
     "keywords": ["veo", "google", "vidéo", "cinéma", "audio"],
     "score": 91, "color": "#4285F4"},

    {"slug": "hailuo", "name": "Hailuo", "vendor": "MiniMax", "domain": "hailuoai.video",
     "tagline": "La vidéo IA chinoise grand public",
     "description": "Génération vidéo MiniMax avec contrôle caméra, 1080p, audio.",
     "categorySlugs": ["video"], "speedMs": 50000, "accuracyPct": 86,
     "costPerPrompt": 0.3, "monthlyPrice": 10.0, "freeTier": True,
     "languages": ["zh", "en", "fr"],
     "features": ["Camera control", "Audio", "1080p"],
     "useCases": ["Clip", "Réseaux sociaux"],
     "keywords": ["hailuo", "minimax", "vidéo", "chinois"],
     "score": 84, "color": "#FF4444"},

    {"slug": "pixverse", "name": "Pixverse", "vendor": "Pixverse", "domain": "pixverse.ai",
     "tagline": "La vidéo IA créative anime/3D",
     "description": "Style anime, 3D et photoréaliste, contrôle caméra fin, lipsync.",
     "categorySlugs": ["video"], "speedMs": 45000, "accuracyPct": 84,
     "costPerPrompt": 0.25, "monthlyPrice": 10.0, "freeTier": True,
     "languages": ["en", "zh"],
     "features": ["Anime", "Lipsync", "Camera"],
     "useCases": ["Anime", "Animation 3D", "Storytelling"],
     "keywords": ["pixverse", "anime", "vidéo", "3d"],
     "score": 81, "color": "#7B5BFF"},

    {"slug": "genmo", "name": "Genmo Mochi", "vendor": "Genmo", "domain": "genmo.ai",
     "tagline": "La vidéo open-source de référence",
     "description": "Modèle vidéo open-weight Apache 2.0, 480p à 720p, Mochi 1.",
     "categorySlugs": ["video"], "speedMs": 90000, "accuracyPct": 80,
     "costPerPrompt": 0.0, "monthlyPrice": 10.0, "freeTier": True,
     "languages": ["en"],
     "features": ["Open-weight", "Apache 2.0", "Self-host"],
     "useCases": ["Self-hosting vidéo", "Recherche"],
     "keywords": ["genmo", "mochi", "open", "vidéo"],
     "score": 79, "color": "#000000"},

    {"slug": "ltx", "name": "LTX Studio", "vendor": "Lightricks", "domain": "ltx.studio",
     "tagline": "Le studio vidéo IA tout-en-un",
     "description": "Storyboard, cast, scènes IA pour pré-production vidéo cinéma.",
     "categorySlugs": ["video"], "speedMs": 30000, "accuracyPct": 83,
     "costPerPrompt": 0.0, "monthlyPrice": 35.0, "freeTier": True,
     "languages": ["en", "fr"],
     "features": ["Storyboard", "Cast IA", "Scènes"],
     "useCases": ["Pré-production", "Pitch vidéo"],
     "keywords": ["ltx", "lightricks", "vidéo", "studio"],
     "score": 82, "color": "#1F1F1F"},

    {"slug": "synthesia", "name": "Synthesia", "vendor": "Synthesia", "domain": "synthesia.io",
     "tagline": "Les avatars vidéo entreprise",
     "description": "Plateforme avatar vidéo n°1 entreprise, 140+ langues, marque blanche.",
     "categorySlugs": ["video", "audio"], "speedMs": 30000, "accuracyPct": 90,
     "costPerPrompt": 0.0, "monthlyPrice": 22.0, "freeTier": True,
     "languages": ["fr", "en", "es", "de", "ja", "zh", "ar"],
     "features": ["140+ langues", "Avatar custom", "Templates"],
     "useCases": ["L&D", "Vidéos internes", "Onboarding"],
     "keywords": ["synthesia", "avatar", "formation", "entreprise", "tuto"],
     "score": 87, "color": "#32A8E8"},

    {"slug": "did", "name": "D-ID", "vendor": "D-ID", "domain": "d-id.com",
     "tagline": "Avatars parlants temps-réel",
     "description": "Photos animées en avatars parlants avec lipsync de qualité, API solide.",
     "categorySlugs": ["video", "audio"], "speedMs": 12000, "accuracyPct": 86,
     "costPerPrompt": 0.5, "monthlyPrice": 6.0, "freeTier": True,
     "languages": ["fr", "en", "es", "de"],
     "features": ["Lipsync", "Photo-to-video", "Real-time"],
     "useCases": ["Vidéo perso", "Avatar SAV"],
     "keywords": ["d-id", "avatar", "lipsync", "photo"],
     "score": 81, "color": "#FF7C00"},

    # ===== Audio =====
    {"slug": "cartesia", "name": "Cartesia Sonic", "vendor": "Cartesia", "domain": "cartesia.ai",
     "tagline": "La voix synthétique ultra-rapide",
     "description": "TTS state-machine, 90ms latence, qualité naturelle, idéal voicebot temps-réel.",
     "categorySlugs": ["audio"], "speedMs": 90, "accuracyPct": 92,
     "costPerPrompt": 0.05, "monthlyPrice": 5.0, "freeTier": True,
     "languages": ["fr", "en", "es", "de", "ja"],
     "features": ["90ms latence", "State-space", "Voicebot"],
     "useCases": ["Voicebot temps-réel", "Streaming TTS"],
     "keywords": ["cartesia", "sonic", "voix", "rapide", "voicebot"],
     "score": 88, "color": "#000000"},

    {"slug": "playht", "name": "Play.ht", "vendor": "Play.ht", "domain": "play.ht",
     "tagline": "Voix synthétiques studio",
     "description": "Plus de 800 voix dans 130+ langues, clonage et émotions.",
     "categorySlugs": ["audio"], "speedMs": 1500, "accuracyPct": 90,
     "costPerPrompt": 0.05, "monthlyPrice": 31.2, "freeTier": True,
     "languages": ["fr", "en", "es", "de", "it", "ja", "zh"],
     "features": ["800 voix", "Clonage", "Émotions"],
     "useCases": ["Podcast", "Audiolivre", "Pub radio"],
     "keywords": ["play", "ht", "voix", "podcast", "audiolivre"],
     "score": 84, "color": "#39EBA9"},

    {"slug": "resemble", "name": "Resemble AI", "vendor": "Resemble", "domain": "resemble.ai",
     "tagline": "Le clonage de voix entreprise",
     "description": "Clonage de voix temps-réel haute fidélité avec garde-fous deepfake.",
     "categorySlugs": ["audio"], "speedMs": 800, "accuracyPct": 91,
     "costPerPrompt": 0.04, "monthlyPrice": 19.0, "freeTier": True,
     "languages": ["fr", "en", "es", "de"],
     "features": ["Voice cloning", "Anti-deepfake", "Real-time"],
     "useCases": ["Doublage", "SAV vocal", "Démo produit"],
     "keywords": ["resemble", "clonage", "voix", "deepfake"],
     "score": 84, "color": "#272727"},

    {"slug": "stable-audio", "name": "Stable Audio 2", "vendor": "Stability AI", "domain": "stability.ai",
     "tagline": "Musique IA open-source",
     "description": "Génération musique 3 minutes haute qualité, modèle open.",
     "categorySlugs": ["audio"], "speedMs": 25000, "accuracyPct": 84,
     "costPerPrompt": 0.0, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["en"],
     "features": ["3 min HQ", "Open-weight", "Audio-to-audio"],
     "useCases": ["Musique de fond", "Sound design"],
     "keywords": ["stable", "audio", "musique", "open"],
     "score": 81, "color": "#7B61FF"},

    {"slug": "assemblyai", "name": "AssemblyAI", "vendor": "AssemblyAI", "domain": "assemblyai.com",
     "tagline": "L'API speech-to-text pro",
     "description": "Transcription multilingue, diarisation, summarisation, redaction PII.",
     "categorySlugs": ["audio"], "speedMs": 2000, "accuracyPct": 93,
     "costPerPrompt": 0.005, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["fr", "en", "es", "de", "it", "ja", "zh"],
     "features": ["Diarisation", "Summary", "PII redact"],
     "useCases": ["Transcription scale", "Compliance"],
     "keywords": ["assemblyai", "transcription", "diarisation", "api"],
     "score": 88, "color": "#1A53E0"},

    {"slug": "deepgram", "name": "Deepgram", "vendor": "Deepgram", "domain": "deepgram.com",
     "tagline": "Le STT temps-réel le plus rapide",
     "description": "API STT temps-réel sub-300ms, idéal voicebot et live captioning.",
     "categorySlugs": ["audio"], "speedMs": 300, "accuracyPct": 91,
     "costPerPrompt": 0.004, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["fr", "en", "es", "de", "ja", "ko"],
     "features": ["Streaming", "Sub-300ms", "Custom models"],
     "useCases": ["Voicebot", "Live captioning"],
     "keywords": ["deepgram", "stt", "temps réel", "streaming"],
     "score": 87, "color": "#13EF93"},

    # ===== Code =====
    {"slug": "tabnine", "name": "Tabnine", "vendor": "Tabnine", "domain": "tabnine.com",
     "tagline": "L'autocomplétion code privée",
     "description": "Code completion privé, on-prem possible, modèles entraînés sur ton repo.",
     "categorySlugs": ["code"], "speedMs": 100, "accuracyPct": 86,
     "costPerPrompt": 0.0, "monthlyPrice": 12.0, "freeTier": True,
     "languages": ["en"],
     "features": ["On-prem", "Private", "Custom-trained"],
     "useCases": ["Banque", "Industrie", "Gouv"],
     "keywords": ["tabnine", "code", "privé", "on-prem"],
     "score": 83, "color": "#6E40C9"},

    {"slug": "aider", "name": "Aider", "vendor": "Aider", "domain": "aider.chat",
     "tagline": "Le pair-programmeur en CLI",
     "description": "Open-source CLI tool qui édite ton repo via LLM (GPT, Claude, Gemini, DeepSeek).",
     "categorySlugs": ["code"], "speedMs": 3000, "accuracyPct": 87,
     "costPerPrompt": 0.0, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["en"],
     "features": ["CLI", "Multi-LLM", "Git native"],
     "useCases": ["Refactor batch", "Patch automatique"],
     "keywords": ["aider", "cli", "git", "code", "open"],
     "score": 84, "color": "#000000"},

    {"slug": "continue", "name": "Continue", "vendor": "Continue", "domain": "continue.dev",
     "tagline": "L'IDE plugin open-source",
     "description": "Plugin VS Code/JetBrains open-source pour brancher n'importe quel LLM.",
     "categorySlugs": ["code"], "speedMs": 200, "accuracyPct": 84,
     "costPerPrompt": 0.0, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["en"],
     "features": ["Open-source", "Multi-LLM", "Custom"],
     "useCases": ["Self-hosted Copilot"],
     "keywords": ["continue", "ide", "open", "vscode"],
     "score": 81, "color": "#000000"},

    {"slug": "devin", "name": "Devin", "vendor": "Cognition", "domain": "cognition.ai",
     "tagline": "L'ingénieur logiciel autonome",
     "description": "Agent IA autonome qui code, débogue et déploie, exécution sandbox.",
     "categorySlugs": ["code", "agent"], "speedMs": 8000, "accuracyPct": 80,
     "costPerPrompt": 0.0, "monthlyPrice": 500.0, "freeTier": False,
     "languages": ["en"],
     "features": ["Agent autonome", "Sandbox", "Plan-execute"],
     "useCases": ["Tâches longues", "Refactor massif"],
     "keywords": ["devin", "cognition", "agent", "ingénieur"],
     "score": 83, "color": "#000000"},

    {"slug": "supermaven", "name": "Supermaven", "vendor": "Supermaven", "domain": "supermaven.com",
     "tagline": "L'autocomplétion contexte 1M",
     "description": "Autocomplétion code la plus rapide avec contexte 1M tokens.",
     "categorySlugs": ["code"], "speedMs": 80, "accuracyPct": 88,
     "costPerPrompt": 0.0, "monthlyPrice": 10.0, "freeTier": True,
     "languages": ["en"],
     "features": ["1M contexte", "Ultra-rapide", "VS Code"],
     "useCases": ["Coder vite", "Gros monorepo"],
     "keywords": ["supermaven", "code", "rapide", "contexte"],
     "score": 86, "color": "#000000"},

    {"slug": "codeium", "name": "Codeium", "vendor": "Codeium", "domain": "codeium.com",
     "tagline": "L'autocomplétion gratuite illimitée",
     "description": "Concurrent gratuit de Copilot, 70+ langages, on-prem possible entreprise.",
     "categorySlugs": ["code"], "speedMs": 120, "accuracyPct": 85,
     "costPerPrompt": 0.0, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["en"],
     "features": ["Gratuit illimité", "70+ langages", "On-prem"],
     "useCases": ["Coder gratos", "Self-hosted"],
     "keywords": ["codeium", "code", "gratuit", "copilot"],
     "score": 84, "color": "#09B6A2"},

    {"slug": "lovable", "name": "Lovable", "vendor": "Lovable", "domain": "lovable.dev",
     "tagline": "Du prompt à l'app full-stack",
     "description": "Build apps full-stack avec Supabase intégré, déploiement instantané.",
     "categorySlugs": ["code", "agent"], "speedMs": 7000, "accuracyPct": 84,
     "costPerPrompt": 0.0, "monthlyPrice": 20.0, "freeTier": True,
     "languages": ["en", "fr"],
     "features": ["Full-stack", "Supabase", "Deploy"],
     "useCases": ["MVP rapide", "Apps SaaS"],
     "keywords": ["lovable", "app", "fullstack", "saas"],
     "score": 85, "color": "#FF4444"},

    {"slug": "softgen", "name": "Softgen", "vendor": "Softgen", "domain": "softgen.ai",
     "tagline": "Apps SaaS depuis un brief",
     "description": "Génère des SaaS complets avec auth, paiement et BDD à partir d'un brief.",
     "categorySlugs": ["code", "agent"], "speedMs": 6000, "accuracyPct": 81,
     "costPerPrompt": 0.0, "monthlyPrice": 19.0, "freeTier": True,
     "languages": ["en"],
     "features": ["Auth + DB", "Stripe", "Deploy"],
     "useCases": ["MVP SaaS", "Side project"],
     "keywords": ["softgen", "saas", "app", "build"],
     "score": 79, "color": "#000000"},

    # ===== Productivity (LLM-based) =====
    {"slug": "copilot-365", "name": "Microsoft Copilot", "vendor": "Microsoft", "domain": "microsoft.com",
     "tagline": "L'IA dans Office 365",
     "description": "Copilot dans Word, Excel, Outlook, Teams, PowerPoint pour entreprise.",
     "categorySlugs": ["productivite", "texte"], "speedMs": 200, "accuracyPct": 88,
     "costPerPrompt": 0.0, "monthlyPrice": 30.0, "freeTier": False,
     "languages": ["fr", "en", "es", "de", "ja"],
     "features": ["Office 365", "Teams", "M365 Chat"],
     "useCases": ["Email", "Excel formules", "Docs Word"],
     "keywords": ["copilot", "microsoft", "office", "word", "excel", "teams"],
     "score": 87, "color": "#0078D4"},

    {"slug": "gemini-workspace", "name": "Gemini for Workspace", "vendor": "Google", "domain": "workspace.google.com",
     "tagline": "L'IA dans Gmail, Docs, Sheets",
     "description": "Gemini intégré à Workspace pour brouillons, résumés, analyse data.",
     "categorySlugs": ["productivite", "texte"], "speedMs": 180, "accuracyPct": 87,
     "costPerPrompt": 0.0, "monthlyPrice": 24.0, "freeTier": False,
     "languages": ["fr", "en", "es", "de", "ja"],
     "features": ["Gmail", "Docs", "Sheets"],
     "useCases": ["Email", "Sheets analyse", "Docs rédaction"],
     "keywords": ["gemini", "workspace", "google", "gmail", "docs"],
     "score": 86, "color": "#4285F4"},

    {"slug": "mem", "name": "Mem", "vendor": "Mem Labs", "domain": "mem.ai",
     "tagline": "Le second cerveau IA",
     "description": "Notes auto-organisées par IA, recherche sémantique, chat avec tes notes.",
     "categorySlugs": ["productivite", "texte"], "speedMs": 300, "accuracyPct": 84,
     "costPerPrompt": 0.0, "monthlyPrice": 14.99, "freeTier": True,
     "languages": ["en", "fr"],
     "features": ["Auto-tag", "Chat notes", "Smart write"],
     "useCases": ["Notes perso", "Knowledge mgmt"],
     "keywords": ["mem", "notes", "second cerveau", "knowledge"],
     "score": 81, "color": "#000000"},

    {"slug": "granola", "name": "Granola", "vendor": "Granola", "domain": "granola.ai",
     "tagline": "Notes de réunion sans bot intrusif",
     "description": "Notes de réunion IA enrichies sans bot dans la call, intégré à Notion/Slack.",
     "categorySlugs": ["productivite", "audio"], "speedMs": 500, "accuracyPct": 89,
     "costPerPrompt": 0.0, "monthlyPrice": 18.0, "freeTier": True,
     "languages": ["en", "fr"],
     "features": ["No bot", "Templates", "Integrations"],
     "useCases": ["Notes réunion", "Suivi action"],
     "keywords": ["granola", "réunion", "notes", "meeting"],
     "score": 84, "color": "#000000"},

    {"slug": "spell", "name": "Spell", "vendor": "Spell", "domain": "spell.so",
     "tagline": "L'écrivain IA en parallèle",
     "description": "Lance plusieurs prompts ChatGPT en parallèle pour comparer rapidement.",
     "categorySlugs": ["texte", "productivite"], "speedMs": 800, "accuracyPct": 84,
     "costPerPrompt": 0.001, "monthlyPrice": 12.0, "freeTier": True,
     "languages": ["fr", "en"],
     "features": ["Parallel prompts", "Templates", "Bulk"],
     "useCases": ["A/B test prompts", "Volume rédaction"],
     "keywords": ["spell", "parallèle", "rédaction", "bulk"],
     "score": 79, "color": "#7B5BFF"},

    # ===== Research =====
    {"slug": "phind", "name": "Phind", "vendor": "Phind", "domain": "phind.com",
     "tagline": "Le moteur de recherche dev",
     "description": "Recherche IA spécialisée pour développeurs avec sources techniques.",
     "categorySlugs": ["recherche", "code"], "speedMs": 1500, "accuracyPct": 88,
     "costPerPrompt": 0.001, "monthlyPrice": 20.0, "freeTier": True,
     "languages": ["en"],
     "features": ["Citations dev", "Code blocks", "VS Code"],
     "useCases": ["Recherche tech", "Stack overflow killer"],
     "keywords": ["phind", "recherche", "dev", "code", "stackoverflow"],
     "score": 85, "color": "#3B82F6"},

    {"slug": "consensus", "name": "Consensus", "vendor": "Consensus", "domain": "consensus.app",
     "tagline": "Le moteur de recherche académique IA",
     "description": "Trouve des consensus scientifiques basés sur 200M+ papers vérifiés.",
     "categorySlugs": ["recherche"], "speedMs": 2500, "accuracyPct": 90,
     "costPerPrompt": 0.0, "monthlyPrice": 8.99, "freeTier": True,
     "languages": ["en"],
     "features": ["200M papers", "Consensus meter", "Citations"],
     "useCases": ["Recherche scientifique", "Mémoire"],
     "keywords": ["consensus", "scientifique", "papers", "académique"],
     "score": 86, "color": "#3B82F6"},

    {"slug": "elicit", "name": "Elicit", "vendor": "Elicit", "domain": "elicit.com",
     "tagline": "L'assistant chercheur",
     "description": "Synthèse littérature scientifique, extraction systématique de papers.",
     "categorySlugs": ["recherche"], "speedMs": 3000, "accuracyPct": 89,
     "costPerPrompt": 0.0, "monthlyPrice": 12.0, "freeTier": True,
     "languages": ["en"],
     "features": ["Systematic review", "Extract data", "PRISMA"],
     "useCases": ["Thèse", "Méta-analyse"],
     "keywords": ["elicit", "scientifique", "thèse", "papers"],
     "score": 84, "color": "#000000"},

    {"slug": "scite", "name": "Scite Assistant", "vendor": "Scite", "domain": "scite.ai",
     "tagline": "Citations validées en contexte",
     "description": "Distingue citations soutenant ou contredisant un papier scientifique.",
     "categorySlugs": ["recherche"], "speedMs": 2000, "accuracyPct": 87,
     "costPerPrompt": 0.0, "monthlyPrice": 20.0, "freeTier": True,
     "languages": ["en"],
     "features": ["Smart citations", "Critical reading"],
     "useCases": ["Validation source", "Recherche critique"],
     "keywords": ["scite", "citation", "scientifique", "critique"],
     "score": 82, "color": "#1F1F1F"},

    # ===== Agents =====
    {"slug": "agentgpt", "name": "AgentGPT", "vendor": "Reworkd", "domain": "agentgpt.reworkd.ai",
     "tagline": "L'agent autonome dans le navigateur",
     "description": "Lance un agent autonome qui décompose un objectif en tâches.",
     "categorySlugs": ["agent"], "speedMs": 5000, "accuracyPct": 78,
     "costPerPrompt": 0.0, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["en", "fr"],
     "features": ["Auto-decompose", "Web access", "Open-source"],
     "useCases": ["Brainstorming", "Recherche guidée"],
     "keywords": ["agentgpt", "agent", "autonome", "open"],
     "score": 76, "color": "#000000"},

    {"slug": "multion", "name": "MultiOn", "vendor": "MultiOn", "domain": "multion.ai",
     "tagline": "L'agent navigateur",
     "description": "Agent IA qui navigue le web pour toi (booking, achat, recherche).",
     "categorySlugs": ["agent"], "speedMs": 5000, "accuracyPct": 80,
     "costPerPrompt": 0.0, "monthlyPrice": 19.0, "freeTier": True,
     "languages": ["en"],
     "features": ["Browser agent", "Action API"],
     "useCases": ["Booking auto", "Recherche produit"],
     "keywords": ["multion", "agent", "navigateur", "browser"],
     "score": 80, "color": "#000000"},

    {"slug": "relevance", "name": "Relevance AI", "vendor": "Relevance", "domain": "relevanceai.com",
     "tagline": "La force de vente IA",
     "description": "Construis des équipes d'agents IA pour vente, support, marketing.",
     "categorySlugs": ["agent"], "speedMs": 3000, "accuracyPct": 85,
     "costPerPrompt": 0.0, "monthlyPrice": 99.0, "freeTier": True,
     "languages": ["en", "fr"],
     "features": ["Agent teams", "CRM-ready", "Tools"],
     "useCases": ["Sales agent", "Support agent"],
     "keywords": ["relevance", "agent", "vente", "sales"],
     "score": 83, "color": "#FF6E47"},

    {"slug": "lindy", "name": "Lindy", "vendor": "Lindy", "domain": "lindy.ai",
     "tagline": "L'assistant IA personnel d'entreprise",
     "description": "Assistant IA qui prend tes RDV, envoie des emails et gère ton CRM.",
     "categorySlugs": ["agent", "productivite"], "speedMs": 2000, "accuracyPct": 86,
     "costPerPrompt": 0.0, "monthlyPrice": 49.99, "freeTier": True,
     "languages": ["en", "fr"],
     "features": ["Calendar", "Email", "CRM"],
     "useCases": ["Assistant exec", "Suivi commercial"],
     "keywords": ["lindy", "assistant", "rdv", "crm"],
     "score": 84, "color": "#000000"},

    # ===== Data / BI =====
    {"slug": "hex", "name": "Hex Magic", "vendor": "Hex", "domain": "hex.tech",
     "tagline": "Le notebook data avec IA",
     "description": "Notebook data avec IA qui écrit SQL, Python et explique tes datasets.",
     "categorySlugs": ["data", "code"], "speedMs": 1500, "accuracyPct": 88,
     "costPerPrompt": 0.0, "monthlyPrice": 24.0, "freeTier": True,
     "languages": ["en"],
     "features": ["SQL gen", "Python", "Notebook"],
     "useCases": ["Analyse data", "Reporting"],
     "keywords": ["hex", "data", "sql", "notebook", "python"],
     "score": 86, "color": "#5A45FF"},

    {"slug": "fabric-ms", "name": "Microsoft Fabric", "vendor": "Microsoft", "domain": "microsoft.com",
     "tagline": "La data plateforme IA Microsoft",
     "description": "Plateforme analytics unifiée avec Copilot data pour Power BI et Synapse.",
     "categorySlugs": ["data"], "speedMs": 1200, "accuracyPct": 87,
     "costPerPrompt": 0.0, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["fr", "en"],
     "features": ["Power BI", "Synapse", "Copilot data"],
     "useCases": ["BI entreprise", "Data lake"],
     "keywords": ["fabric", "microsoft", "data", "power bi", "bi"],
     "score": 85, "color": "#0078D4"},

    # ===== Bonus LLMs frontières =====
    {"slug": "claude-opus", "name": "Claude Opus 4", "vendor": "Anthropic", "domain": "claude.ai",
     "tagline": "Le modèle de raisonnement Anthropic premium",
     "description": "Le plus puissant des Claude, raisonnement de pointe, contexte 200k+.",
     "categorySlugs": ["texte", "code", "recherche"], "speedMs": 400, "accuracyPct": 96,
     "costPerPrompt": 0.015, "monthlyPrice": 200.0, "freeTier": False,
     "languages": ["fr", "en", "es", "de", "ja"],
     "features": ["Raisonnement profond", "Tool use", "Vision"],
     "useCases": ["Décisions stratégiques", "Audit complexe"],
     "keywords": ["claude", "opus", "anthropic", "raisonnement"],
     "score": 96, "color": "#CC785C"},

    {"slug": "gpt5", "name": "GPT-5.5", "vendor": "OpenAI", "domain": "openai.com",
     "tagline": "Le modèle de référence OpenAI",
     "description": "Mémoire continue, raisonnement natif, multimodal d'origine — état de l'art.",
     "categorySlugs": ["texte", "code", "recherche", "image"], "speedMs": 250, "accuracyPct": 95,
     "costPerPrompt": 0.01, "monthlyPrice": 200.0, "freeTier": False,
     "languages": ["fr", "en", "es", "de", "ja", "zh"],
     "features": ["Mémoire continue", "Raisonnement", "Multimodal"],
     "useCases": ["Tâches complexes", "Pro avancé"],
     "keywords": ["gpt5", "gpt-5", "openai", "raisonnement"],
     "score": 96, "color": "#10A37F"},

    {"slug": "o3", "name": "o3", "vendor": "OpenAI", "domain": "openai.com",
     "tagline": "Le raisonneur frontière",
     "description": "Modèle reasoning OpenAI o3 — chaîne de pensée extrême, math/code/sciences.",
     "categorySlugs": ["texte", "code", "recherche"], "speedMs": 8000, "accuracyPct": 97,
     "costPerPrompt": 0.06, "monthlyPrice": 200.0, "freeTier": False,
     "languages": ["en", "fr"],
     "features": ["Reasoning extrême", "Math", "Code"],
     "useCases": ["Recherche", "Olympiades", "Code complexe"],
     "keywords": ["o3", "openai", "raisonnement", "math"],
     "score": 95, "color": "#10A37F"},

    {"slug": "gemini-25", "name": "Gemini 2.5 Pro", "vendor": "Google", "domain": "gemini.google.com",
     "tagline": "Le multimodal Google haut de gamme",
     "description": "Gemini 2.5 Pro avec contexte 2M, Deep Research, vision native.",
     "categorySlugs": ["texte", "image", "video", "recherche"], "speedMs": 220, "accuracyPct": 94,
     "costPerPrompt": 0.0035, "monthlyPrice": 19.99, "freeTier": True,
     "languages": ["fr", "en", "es", "de", "ja", "zh"],
     "features": ["Contexte 2M", "Vidéo", "Deep Research"],
     "useCases": ["Pro multimodal", "Vidéo analyse"],
     "keywords": ["gemini", "2.5", "pro", "google", "deep research"],
     "score": 94, "color": "#4285F4"},

    {"slug": "deepseek-r1", "name": "DeepSeek R1", "vendor": "DeepSeek", "domain": "deepseek.com",
     "tagline": "Le raisonneur open-source de référence",
     "description": "Reasoning model open-source au niveau o1 mais 30× moins cher.",
     "categorySlugs": ["texte", "code", "recherche"], "speedMs": 600, "accuracyPct": 94,
     "costPerPrompt": 0.0002, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["fr", "en", "zh"],
     "features": ["Reasoning", "Open-weight", "30x moins cher"],
     "useCases": ["Maths", "Code complexe", "Volume"],
     "keywords": ["deepseek", "r1", "raisonnement", "open"],
     "score": 92, "color": "#4D6BFE"},
]
