"""Seed catalog of AI tools for IA Match — expanded to ~50 with real logos via Clearbit."""

CATEGORIES = [
    {"slug": "texte", "name": "Texte & Écriture", "description": "Rédaction, résumé, brainstorming"},
    {"slug": "image", "name": "Image & Design", "description": "Génération et édition d'images"},
    {"slug": "code", "name": "Code & Dev", "description": "Assistants pour développeurs"},
    {"slug": "video", "name": "Vidéo", "description": "Génération et montage vidéo"},
    {"slug": "audio", "name": "Audio & Voix", "description": "Voix synthétique, transcription, musique"},
    {"slug": "productivite", "name": "Productivité", "description": "Documents, tableurs, présentations"},
    {"slug": "recherche", "name": "Recherche & Analyse", "description": "Recherche web, synthèse"},
    {"slug": "agent", "name": "Agents & Automatisation", "description": "Agents autonomes et workflows"},
    {"slug": "data", "name": "Data & Analyse", "description": "Tableurs, BI, analyse de données"},
]


def _logo(domain: str) -> str:
    """Real-brand logo via Clearbit (high quality, square, transparent)."""
    return f"https://logo.clearbit.com/{domain}"


TOOLS = [
    # Conversational / Text generalists
    {"slug": "chatgpt", "name": "ChatGPT", "vendor": "OpenAI", "domain": "openai.com",
     "tagline": "Powered by GPT-5.5 — l'assistant IA n°1 mondial",
     "description": "Assistant conversationnel OpenAI propulsé par GPT-5.5. Rédaction, brainstorming, code, analyse de documents, vision, navigation web et GPTs personnalisés.",
     "categorySlugs": ["texte", "productivite", "recherche", "code"], "speedMs": 180, "accuracyPct": 95,
     "costPerPrompt": 0.002, "monthlyPrice": 20.0, "freeTier": True,
     "languages": ["fr", "en", "es", "de", "it", "ja", "zh"],
     "features": ["GPT-5.5", "Multimodal", "Vision", "Navigation web", "Custom GPTs"],
     "useCases": ["Rédiger un CV", "Résumer un document", "Brainstorming", "Apprendre"],
     "keywords": ["cv", "resume", "résumé", "lettre", "motivation", "email", "écrire", "rédiger", "brainstorm", "gpt5", "gpt-5"],
     "score": 96, "color": "#10A37F"},

    {"slug": "claude", "name": "Claude Sonnet 4", "vendor": "Anthropic", "domain": "claude.ai",
     "tagline": "L'assistant Anthropic équilibré (Free + Pro 20€/mois)",
     "description": "Excellent pour l'analyse de documents longs, le raisonnement nuancé et l'écriture soignée.",
     "categorySlugs": ["texte", "recherche", "productivite"], "speedMs": 220, "accuracyPct": 95,
     "costPerPrompt": 0.003, "monthlyPrice": 20.0, "freeTier": True,
     "languages": ["fr", "en", "es", "de", "it", "ja"],
     "features": ["Contexte 200k", "Artefacts", "Analyse fichiers"],
     "useCases": ["Analyser un long PDF", "Écrire un essai", "Audit juridique"],
     "keywords": ["analyse", "long", "document", "pdf", "rapport", "essai", "juridique", "synthèse", "rédaction"],
     "score": 95, "color": "#CC785C"},

    {"slug": "gemini", "name": "Gemini", "vendor": "Google", "domain": "gemini.google.com",
     "tagline": "L'assistant Google grand public (Free + Advanced 19,99€)",
     "description": "Multimodal natif, intégré à Gmail, Docs et la recherche Google.",
     "categorySlugs": ["texte", "productivite", "recherche", "image"], "speedMs": 160, "accuracyPct": 90,
     "costPerPrompt": 0.0015, "monthlyPrice": 19.99, "freeTier": True,
     "languages": ["fr", "en", "es", "de", "ja", "zh", "ko"],
     "features": ["Multimodal", "Workspace", "Recherche temps réel"],
     "useCases": ["Recherche web", "Email", "Docs Google"],
     "keywords": ["recherche", "google", "email", "gmail", "docs", "tableur", "actualité", "web"],
     "score": 90, "color": "#4285F4"},

    {"slug": "mistral", "name": "Le Chat", "vendor": "Mistral AI", "domain": "mistral.ai",
     "tagline": "Le champion européen open-weight",
     "description": "Modèle français performant, rapide, avec versions open-weight pour déploiement custom.",
     "categorySlugs": ["texte", "code", "productivite"], "speedMs": 130, "accuracyPct": 88,
     "costPerPrompt": 0.001, "monthlyPrice": 14.99, "freeTier": True,
     "languages": ["fr", "en", "es", "de", "it"],
     "features": ["Open-weight", "Code Mistral", "API"],
     "useCases": ["Apps européennes", "Code", "Souveraineté data"],
     "keywords": ["français", "europe", "souveraineté", "open", "mistral", "le chat"],
     "score": 87, "color": "#FA520F"},

    {"slug": "grok", "name": "Grok", "vendor": "xAI", "domain": "x.ai",
     "tagline": "L'IA temps-réel branchée sur X",
     "description": "Réponses temps-réel avec accès flux X, ton décalé, mode raisonnement.",
     "categorySlugs": ["texte", "recherche"], "speedMs": 200, "accuracyPct": 86,
     "costPerPrompt": 0.002, "monthlyPrice": 16.0, "freeTier": True,
     "languages": ["en", "fr", "es"],
     "features": ["Temps réel X", "Mode Think", "Vision"],
     "useCases": ["Veille X/Twitter", "Réactivité actualité"],
     "keywords": ["temps réel", "twitter", "x", "actualité", "veille"],
     "score": 82, "color": "#000000"},

    {"slug": "deepseek", "name": "DeepSeek V3", "vendor": "DeepSeek", "domain": "deepseek.com",
     "tagline": "Le LLM open-weight chinois ultra abordable",
     "tagline": "Le raisonneur open-source ultra-économique",
     "description": "Modèle chinois open-source au rapport qualité/prix exceptionnel, fort en code et maths.",
     "categorySlugs": ["texte", "code", "data"], "speedMs": 240, "accuracyPct": 89,
     "costPerPrompt": 0.0002, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["fr", "en", "zh"],
     "features": ["Open-source", "Reasoning R1", "Pas cher"],
     "useCases": ["Maths complexes", "Code", "Volume API"],
     "keywords": ["maths", "math", "raisonnement", "code", "open", "gratuit", "chinois"],
     "score": 88, "color": "#4D6BFE"},

    {"slug": "perplexity", "name": "Perplexity", "vendor": "Perplexity AI", "domain": "perplexity.ai",
     "tagline": "Le moteur de recherche IA avec sources",
     "description": "Recherche web en temps réel avec citations vérifiables.",
     "categorySlugs": ["recherche"], "speedMs": 140, "accuracyPct": 88,
     "costPerPrompt": 0.001, "monthlyPrice": 20.0, "freeTier": True,
     "languages": ["fr", "en", "es", "de"],
     "features": ["Citations", "Recherche temps réel", "Pro Search"],
     "useCases": ["Recherche académique", "Veille", "Fact-checking"],
     "keywords": ["recherche", "veille", "actualité", "source", "citation", "fact", "article", "web"],
     "score": 89, "color": "#20B8CD"},

    {"slug": "you-com", "name": "You.com", "vendor": "You.com", "domain": "you.com",
     "tagline": "Le moteur multi-modèle tout-en-un",
     "description": "Recherche IA avec accès Claude, GPT, Gemini en un seul endroit.",
     "categorySlugs": ["recherche", "texte"], "speedMs": 200, "accuracyPct": 86,
     "costPerPrompt": 0.001, "monthlyPrice": 15.0, "freeTier": True,
     "languages": ["fr", "en", "es"],
     "features": ["Multi-modèle", "Agents", "Apps"],
     "useCases": ["Recherche avancée", "Veille techno"],
     "keywords": ["recherche", "veille", "multi", "agent", "moteur"],
     "score": 80, "color": "#7C3AED"},

    # Image generation
    {"slug": "midjourney", "name": "Midjourney", "vendor": "Midjourney", "domain": "midjourney.com",
     "tagline": "Le maître de l'image artistique",
     "description": "Génération d'images d'une qualité artistique exceptionnelle.",
     "categorySlugs": ["image"], "speedMs": 30000, "accuracyPct": 96,
     "costPerPrompt": 0.04, "monthlyPrice": 10.0, "freeTier": False,
     "languages": ["en"],
     "features": ["Style references", "Upscale", "V6"],
     "useCases": ["Illustration", "Concept art", "Visuel marketing"],
     "keywords": ["image", "illustration", "art", "dessin", "visuel", "design", "logo", "affiche", "poster"],
     "score": 93, "color": "#000000"},

    {"slug": "dalle", "name": "DALL-E 3", "vendor": "OpenAI", "domain": "openai.com",
     "tagline": "L'image fidèle au prompt",
     "description": "Génération d'images intégrée à ChatGPT, suit fidèlement les instructions.",
     "categorySlugs": ["image"], "speedMs": 12000, "accuracyPct": 88,
     "costPerPrompt": 0.04, "monthlyPrice": 20.0, "freeTier": False,
     "languages": ["fr", "en", "es"],
     "features": ["Intégré ChatGPT", "Édition d'image"],
     "useCases": ["Visuel rapide", "Illustration concept"],
     "keywords": ["image", "illustration", "dessin", "visuel", "concept"],
     "score": 86, "color": "#FF6B35"},

    {"slug": "stable-diffusion", "name": "Stable Diffusion", "vendor": "Stability AI", "domain": "stability.ai",
     "tagline": "Open-source, contrôle total",
     "description": "Modèle open-source customisable et exécutable en local.",
     "categorySlugs": ["image"], "speedMs": 8000, "accuracyPct": 84,
     "costPerPrompt": 0.0, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["en"],
     "features": ["Open-source", "Local", "ControlNet"],
     "useCases": ["Pipeline custom", "Volume élevé"],
     "keywords": ["image", "open", "gratuit", "local", "self-hosted"],
     "score": 82, "color": "#7B61FF"},

    {"slug": "flux", "name": "Flux", "vendor": "Black Forest Labs", "domain": "blackforestlabs.ai",
     "tagline": "Le nouveau standard du photoréalisme",
     "description": "Modèle open d'image au photoréalisme bluffant, créé par les ex-Stable Diffusion.",
     "categorySlugs": ["image"], "speedMs": 6000, "accuracyPct": 93,
     "costPerPrompt": 0.025, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["en"],
     "features": ["Photoréalisme", "Open-weight", "Fast variant"],
     "useCases": ["Photo produit", "Mode", "Portraits"],
     "keywords": ["photo", "photoréalisme", "réaliste", "portrait", "produit"],
     "score": 91, "color": "#000000"},

    {"slug": "ideogram", "name": "Ideogram", "vendor": "Ideogram", "domain": "ideogram.ai",
     "tagline": "L'IA image qui sait écrire",
     "description": "Génération d'images avec texte intégré net et lisible — affiches, logos.",
     "categorySlugs": ["image"], "speedMs": 7000, "accuracyPct": 87,
     "costPerPrompt": 0.02, "monthlyPrice": 8.0, "freeTier": True,
     "languages": ["en"],
     "features": ["Texte dans l'image", "Magic Prompt", "Tile"],
     "useCases": ["Affiches typographiques", "Logos", "Posters"],
     "keywords": ["affiche", "poster", "logo", "texte", "typographie"],
     "score": 84, "color": "#FF4F8B"},

    {"slug": "leonardo", "name": "Leonardo.AI", "vendor": "Leonardo", "domain": "leonardo.ai",
     "tagline": "Le studio image pour créatifs",
     "description": "Génération + retouche tout-en-un avec modèles fine-tunés et Canvas.",
     "categorySlugs": ["image"], "speedMs": 6500, "accuracyPct": 86,
     "costPerPrompt": 0.015, "monthlyPrice": 12.0, "freeTier": True,
     "languages": ["en"],
     "features": ["Canvas", "Fine-tunes", "Real-time"],
     "useCases": ["Concept jeux vidéo", "Asset 3D", "Brand visuels"],
     "keywords": ["jeu", "concept", "asset", "brand", "personnage"],
     "score": 83, "color": "#A855F7"},

    {"slug": "recraft", "name": "Recraft", "vendor": "Recraft", "domain": "recraft.ai",
     "tagline": "Le compagnon des designers",
     "description": "Vector + raster avec contrôle de style fin pour usages design pro.",
     "categorySlugs": ["image"], "speedMs": 8000, "accuracyPct": 88,
     "costPerPrompt": 0.025, "monthlyPrice": 12.0, "freeTier": True,
     "languages": ["en"],
     "features": ["Vector", "Brand kit", "Style consistency"],
     "useCases": ["Icônes", "Pictogrammes", "Identité visuelle"],
     "keywords": ["vector", "vectoriel", "icône", "icone", "brand", "identité"],
     "score": 85, "color": "#000000"},

    # Code
    {"slug": "github-copilot", "name": "GitHub Copilot", "vendor": "GitHub", "domain": "github.com",
     "tagline": "Le pair-programmeur dans ton IDE",
     "description": "Suggestions de code en temps réel dans VS Code, JetBrains et autres IDEs.",
     "categorySlugs": ["code"], "speedMs": 80, "accuracyPct": 89,
     "costPerPrompt": 0.0, "monthlyPrice": 10.0, "freeTier": False,
     "languages": ["en"],
     "features": ["IDE plugin", "Chat", "Workspace"],
     "useCases": ["Coder plus vite", "Auto-complétion"],
     "keywords": ["code", "coder", "programmation", "développer", "ide", "vscode", "fonction"],
     "score": 91, "color": "#181717"},

    {"slug": "cursor", "name": "Cursor", "vendor": "Cursor", "domain": "cursor.com",
     "tagline": "L'IDE pensé pour l'IA",
     "description": "Éditeur de code avec IA native, refactoring multi-fichiers et agent autonome.",
     "categorySlugs": ["code", "agent"], "speedMs": 120, "accuracyPct": 92,
     "costPerPrompt": 0.0, "monthlyPrice": 20.0, "freeTier": True,
     "languages": ["en"],
     "features": ["Composer", "Agent mode", "Tab"],
     "useCases": ["Coder une app", "Refactor", "Debug"],
     "keywords": ["code", "coder", "ide", "éditeur", "app", "refactor", "debug"],
     "score": 93, "color": "#0F0F0F"},

    {"slug": "windsurf", "name": "Windsurf", "vendor": "Codeium", "domain": "codeium.com",
     "tagline": "L'éditeur cascade-flow",
     "description": "IDE IA avec un agent qui anticipe l'intention sur plusieurs fichiers.",
     "categorySlugs": ["code", "agent"], "speedMs": 130, "accuracyPct": 90,
     "costPerPrompt": 0.0, "monthlyPrice": 15.0, "freeTier": True,
     "languages": ["en"],
     "features": ["Cascade", "Multi-file edit", "Plan mode"],
     "useCases": ["Refactor complexe", "Migration de stack"],
     "keywords": ["code", "refactor", "migration", "cascade", "agent"],
     "score": 88, "color": "#09B6A2"},

    {"slug": "v0", "name": "v0", "vendor": "Vercel", "domain": "vercel.com",
     "tagline": "Du prompt à l'UI React",
     "description": "Génère des composants Next.js + Tailwind directement depuis une description.",
     "categorySlugs": ["code"], "speedMs": 5000, "accuracyPct": 87,
     "costPerPrompt": 0.05, "monthlyPrice": 20.0, "freeTier": True,
     "languages": ["en"],
     "features": ["React/Next", "shadcn/ui", "Deploy"],
     "useCases": ["Landing page", "Composant UI", "Prototype rapide"],
     "keywords": ["ui", "react", "next", "composant", "landing", "prototype"],
     "score": 86, "color": "#000000"},

    {"slug": "bolt", "name": "Bolt.new", "vendor": "StackBlitz", "domain": "stackblitz.com",
     "tagline": "Une app full-stack en un prompt",
     "description": "Build, run et déploie une app full-stack dans le navigateur.",
     "categorySlugs": ["code", "agent"], "speedMs": 8000, "accuracyPct": 84,
     "costPerPrompt": 0.0, "monthlyPrice": 20.0, "freeTier": True,
     "languages": ["en"],
     "features": ["Full-stack", "WebContainer", "Deploy Netlify"],
     "useCases": ["MVP rapide", "App jetable", "Démo client"],
     "keywords": ["app", "fullstack", "mvp", "prototype", "démo"],
     "score": 84, "color": "#1389FD"},

    {"slug": "replit-agent", "name": "Replit Agent", "vendor": "Replit", "domain": "replit.com",
     "tagline": "L'agent qui code pour toi",
     "description": "Décrit ton idée, l'agent crée, teste et déploie l'app.",
     "categorySlugs": ["code", "agent"], "speedMs": 6000, "accuracyPct": 83,
     "costPerPrompt": 0.0, "monthlyPrice": 25.0, "freeTier": True,
     "languages": ["en"],
     "features": ["Agent autonome", "Cloud", "Deploy"],
     "useCases": ["Auto-build d'app", "Apprentissage code"],
     "keywords": ["agent", "app", "build", "auto", "replit"],
     "score": 82, "color": "#F26207"},

    # Video
    {"slug": "sora", "name": "Sora", "vendor": "OpenAI", "domain": "sora.com",
     "tagline": "Le générateur vidéo nouvelle génération",
     "description": "Génération vidéo cinématographique à partir de texte.",
     "categorySlugs": ["video"], "speedMs": 60000, "accuracyPct": 91,
     "costPerPrompt": 0.5, "monthlyPrice": 20.0, "freeTier": False,
     "languages": ["en", "fr"],
     "features": ["Text-to-video", "Storyboard", "Remix"],
     "useCases": ["Pub vidéo", "Court-métrage"],
     "keywords": ["vidéo", "video", "film", "court", "métrage", "pub", "animation", "clip"],
     "score": 88, "color": "#000000"},

    {"slug": "runway", "name": "Runway", "vendor": "Runway", "domain": "runwayml.com",
     "tagline": "La suite vidéo IA professionnelle",
     "description": "Outils complets : génération, montage, effets visuels IA.",
     "categorySlugs": ["video"], "speedMs": 45000, "accuracyPct": 86,
     "costPerPrompt": 0.3, "monthlyPrice": 15.0, "freeTier": True,
     "languages": ["en"],
     "features": ["Gen-3", "Motion brush", "Inpainting"],
     "useCases": ["VFX", "Court vidéo", "Édition"],
     "keywords": ["vidéo", "video", "vfx", "montage", "effet", "édition"],
     "score": 85, "color": "#01FF61"},

    {"slug": "luma", "name": "Luma Dream Machine", "vendor": "Luma AI", "domain": "lumalabs.ai",
     "tagline": "L'image qui prend vie",
     "description": "Anime tes images en vidéos cinématiques avec mouvements de caméra.",
     "categorySlugs": ["video"], "speedMs": 50000, "accuracyPct": 84,
     "costPerPrompt": 0.4, "monthlyPrice": 9.99, "freeTier": True,
     "languages": ["en"],
     "features": ["Image-to-video", "Camera motion", "Loop"],
     "useCases": ["Cinématique", "Animation produit", "Réseaux sociaux"],
     "keywords": ["animer", "animation", "cinématique", "luma", "mouvement"],
     "score": 83, "color": "#000000"},

    {"slug": "pika", "name": "Pika", "vendor": "Pika Labs", "domain": "pika.art",
     "tagline": "La vidéo grand public, ludique",
     "description": "Effets viraux, pikaffects et mode vidéo court drôle.",
     "categorySlugs": ["video"], "speedMs": 40000, "accuracyPct": 80,
     "costPerPrompt": 0.25, "monthlyPrice": 10.0, "freeTier": True,
     "languages": ["en"],
     "features": ["Pikaffects", "Lipsync", "Sound"],
     "useCases": ["TikTok", "Memes vidéo", "Réseaux"],
     "keywords": ["tiktok", "réseau", "social", "meme", "court"],
     "score": 78, "color": "#000000"},

    {"slug": "heygen", "name": "HeyGen", "vendor": "HeyGen", "domain": "heygen.com",
     "tagline": "Avatar vidéo qui parle ta langue",
     "description": "Crée des vidéos avec avatars réalistes en 175 langues.",
     "categorySlugs": ["video", "audio"], "speedMs": 30000, "accuracyPct": 88,
     "costPerPrompt": 0.5, "monthlyPrice": 24.0, "freeTier": True,
     "languages": ["fr", "en", "es", "de", "ja", "zh"],
     "features": ["Avatar", "175 langues", "Doublage"],
     "useCases": ["Tuto vidéo", "L&D", "Vidéo multilingue"],
     "keywords": ["avatar", "doublage", "tuto", "formation", "multilingue"],
     "score": 86, "color": "#7B5BFF"},

    # Audio
    {"slug": "elevenlabs", "name": "ElevenLabs", "vendor": "ElevenLabs", "domain": "elevenlabs.io",
     "tagline": "Voix synthétiques d'un réalisme stupéfiant",
     "description": "Synthèse vocale et clonage de voix multilingue ultra-réaliste.",
     "categorySlugs": ["audio"], "speedMs": 1500, "accuracyPct": 96,
     "costPerPrompt": 0.18, "monthlyPrice": 5.0, "freeTier": True,
     "languages": ["fr", "en", "es", "de", "it", "ja", "zh", "ko", "pt"],
     "features": ["Voice cloning", "Multi-langue", "API"],
     "useCases": ["Voix-off", "Podcast", "Audiolivre"],
     "keywords": ["voix", "audio", "podcast", "narration", "voice", "off", "audiolivre", "clonage"],
     "score": 94, "color": "#000000"},

    {"slug": "whisper", "name": "Whisper", "vendor": "OpenAI", "domain": "openai.com",
     "tagline": "La transcription multilingue de référence",
     "description": "Transcription audio précise en 90+ langues.",
     "categorySlugs": ["audio"], "speedMs": 5000, "accuracyPct": 93,
     "costPerPrompt": 0.006, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["fr", "en", "es", "de", "it", "ja", "zh", "ko", "pt", "ar"],
     "features": ["90+ langues", "Open-source", "API"],
     "useCases": ["Sous-titres", "Transcription réunion", "Notes"],
     "keywords": ["transcription", "transcrire", "audio", "sous-titre", "réunion", "meeting", "podcast"],
     "score": 90, "color": "#10A37F"},

    {"slug": "suno", "name": "Suno", "vendor": "Suno", "domain": "suno.com",
     "tagline": "Compose des chansons en quelques secondes",
     "description": "Génération de chansons complètes (musique + voix) à partir de texte.",
     "categorySlugs": ["audio"], "speedMs": 30000, "accuracyPct": 85,
     "costPerPrompt": 0.0, "monthlyPrice": 10.0, "freeTier": True,
     "languages": ["fr", "en", "es", "ja"],
     "features": ["Chanson complète", "Voix", "Style"],
     "useCases": ["Musique d'ambiance", "Jingle", "Démo"],
     "keywords": ["musique", "chanson", "song", "jingle", "instrumental", "mélodie"],
     "score": 84, "color": "#1A1A1A"},

    {"slug": "udio", "name": "Udio", "vendor": "Udio", "domain": "udio.com",
     "tagline": "L'autre studio musical IA",
     "description": "Composition de morceaux longs avec voix et instruments réalistes.",
     "categorySlugs": ["audio"], "speedMs": 25000, "accuracyPct": 84,
     "costPerPrompt": 0.0, "monthlyPrice": 10.0, "freeTier": True,
     "languages": ["en"],
     "features": ["Morceaux longs", "Inpainting audio", "Stems"],
     "useCases": ["Démo album", "Musique de film court"],
     "keywords": ["musique", "chanson", "compose", "instrumental"],
     "score": 81, "color": "#000000"},

    {"slug": "fireflies", "name": "Fireflies.ai", "vendor": "Fireflies", "domain": "fireflies.ai",
     "tagline": "Le copilote de tes réunions",
     "description": "Transcription, résumé et analyse automatiques de réunions.",
     "categorySlugs": ["audio", "productivite"], "speedMs": 3000, "accuracyPct": 88,
     "costPerPrompt": 0.0, "monthlyPrice": 10.0, "freeTier": True,
     "languages": ["fr", "en", "es", "de"],
     "features": ["Zoom", "Meet", "Teams", "Résumé"],
     "useCases": ["Compte-rendu réunion", "Action items"],
     "keywords": ["réunion", "meeting", "zoom", "meet", "teams", "compte-rendu"],
     "score": 83, "color": "#F0463A"},

    {"slug": "otter", "name": "Otter.ai", "vendor": "Otter", "domain": "otter.ai",
     "tagline": "Le scribe intelligent",
     "description": "Transcription temps réel + chat sur tes meetings passés.",
     "categorySlugs": ["audio", "productivite"], "speedMs": 1000, "accuracyPct": 87,
     "costPerPrompt": 0.0, "monthlyPrice": 16.99, "freeTier": True,
     "languages": ["en", "fr", "es"],
     "features": ["Live caption", "Chat meetings", "Slides capture"],
     "useCases": ["Notes étudiantes", "Notes meetings"],
     "keywords": ["transcription", "réunion", "meeting", "notes", "live"],
     "score": 80, "color": "#3B82F6"},

    # Productivity / Text utilities
    {"slug": "notion-ai", "name": "Notion AI", "vendor": "Notion", "domain": "notion.so",
     "tagline": "L'IA dans ton workspace",
     "description": "Assistant intégré à Notion pour rédaction, résumé et organisation.",
     "categorySlugs": ["productivite", "texte"], "speedMs": 200, "accuracyPct": 87,
     "costPerPrompt": 0.0, "monthlyPrice": 10.0, "freeTier": False,
     "languages": ["fr", "en", "es", "de"],
     "features": ["Q&A docs", "Auto-fill", "Résumé"],
     "useCases": ["Notes équipe", "Wiki", "Résumé réunion"],
     "keywords": ["notion", "notes", "wiki", "équipe", "team", "doc", "workspace"],
     "score": 84, "color": "#000000"},

    {"slug": "grammarly", "name": "Grammarly", "vendor": "Grammarly", "domain": "grammarly.com",
     "tagline": "Le correcteur intelligent",
     "description": "Correction grammaticale, ton et style sur tout ton écrit.",
     "categorySlugs": ["texte", "productivite"], "speedMs": 100, "accuracyPct": 91,
     "costPerPrompt": 0.0, "monthlyPrice": 12.0, "freeTier": True,
     "languages": ["en"],
     "features": ["Correction temps réel", "Ton", "Plagiat"],
     "useCases": ["Email pro", "Mémoire", "Article"],
     "keywords": ["grammaire", "correction", "orthographe", "ton", "style", "anglais"],
     "score": 86, "color": "#15C39A"},

    {"slug": "deepl", "name": "DeepL", "vendor": "DeepL", "domain": "deepl.com",
     "tagline": "La traduction qui sonne juste",
     "description": "Traduction d'une qualité supérieure, surtout pour les langues européennes.",
     "categorySlugs": ["texte", "productivite"], "speedMs": 90, "accuracyPct": 95,
     "costPerPrompt": 0.0, "monthlyPrice": 8.74, "freeTier": True,
     "languages": ["fr", "en", "es", "de", "it", "ja", "zh", "ko", "pt", "ru", "nl"],
     "features": ["Write", "Glossaire", "Documents"],
     "useCases": ["Traduction pro", "Email international"],
     "keywords": ["traduction", "traduire", "anglais", "français", "espagnol", "allemand", "langue"],
     "score": 92, "color": "#0F2B46"},

    {"slug": "canva-ai", "name": "Canva Magic Studio", "vendor": "Canva", "domain": "canva.com",
     "tagline": "Le design IA grand public",
     "description": "Suite IA dans Canva : génération d'images, redimensionnement, écriture.",
     "categorySlugs": ["image", "productivite"], "speedMs": 4000, "accuracyPct": 83,
     "costPerPrompt": 0.0, "monthlyPrice": 12.99, "freeTier": True,
     "languages": ["fr", "en", "es", "de", "it"],
     "features": ["Magic Design", "Magic Write", "Background remover"],
     "useCases": ["Réseaux sociaux", "Présentation", "Affiche"],
     "keywords": ["design", "réseau", "social", "présentation", "powerpoint", "affiche", "post", "instagram"],
     "score": 81, "color": "#00C4CC"},

    {"slug": "gamma", "name": "Gamma", "vendor": "Gamma", "domain": "gamma.app",
     "tagline": "Slides, sites, docs en un clic",
     "description": "Génère présentations, pages web et docs visuels à partir d'un brief.",
     "categorySlugs": ["productivite"], "speedMs": 4000, "accuracyPct": 86,
     "costPerPrompt": 0.0, "monthlyPrice": 10.0, "freeTier": True,
     "languages": ["fr", "en", "es"],
     "features": ["Slides", "Webpage", "PDF export"],
     "useCases": ["Pitch deck", "Présentation client", "Slides cours"],
     "keywords": ["présentation", "slide", "pitch", "deck", "powerpoint", "keynote"],
     "score": 86, "color": "#A855F7"},

    {"slug": "tome", "name": "Tome", "vendor": "Tome", "domain": "tome.app",
     "tagline": "Des slides narratives nouvelle génération",
     "description": "Storytelling visuel avec layouts dynamiques et formats interactifs.",
     "categorySlugs": ["productivite"], "speedMs": 5000, "accuracyPct": 82,
     "costPerPrompt": 0.0, "monthlyPrice": 16.0, "freeTier": True,
     "languages": ["en", "fr"],
     "features": ["Storytelling", "Interactif", "Tiles"],
     "useCases": ["Pitch", "Brief créatif"],
     "keywords": ["pitch", "présentation", "storytelling", "slide"],
     "score": 79, "color": "#000000"},

    # Agents / Automation
    {"slug": "zapier-ai", "name": "Zapier Agents", "vendor": "Zapier", "domain": "zapier.com",
     "tagline": "Les agents qui orchestrent ton stack",
     "description": "Crée des agents qui connectent tes 7000+ apps avec déclencheurs IA.",
     "categorySlugs": ["agent", "productivite"], "speedMs": 2000, "accuracyPct": 86,
     "costPerPrompt": 0.0, "monthlyPrice": 19.99, "freeTier": True,
     "languages": ["fr", "en"],
     "features": ["7000+ intégrations", "Triggers IA", "No-code"],
     "useCases": ["Automatiser CRM", "Workflows email", "Lead capture"],
     "keywords": ["automatisation", "automate", "workflow", "zap", "intégration", "no-code"],
     "score": 87, "color": "#FF4F00"},

    {"slug": "make", "name": "Make", "vendor": "Make", "domain": "make.com",
     "tagline": "Le studio visuel d'automatisations",
     "description": "Build des scénarios visuels avec routes, filtres et IA pour automatiser tout.",
     "categorySlugs": ["agent", "productivite"], "speedMs": 1500, "accuracyPct": 85,
     "costPerPrompt": 0.0, "monthlyPrice": 9.0, "freeTier": True,
     "languages": ["fr", "en", "es"],
     "features": ["Scenarios visuels", "Routeurs", "Webhooks"],
     "useCases": ["Sync CRM", "Pipelines marketing"],
     "keywords": ["automatisation", "scenario", "workflow", "intégration"],
     "score": 84, "color": "#6D00CC"},

    {"slug": "n8n", "name": "n8n", "vendor": "n8n", "domain": "n8n.io",
     "tagline": "L'automatisation open-source pour devs",
     "description": "Plateforme self-hostable d'automatisations avec nodes IA natifs.",
     "categorySlugs": ["agent", "code"], "speedMs": 1000, "accuracyPct": 86,
     "costPerPrompt": 0.0, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["en"],
     "features": ["Open-source", "Self-host", "AI nodes"],
     "useCases": ["Pipelines data", "Agents internes"],
     "keywords": ["open", "self-hosted", "workflow", "data", "pipeline"],
     "score": 86, "color": "#EA4B71"},

    # Data / Analyse
    {"slug": "julius", "name": "Julius", "vendor": "Julius AI", "domain": "julius.ai",
     "tagline": "Ton analyste de données conversationnel",
     "description": "Pose des questions en français à tes datasets, obtiens graphiques + insights.",
     "categorySlugs": ["data", "recherche"], "speedMs": 3000, "accuracyPct": 88,
     "costPerPrompt": 0.0, "monthlyPrice": 20.0, "freeTier": True,
     "languages": ["fr", "en"],
     "features": ["CSV/Excel", "Graphiques", "Forecast"],
     "useCases": ["Analyse ventes", "Tableau de bord", "Forecast"],
     "keywords": ["data", "donnée", "csv", "excel", "graphique", "tableau", "analyse", "forecast"],
     "score": 86, "color": "#000000"},

    {"slug": "rows", "name": "Rows", "vendor": "Rows", "domain": "rows.com",
     "tagline": "Le tableur boosté par l'IA",
     "description": "Tableur moderne avec fonctions IA natives et intégrations marketing.",
     "categorySlugs": ["data", "productivite"], "speedMs": 200, "accuracyPct": 84,
     "costPerPrompt": 0.0, "monthlyPrice": 8.0, "freeTier": True,
     "languages": ["en", "fr", "es"],
     "features": ["AI Analyst", "Connectors", "Dashboards"],
     "useCases": ["Reporting marketing", "KPI"],
     "keywords": ["tableur", "spreadsheet", "kpi", "reporting", "marketing"],
     "score": 80, "color": "#3F51B5"},

    # Dev tools / specific
    {"slug": "kling", "name": "Kling", "vendor": "Kuaishou", "domain": "klingai.com",
     "tagline": "La vidéo IA chinoise qui rivalise avec Sora",
     "description": "Génération vidéo cinématographique avec contrôle caméra fin.",
     "categorySlugs": ["video"], "speedMs": 60000, "accuracyPct": 88,
     "costPerPrompt": 0.4, "monthlyPrice": 10.0, "freeTier": True,
     "languages": ["zh", "en"],
     "features": ["Camera control", "Lipsync", "Long video"],
     "useCases": ["Pub vidéo", "Clip"],
     "keywords": ["vidéo", "video", "clip", "pub", "kling"],
     "score": 84, "color": "#000000"},

    {"slug": "krea", "name": "Krea", "vendor": "Krea", "domain": "krea.ai",
     "tagline": "Le creative playground temps réel",
     "description": "Image, vidéo et patterns en mode temps réel pour designers.",
     "categorySlugs": ["image", "video"], "speedMs": 500, "accuracyPct": 84,
     "costPerPrompt": 0.0, "monthlyPrice": 10.0, "freeTier": True,
     "languages": ["en"],
     "features": ["Real-time", "Enhance", "Patterns"],
     "useCases": ["Mood board", "Motion design", "Itération design"],
     "keywords": ["temps réel", "design", "moodboard", "itération", "pattern"],
     "score": 81, "color": "#FF4500"},

    {"slug": "scribe", "name": "Scribe", "vendor": "Scribe", "domain": "scribehow.com",
     "tagline": "Transforme tes process en guides visuels",
     "description": "Capture automatiquement tes étapes à l'écran et génère un how-to illustré.",
     "categorySlugs": ["productivite"], "speedMs": 3000, "accuracyPct": 88,
     "costPerPrompt": 0.0, "monthlyPrice": 23.0, "freeTier": True,
     "languages": ["en", "fr"],
     "features": ["Auto-capture", "Annotations", "Partage"],
     "useCases": ["Onboarding équipe", "Documentation interne"],
     "keywords": ["how-to", "guide", "documentation", "onboarding", "tutoriel"],
     "score": 82, "color": "#0F62FE"},

    {"slug": "decktopus", "name": "Decktopus", "vendor": "Decktopus", "domain": "decktopus.com",
     "tagline": "Slides en moins de 60 secondes",
     "description": "Crée et personnalise des présentations à partir d'un sujet.",
     "categorySlugs": ["productivite"], "speedMs": 6000, "accuracyPct": 80,
     "costPerPrompt": 0.0, "monthlyPrice": 9.99, "freeTier": True,
     "languages": ["fr", "en", "es", "de"],
     "features": ["Templates", "Thèmes", "Export PDF"],
     "useCases": ["Présentation rapide"],
     "keywords": ["slide", "présentation", "deck", "rapide"],
     "score": 76, "color": "#7B5BFF"},

    {"slug": "tldraw", "name": "tldraw", "vendor": "tldraw", "domain": "tldraw.com",
     "tagline": "Du dessin à l'app en un clic",
     "description": "Whiteboard infini avec Make Real : transforme tes croquis en sites web.",
     "categorySlugs": ["code", "image"], "speedMs": 8000, "accuracyPct": 80,
     "costPerPrompt": 0.0, "monthlyPrice": 0.0, "freeTier": True,
     "languages": ["en"],
     "features": ["Whiteboard", "Make Real", "Multiplayer"],
     "useCases": ["Prototype UI", "Brainstorming visuel"],
     "keywords": ["whiteboard", "croquis", "wireframe", "ui", "prototype"],
     "score": 80, "color": "#000000"},
]


# Decorate every tool with a Clearbit logo URL based on its domain
for _t in TOOLS:
    _t["image"] = _logo(_t["domain"])
