"""Seed catalog of 20 popular AI tools for IA Match."""

CATEGORIES = [
    {"slug": "texte", "name": "Texte & Écriture", "description": "Génération de texte, rédaction, résumé"},
    {"slug": "image", "name": "Image & Design", "description": "Génération et édition d'images"},
    {"slug": "code", "name": "Code & Dev", "description": "Assistants pour développeurs"},
    {"slug": "video", "name": "Vidéo", "description": "Génération et montage vidéo"},
    {"slug": "audio", "name": "Audio & Voix", "description": "Voix synthétique, transcription"},
    {"slug": "productivite", "name": "Productivité", "description": "Documents, tableurs, présentations"},
    {"slug": "recherche", "name": "Recherche & Analyse", "description": "Recherche web, synthèse d'information"},
]

# Curated catalog. Keywords used by rule-based matcher.
TOOLS = [
    {
        "slug": "chatgpt",
        "name": "ChatGPT",
        "vendor": "OpenAI",
        "tagline": "L'assistant conversationnel polyvalent",
        "description": "Modèle GPT polyvalent pour rédaction, brainstorming, code et analyse de documents.",
        "categorySlugs": ["texte", "productivite", "recherche", "code"],
        "speedMs": 180,
        "accuracyPct": 92,
        "costPerPrompt": 0.002,
        "monthlyPrice": 20.0,
        "freeTier": True,
        "languages": ["fr", "en", "es", "de", "it", "ja", "zh"],
        "features": ["Multimodal", "Vision", "Browsing", "Custom GPTs"],
        "useCases": ["Rédiger un CV", "Résumer un document", "Brainstorming", "Apprendre"],
        "keywords": ["cv", "resume", "résumé", "lettre", "motivation", "email", "écrire", "rédiger", "texte", "brainstorm", "idée", "synthèse", "analyse"],
        "score": 94,
        "color": "#10A37F",
        "image": "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&q=80",
    },
    {
        "slug": "claude",
        "name": "Claude",
        "vendor": "Anthropic",
        "tagline": "Le rédacteur long format au raisonnement profond",
        "description": "Excellent pour l'analyse de documents longs, le raisonnement nuancé et l'écriture soignée.",
        "categorySlugs": ["texte", "recherche", "productivite"],
        "speedMs": 220,
        "accuracyPct": 95,
        "costPerPrompt": 0.003,
        "monthlyPrice": 20.0,
        "freeTier": True,
        "languages": ["fr", "en", "es", "de", "it", "ja"],
        "features": ["Contexte 200k tokens", "Artefacts", "Analyse fichiers"],
        "useCases": ["Analyser un long PDF", "Écrire un essai", "Audit juridique"],
        "keywords": ["analyse", "long", "document", "pdf", "rapport", "essai", "juridique", "résumé", "synthèse", "rédaction", "livre"],
        "score": 95,
        "color": "#CC785C",
        "image": "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=600&q=80",
    },
    {
        "slug": "gemini",
        "name": "Gemini",
        "vendor": "Google",
        "tagline": "L'IA multimodale intégrée à Google",
        "description": "Multimodal natif, intégré à Gmail, Docs et la recherche Google.",
        "categorySlugs": ["texte", "productivite", "recherche", "image"],
        "speedMs": 160,
        "accuracyPct": 90,
        "costPerPrompt": 0.0015,
        "monthlyPrice": 19.99,
        "freeTier": True,
        "languages": ["fr", "en", "es", "de", "ja", "zh", "ko"],
        "features": ["Multimodal", "Workspace", "Recherche temps réel"],
        "useCases": ["Recherche web", "Email", "Docs Google"],
        "keywords": ["recherche", "google", "email", "gmail", "docs", "tableur", "actualité", "web"],
        "score": 90,
        "color": "#4285F4",
        "image": "https://images.unsplash.com/photo-1522199755839-a2bacb67c546?w=600&q=80",
    },
    {
        "slug": "perplexity",
        "name": "Perplexity",
        "vendor": "Perplexity AI",
        "tagline": "Le moteur de recherche IA avec sources",
        "description": "Recherche web en temps réel avec citations vérifiables.",
        "categorySlugs": ["recherche"],
        "speedMs": 140,
        "accuracyPct": 88,
        "costPerPrompt": 0.001,
        "monthlyPrice": 20.0,
        "freeTier": True,
        "languages": ["fr", "en", "es", "de"],
        "features": ["Citations", "Recherche temps réel", "Pro Search"],
        "useCases": ["Recherche académique", "Veille", "Fact-checking"],
        "keywords": ["recherche", "veille", "actualité", "source", "citation", "fact", "article", "web"],
        "score": 89,
        "color": "#20B8CD",
        "image": "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=80",
    },
    {
        "slug": "midjourney",
        "name": "Midjourney",
        "vendor": "Midjourney",
        "tagline": "Le maître de l'image artistique",
        "description": "Génération d'images d'une qualité artistique exceptionnelle.",
        "categorySlugs": ["image"],
        "speedMs": 30000,
        "accuracyPct": 96,
        "costPerPrompt": 0.04,
        "monthlyPrice": 10.0,
        "freeTier": False,
        "languages": ["en"],
        "features": ["Style references", "Upscale", "V6"],
        "useCases": ["Illustration", "Concept art", "Visuel marketing"],
        "keywords": ["image", "illustration", "art", "dessin", "visuel", "design", "logo", "affiche", "poster"],
        "score": 93,
        "color": "#000000",
        "image": "https://images.unsplash.com/photo-1547954575-855750c57bd3?w=600&q=80",
    },
    {
        "slug": "dalle",
        "name": "DALL-E 3",
        "vendor": "OpenAI",
        "tagline": "L'image fidèle au prompt",
        "description": "Génération d'images intégrée à ChatGPT, suit fidèlement les instructions.",
        "categorySlugs": ["image"],
        "speedMs": 12000,
        "accuracyPct": 88,
        "costPerPrompt": 0.04,
        "monthlyPrice": 20.0,
        "freeTier": False,
        "languages": ["fr", "en", "es"],
        "features": ["Intégré ChatGPT", "Édition d'image"],
        "useCases": ["Visuel rapide", "Illustration concept"],
        "keywords": ["image", "illustration", "dessin", "visuel", "concept"],
        "score": 86,
        "color": "#FF6B35",
        "image": "https://images.unsplash.com/photo-1561736778-92e52a7769ef?w=600&q=80",
    },
    {
        "slug": "stable-diffusion",
        "name": "Stable Diffusion",
        "vendor": "Stability AI",
        "tagline": "Open-source, contrôle total",
        "description": "Modèle open-source, customisable et exécutable en local.",
        "categorySlugs": ["image"],
        "speedMs": 8000,
        "accuracyPct": 84,
        "costPerPrompt": 0.0,
        "monthlyPrice": 0.0,
        "freeTier": True,
        "languages": ["en"],
        "features": ["Open-source", "Local", "ControlNet"],
        "useCases": ["Pipeline custom", "Volume élevé"],
        "keywords": ["image", "open", "gratuit", "local", "self-hosted"],
        "score": 82,
        "color": "#7B61FF",
        "image": "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&q=80",
    },
    {
        "slug": "github-copilot",
        "name": "GitHub Copilot",
        "vendor": "GitHub",
        "tagline": "Le pair-programmeur dans ton IDE",
        "description": "Suggestions de code en temps réel dans VS Code, JetBrains et autres IDEs.",
        "categorySlugs": ["code"],
        "speedMs": 80,
        "accuracyPct": 89,
        "costPerPrompt": 0.0,
        "monthlyPrice": 10.0,
        "freeTier": False,
        "languages": ["en"],
        "features": ["IDE plugin", "Chat", "Workspace"],
        "useCases": ["Coder plus vite", "Auto-complétion"],
        "keywords": ["code", "coder", "programmation", "développer", "ide", "vscode", "fonction"],
        "score": 91,
        "color": "#181717",
        "image": "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&q=80",
    },
    {
        "slug": "cursor",
        "name": "Cursor",
        "vendor": "Cursor",
        "tagline": "L'IDE pensé pour l'IA",
        "description": "Éditeur de code avec IA native, refactoring multi-fichiers.",
        "categorySlugs": ["code"],
        "speedMs": 120,
        "accuracyPct": 92,
        "costPerPrompt": 0.0,
        "monthlyPrice": 20.0,
        "freeTier": True,
        "languages": ["en"],
        "features": ["Composer", "Agent mode", "Tab"],
        "useCases": ["Coder une app", "Refactor", "Debug"],
        "keywords": ["code", "coder", "ide", "éditeur", "app", "développer", "refactor", "debug"],
        "score": 93,
        "color": "#0F0F0F",
        "image": "https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=600&q=80",
    },
    {
        "slug": "sora",
        "name": "Sora",
        "vendor": "OpenAI",
        "tagline": "Le générateur vidéo nouvelle génération",
        "description": "Génération vidéo cinématographique à partir de texte.",
        "categorySlugs": ["video"],
        "speedMs": 60000,
        "accuracyPct": 91,
        "costPerPrompt": 0.5,
        "monthlyPrice": 20.0,
        "freeTier": False,
        "languages": ["en", "fr"],
        "features": ["Text-to-video", "Storyboard", "Remix"],
        "useCases": ["Pub vidéo", "Court-métrage"],
        "keywords": ["vidéo", "video", "film", "court", "métrage", "pub", "animation", "clip"],
        "score": 88,
        "color": "#000000",
        "image": "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=600&q=80",
    },
    {
        "slug": "runway",
        "name": "Runway",
        "vendor": "Runway",
        "tagline": "La suite vidéo IA professionnelle",
        "description": "Outils complets : génération, montage, effets visuels IA.",
        "categorySlugs": ["video"],
        "speedMs": 45000,
        "accuracyPct": 86,
        "costPerPrompt": 0.3,
        "monthlyPrice": 15.0,
        "freeTier": True,
        "languages": ["en"],
        "features": ["Gen-3", "Motion brush", "Inpainting"],
        "useCases": ["VFX", "Court vidéo", "Édition"],
        "keywords": ["vidéo", "video", "vfx", "montage", "effet", "édition"],
        "score": 85,
        "color": "#01FF61",
        "image": "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=600&q=80",
    },
    {
        "slug": "elevenlabs",
        "name": "ElevenLabs",
        "vendor": "ElevenLabs",
        "tagline": "Voix synthétiques d'un réalisme stupéfiant",
        "description": "Synthèse vocale et clonage de voix multilingue ultra-réaliste.",
        "categorySlugs": ["audio"],
        "speedMs": 1500,
        "accuracyPct": 96,
        "costPerPrompt": 0.18,
        "monthlyPrice": 5.0,
        "freeTier": True,
        "languages": ["fr", "en", "es", "de", "it", "ja", "zh", "ko", "pt"],
        "features": ["Voice cloning", "Multi-langue", "API"],
        "useCases": ["Voix-off", "Podcast", "Audiolivre"],
        "keywords": ["voix", "audio", "podcast", "narration", "voice", "off", "audiolivre", "clonage"],
        "score": 94,
        "color": "#FFFFFF",
        "image": "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=600&q=80",
    },
    {
        "slug": "whisper",
        "name": "Whisper",
        "vendor": "OpenAI",
        "tagline": "La transcription multilingue de référence",
        "description": "Transcription audio précise en 90+ langues.",
        "categorySlugs": ["audio"],
        "speedMs": 5000,
        "accuracyPct": 93,
        "costPerPrompt": 0.006,
        "monthlyPrice": 0.0,
        "freeTier": True,
        "languages": ["fr", "en", "es", "de", "it", "ja", "zh", "ko", "pt", "ar"],
        "features": ["90+ langues", "Open-source", "API"],
        "useCases": ["Sous-titres", "Transcription réunion", "Notes"],
        "keywords": ["transcription", "transcrire", "audio", "sous-titre", "réunion", "meeting", "podcast"],
        "score": 90,
        "color": "#10A37F",
        "image": "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=600&q=80",
    },
    {
        "slug": "notion-ai",
        "name": "Notion AI",
        "vendor": "Notion",
        "tagline": "L'IA dans ton workspace",
        "description": "Assistant intégré à Notion pour rédaction, résumé et organisation.",
        "categorySlugs": ["productivite", "texte"],
        "speedMs": 200,
        "accuracyPct": 87,
        "costPerPrompt": 0.0,
        "monthlyPrice": 10.0,
        "freeTier": False,
        "languages": ["fr", "en", "es", "de"],
        "features": ["Q&A docs", "Auto-fill", "Résumé"],
        "useCases": ["Notes équipe", "Wiki", "Résumé réunion"],
        "keywords": ["notion", "notes", "wiki", "équipe", "team", "doc", "workspace"],
        "score": 84,
        "color": "#000000",
        "image": "https://images.unsplash.com/photo-1611224885990-ab7363d1f2a9?w=600&q=80",
    },
    {
        "slug": "grammarly",
        "name": "Grammarly",
        "vendor": "Grammarly",
        "tagline": "Le correcteur intelligent",
        "description": "Correction grammaticale, ton et style sur tout ton écrit.",
        "categorySlugs": ["texte", "productivite"],
        "speedMs": 100,
        "accuracyPct": 91,
        "costPerPrompt": 0.0,
        "monthlyPrice": 12.0,
        "freeTier": True,
        "languages": ["en"],
        "features": ["Correction temps réel", "Ton", "Plagiat"],
        "useCases": ["Email pro", "Mémoire", "Article"],
        "keywords": ["grammaire", "correction", "ortographe", "orthographe", "ton", "style", "anglais"],
        "score": 86,
        "color": "#15C39A",
        "image": "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=600&q=80",
    },
    {
        "slug": "canva-ai",
        "name": "Canva Magic Studio",
        "vendor": "Canva",
        "tagline": "Le design IA grand public",
        "description": "Suite IA dans Canva : génération d'images, redimensionnement, écriture.",
        "categorySlugs": ["image", "productivite"],
        "speedMs": 4000,
        "accuracyPct": 83,
        "costPerPrompt": 0.0,
        "monthlyPrice": 12.99,
        "freeTier": True,
        "languages": ["fr", "en", "es", "de", "it"],
        "features": ["Magic Design", "Magic Write", "Background remover"],
        "useCases": ["Réseaux sociaux", "Présentation", "Affiche"],
        "keywords": ["design", "réseau", "social", "présentation", "powerpoint", "affiche", "post", "instagram"],
        "score": 81,
        "color": "#00C4CC",
        "image": "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=600&q=80",
    },
    {
        "slug": "fireflies",
        "name": "Fireflies.ai",
        "vendor": "Fireflies",
        "tagline": "Le copilote de tes réunions",
        "description": "Transcription, résumé et analyse automatiques de réunions.",
        "categorySlugs": ["audio", "productivite"],
        "speedMs": 3000,
        "accuracyPct": 88,
        "costPerPrompt": 0.0,
        "monthlyPrice": 10.0,
        "freeTier": True,
        "languages": ["fr", "en", "es", "de"],
        "features": ["Zoom", "Meet", "Teams", "Résumé"],
        "useCases": ["Compte-rendu réunion", "Action items"],
        "keywords": ["réunion", "meeting", "zoom", "meet", "teams", "compte-rendu", "compte rendu"],
        "score": 83,
        "color": "#F0463A",
        "image": "https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=600&q=80",
    },
    {
        "slug": "deepl",
        "name": "DeepL",
        "vendor": "DeepL",
        "tagline": "La traduction qui sonne juste",
        "description": "Traduction d'une qualité supérieure, surtout pour les langues européennes.",
        "categorySlugs": ["texte", "productivite"],
        "speedMs": 90,
        "accuracyPct": 95,
        "costPerPrompt": 0.0,
        "monthlyPrice": 8.74,
        "freeTier": True,
        "languages": ["fr", "en", "es", "de", "it", "ja", "zh", "ko", "pt", "ru", "nl"],
        "features": ["Write", "Glossaire", "Documents"],
        "useCases": ["Traduction pro", "Email international"],
        "keywords": ["traduction", "traduire", "anglais", "français", "espagnol", "allemand", "langue"],
        "score": 92,
        "color": "#0F2B46",
        "image": "https://images.unsplash.com/photo-1555431189-0fabf2667795?w=600&q=80",
    },
    {
        "slug": "suno",
        "name": "Suno",
        "vendor": "Suno",
        "tagline": "Compose des chansons en quelques secondes",
        "description": "Génération de chansons complètes (musique + voix) à partir de texte.",
        "categorySlugs": ["audio"],
        "speedMs": 30000,
        "accuracyPct": 85,
        "costPerPrompt": 0.0,
        "monthlyPrice": 10.0,
        "freeTier": True,
        "languages": ["fr", "en", "es", "ja"],
        "features": ["Chanson complète", "Voix", "Style"],
        "useCases": ["Musique d'ambiance", "Jingle", "Démo"],
        "keywords": ["musique", "chanson", "song", "jingle", "instrumental", "mélodie"],
        "score": 84,
        "color": "#1A1A1A",
        "image": "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&q=80",
    },
    {
        "slug": "you-com",
        "name": "You.com",
        "vendor": "You.com",
        "tagline": "Le moteur de recherche IA tout-en-un",
        "description": "Recherche IA avec multi-modèles (Claude, GPT, Gemini) en un seul endroit.",
        "categorySlugs": ["recherche", "texte"],
        "speedMs": 200,
        "accuracyPct": 86,
        "costPerPrompt": 0.001,
        "monthlyPrice": 15.0,
        "freeTier": True,
        "languages": ["fr", "en", "es"],
        "features": ["Multi-modèle", "Agents", "Apps"],
        "useCases": ["Recherche avancée", "Veille techno"],
        "keywords": ["recherche", "veille", "multi", "agent", "moteur"],
        "score": 80,
        "color": "#7C3AED",
        "image": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&q=80",
    },
]
