import React, { useEffect, useMemo, useState } from "react";
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, ActivityIndicator, Linking } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useRouter } from "expo-router";
import { ChevronLeft, ExternalLink } from "lucide-react-native";
import { fonts, radius, spacing } from "../../src/theme";
import { useTheme } from "../../src/theme-context";
import { api, Resource } from "../../src/api";

const TYPES=["ALL","YOUTUBE","BLOG","PODCAST","NEWSLETTER","OUTIL"];
export default function AcademyResources(){const router=useRouter();const{colors}=useTheme();const[items,setItems]=useState<Resource[]>([]);const[filter,setFilter]=useState("ALL");const[loading,setLoading]=useState(true);useEffect(()=>{api.listResources().then(setItems).finally(()=>setLoading(false));},[]);const filtered=useMemo(()=>filter==="ALL"?items:items.filter(r=>r.category===filter),[items,filter]);return <SafeAreaView style={[styles.container,{backgroundColor:colors.bg}]} edges={["top"]}><ScrollView contentContainerStyle={styles.scroll}><TouchableOpacity onPress={()=>router.back()} style={styles.back}><ChevronLeft size={18} color={colors.textPrimary}/><Text style={[styles.backText,{color:colors.textPrimary}]}>Academy</Text></TouchableOpacity><Text style={[styles.eyebrow,{color:colors.coral}]}>RESSOURCES · {items.length}</Text><Text style={[styles.title,{color:colors.textPrimary}]}>Sources utiles, séparées du hub.</Text><View style={styles.filters}>{TYPES.map(t=><TouchableOpacity key={t} onPress={()=>setFilter(t)} style={[styles.chip,{borderColor:filter===t?colors.coral:colors.borderSubtle,backgroundColor:filter===t?colors.coralSoft:colors.surface}]}><Text style={[styles.chipText,{color:filter===t?colors.coral:colors.textSecondary}]}>{t==="ALL"?"Tout":t}</Text></TouchableOpacity>)}</View>{loading?<ActivityIndicator color={colors.coral}/>:filtered.map(r=><TouchableOpacity key={r.id} onPress={()=>Linking.openURL(r.url).catch(()=>{})} style={[styles.card,{backgroundColor:colors.surface,borderColor:colors.borderSubtle}]}><View style={styles.head}><Text style={[styles.cat,{color:colors.coral}]}>{r.category}</Text><ExternalLink size={15} color={colors.textSecondary}/></View><Text style={[styles.cardTitle,{color:colors.textPrimary}]}>{r.title}</Text><Text style={[styles.author,{color:colors.textSecondary}]}>par {r.author}</Text><Text style={[styles.summary,{color:colors.textSecondary}]}>{r.summary}</Text></TouchableOpacity>)}<View style={{height:80}}/></ScrollView></SafeAreaView>}
const styles=StyleSheet.create({container:{flex:1},scroll:{padding:spacing.lg},back:{flexDirection:"row",alignItems:"center",gap:6,marginBottom:spacing.md},backText:{fontFamily:fonts.bodyBold,fontSize:13},eyebrow:{fontFamily:fonts.bodyBold,fontSize:10,letterSpacing:2},title:{fontFamily:fonts.serif,fontSize:34,lineHeight:40,marginVertical:spacing.md},filters:{flexDirection:"row",flexWrap:"wrap",gap:8,marginBottom:spacing.md},chip:{borderWidth:1,borderRadius:radius.pill,paddingHorizontal:12,paddingVertical:8},chipText:{fontFamily:fonts.bodySemi,fontSize:12},card:{borderWidth:1,borderRadius:radius.lg,padding:spacing.md,marginBottom:spacing.md},head:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},cat:{fontFamily:fonts.bodyBold,fontSize:10,letterSpacing:1.5},cardTitle:{fontFamily:fonts.serif,fontSize:21,lineHeight:25,marginTop:8},author:{fontFamily:fonts.body,fontSize:11,marginTop:2,fontStyle:"italic"},summary:{fontFamily:fonts.body,fontSize:13,lineHeight:18,marginTop:8}});
