// Auto-generated Academy lesson visual mapping. One optimized visual per Academy course.
export const ACADEMY_LESSON_VISUALS = {
  "course_01_01_comprendre_ce_qu_est_une_ia_g_n_rative": require("../assets/academy/course-visuals/p01_c01__course_01_01_comprendre_ce_qu_est_une_ia_g_n_rative.jpg"),
  "course_01_02_reconna_tre_le_bon_outil_pour_le_bon_besoin": require("../assets/academy/course-visuals/p01_c02__course_01_02_reconna_tre_le_bon_outil_pour_le_bon_besoin.jpg"),
  "course_01_03_crire_un_premier_prompt_clair": require("../assets/academy/course-visuals/p01_c03__course_01_03_crire_un_premier_prompt_clair.jpg"),
  "course_01_04_ajouter_du_contexte_sans_crire_trop": require("../assets/academy/course-visuals/p01_c04__course_01_04_ajouter_du_contexte_sans_crire_trop.jpg"),
  "course_01_05_demander_un_format_de_r_ponse_pr_cis": require("../assets/academy/course-visuals/p01_c05__course_01_05_demander_un_format_de_r_ponse_pr_cis.jpg"),
  "course_01_06_am_liorer_une_r_ponse_insatisfaisante": require("../assets/academy/course-visuals/p01_c06__course_01_06_am_liorer_une_r_ponse_insatisfaisante.jpg"),
  "course_01_07_v_rifier_une_r_ponse_avant_de_l_utiliser": require("../assets/academy/course-visuals/p01_c07__course_01_07_v_rifier_une_r_ponse_avant_de_l_utiliser.jpg"),
  "course_01_08_construire_sa_routine_ia_quotidienne": require("../assets/academy/course-visuals/p01_c08__course_01_08_construire_sa_routine_ia_quotidienne.jpg"),
  "course_02_01_comprendre_les_diff_rences_entre_chatgpt_claude_": require("../assets/academy/course-visuals/p02_c01__course_02_01_comprendre_les_diff_rences_entre_chatgpt_claude_.jpg"),
  "course_02_02_bien_prompter_chatgpt_pour_les_t_ches_du_quotidi": require("../assets/academy/course-visuals/p02_c02__course_02_02_bien_prompter_chatgpt_pour_les_t_ches_du_quotidi.jpg"),
  "course_02_03_bien_prompter_claude_pour_crire_et_analyser_en_p": require("../assets/academy/course-visuals/p02_c03__course_02_03_bien_prompter_claude_pour_crire_et_analyser_en_p.jpg"),
  "course_02_04_bien_prompter_gemini_pour_le_multimodal_et_googl": require("../assets/academy/course-visuals/p02_c04__course_02_04_bien_prompter_gemini_pour_le_multimodal_et_googl.jpg"),
  "course_02_05_bien_prompter_perplexity_pour_la_recherche_sourc": require("../assets/academy/course-visuals/p02_c05__course_02_05_bien_prompter_perplexity_pour_la_recherche_sourc.jpg"),
  "course_02_06_utiliser_des_exemples_dans_un_prompt": require("../assets/academy/course-visuals/p02_c06__course_02_06_utiliser_des_exemples_dans_un_prompt.jpg"),
  "course_02_07_demander_plusieurs_versions_sans_perdre_en_quali": require("../assets/academy/course-visuals/p02_c07__course_02_07_demander_plusieurs_versions_sans_perdre_en_quali.jpg"),
  "course_02_08_cr_er_son_prompt_r_utilisable_personnel": require("../assets/academy/course-visuals/p02_c08__course_02_08_cr_er_son_prompt_r_utilisable_personnel.jpg"),
  "course_03_01_r_sumer_un_document_sans_perdre_les_informations": require("../assets/academy/course-visuals/p03_c01__course_03_01_r_sumer_un_document_sans_perdre_les_informations.jpg"),
  "course_03_02_faire_analyser_un_pdf_ou_un_long_texte": require("../assets/academy/course-visuals/p03_c02__course_03_02_faire_analyser_un_pdf_ou_un_long_texte.jpg"),
  "course_03_03_cr_er_une_fiche_de_synth_se_claire": require("../assets/academy/course-visuals/p03_c03__course_03_03_cr_er_une_fiche_de_synth_se_claire.jpg"),
  "course_03_04_comparer_deux_documents_ou_deux_avis": require("../assets/academy/course-visuals/p03_c04__course_03_04_comparer_deux_documents_ou_deux_avis.jpg"),
  "course_03_05_demander_des_sources_et_v_rifier_les_affirmation": require("../assets/academy/course-visuals/p03_c05__course_03_05_demander_des_sources_et_v_rifier_les_affirmation.jpg"),
  "course_03_06_transformer_un_document_en_plan_d_action": require("../assets/academy/course-visuals/p03_c06__course_03_06_transformer_un_document_en_plan_d_action.jpg"),
  "course_03_07_pr_parer_un_expos_ou_une_pr_sentation_avec_l_ia": require("../assets/academy/course-visuals/p03_c07__course_03_07_pr_parer_un_expos_ou_une_pr_sentation_avec_l_ia.jpg"),
  "course_03_08_utiliser_l_ia_pour_apprendre_plus_vite": require("../assets/academy/course-visuals/p03_c08__course_03_08_utiliser_l_ia_pour_apprendre_plus_vite.jpg"),
  "course_04_01_organiser_sa_journ_e_avec_l_ia": require("../assets/academy/course-visuals/p04_c01__course_04_01_organiser_sa_journ_e_avec_l_ia.jpg"),
  "course_04_02_transformer_une_id_e_floue_en_plan_clair": require("../assets/academy/course-visuals/p04_c02__course_04_02_transformer_une_id_e_floue_en_plan_clair.jpg"),
  "course_04_03_pr_parer_une_r_union_efficacement": require("../assets/academy/course-visuals/p04_c03__course_04_03_pr_parer_une_r_union_efficacement.jpg"),
  "course_04_04_r_sumer_une_r_union_en_actions": require("../assets/academy/course-visuals/p04_c04__course_04_04_r_sumer_une_r_union_en_actions.jpg"),
  "course_04_05_r_diger_des_emails_professionnels_plus_vite": require("../assets/academy/course-visuals/p04_c05__course_04_05_r_diger_des_emails_professionnels_plus_vite.jpg"),
  "course_04_06_cr_er_une_checklist_utile": require("../assets/academy/course-visuals/p04_c06__course_04_06_cr_er_une_checklist_utile.jpg"),
  "course_04_07_d_couper_un_gros_projet_en_petites_tapes": require("../assets/academy/course-visuals/p04_c07__course_04_07_d_couper_un_gros_projet_en_petites_tapes.jpg"),
  "course_04_08_mettre_en_place_un_assistant_personnel_simple": require("../assets/academy/course-visuals/p04_c08__course_04_08_mettre_en_place_un_assistant_personnel_simple.jpg"),
  "course_05_01_clarifier_une_id_e_de_business_avec_l_ia": require("../assets/academy/course-visuals/p05_c01__course_05_01_clarifier_une_id_e_de_business_avec_l_ia.jpg"),
  "course_05_02_d_finir_une_cible_client_simple": require("../assets/academy/course-visuals/p05_c02__course_05_02_d_finir_une_cible_client_simple.jpg"),
  "course_05_03_cr_er_une_offre_claire_et_vendable": require("../assets/academy/course-visuals/p05_c03__course_05_03_cr_er_une_offre_claire_et_vendable.jpg"),
  "course_05_04_analyser_un_concurrent_sans_copier": require("../assets/academy/course-visuals/p05_c04__course_05_04_analyser_un_concurrent_sans_copier.jpg"),
  "course_05_05_cr_er_une_landing_page_convaincante": require("../assets/academy/course-visuals/p05_c05__course_05_05_cr_er_une_landing_page_convaincante.jpg"),
  "course_05_06_pr_parer_un_mini_business_plan": require("../assets/academy/course-visuals/p05_c06__course_05_06_pr_parer_un_mini_business_plan.jpg"),
  "course_05_07_cr_er_un_pitch_clair": require("../assets/academy/course-visuals/p05_c07__course_05_07_cr_er_un_pitch_clair.jpg"),
  "course_05_08_construire_une_roadmap_de_lancement": require("../assets/academy/course-visuals/p05_c08__course_05_08_construire_une_roadmap_de_lancement.jpg"),
  "course_06_01_trouver_des_id_es_de_contenu_utiles": require("../assets/academy/course-visuals/p06_c01__course_06_01_trouver_des_id_es_de_contenu_utiles.jpg"),
  "course_06_02_cr_er_un_calendrier_ditorial_simple": require("../assets/academy/course-visuals/p06_c02__course_06_02_cr_er_un_calendrier_ditorial_simple.jpg"),
  "course_06_03_crire_un_post_linkedin_clair": require("../assets/academy/course-visuals/p06_c03__course_06_03_crire_un_post_linkedin_clair.jpg"),
  "course_06_04_cr_er_des_captions_instagram_efficaces": require("../assets/academy/course-visuals/p06_c04__course_06_04_cr_er_des_captions_instagram_efficaces.jpg"),
  "course_06_05_transformer_un_article_en_plusieurs_contenus": require("../assets/academy/course-visuals/p06_c05__course_06_05_transformer_un_article_en_plusieurs_contenus.jpg"),
  "course_06_06_pr_parer_une_newsletter_avec_l_ia": require("../assets/academy/course-visuals/p06_c06__course_06_06_pr_parer_une_newsletter_avec_l_ia.jpg"),
  "course_06_07_crire_une_page_de_vente_simple": require("../assets/academy/course-visuals/p06_c07__course_06_07_crire_une_page_de_vente_simple.jpg"),
  "course_06_08_garder_son_ton_de_marque_avec_l_ia": require("../assets/academy/course-visuals/p06_c08__course_06_08_garder_son_ton_de_marque_avec_l_ia.jpg"),
  "course_07_01_comprendre_ce_qui_fait_un_bon_prompt_image": require("../assets/academy/course-visuals/p07_c01__course_07_01_comprendre_ce_qui_fait_un_bon_prompt_image.jpg"),
  "course_07_02_d_crire_un_style_visuel_simplement": require("../assets/academy/course-visuals/p07_c02__course_07_02_d_crire_un_style_visuel_simplement.jpg"),
  "course_07_03_cr_er_un_logo_avec_un_prompt_pr_cis": require("../assets/academy/course-visuals/p07_c03__course_07_03_cr_er_un_logo_avec_un_prompt_pr_cis.jpg"),
  "course_07_04_cr_er_une_affiche_ou_un_visuel_promotionnel": require("../assets/academy/course-visuals/p07_c04__course_07_04_cr_er_une_affiche_ou_un_visuel_promotionnel.jpg"),
  "course_07_05_am_liorer_une_image_g_n_r_e": require("../assets/academy/course-visuals/p07_c05__course_07_05_am_liorer_une_image_g_n_r_e.jpg"),
  "course_07_06_cr_er_une_direction_artistique_coh_rente": require("../assets/academy/course-visuals/p07_c06__course_07_06_cr_er_une_direction_artistique_coh_rente.jpg"),
  "course_07_07_adapter_un_visuel_plusieurs_formats": require("../assets/academy/course-visuals/p07_c07__course_07_07_adapter_un_visuel_plusieurs_formats.jpg"),
  "course_07_08_viter_les_erreurs_courantes_en_g_n_ration_d_imag": require("../assets/academy/course-visuals/p07_c08__course_07_08_viter_les_erreurs_courantes_en_g_n_ration_d_imag.jpg"),
  "course_08_01_transformer_une_id_e_en_script_vid_o": require("../assets/academy/course-visuals/p08_c01__course_08_01_transformer_une_id_e_en_script_vid_o.jpg"),
  "course_08_02_crire_une_accroche_pour_vid_o_courte": require("../assets/academy/course-visuals/p08_c02__course_08_02_crire_une_accroche_pour_vid_o_courte.jpg"),
  "course_08_03_cr_er_un_storyboard_simple": require("../assets/academy/course-visuals/p08_c03__course_08_03_cr_er_un_storyboard_simple.jpg"),
  "course_08_04_prompter_une_ia_vid_o_r_aliste": require("../assets/academy/course-visuals/p08_c04__course_08_04_prompter_une_ia_vid_o_r_aliste.jpg"),
  "course_08_05_adapter_un_script_pour_tiktok_reels_ou_shorts": require("../assets/academy/course-visuals/p08_c05__course_08_05_adapter_un_script_pour_tiktok_reels_ou_shorts.jpg"),
  "course_08_06_pr_parer_une_voix_off_naturelle": require("../assets/academy/course-visuals/p08_c06__course_08_06_pr_parer_une_voix_off_naturelle.jpg"),
  "course_08_07_cr_er_une_vid_o_produit_simple": require("../assets/academy/course-visuals/p08_c07__course_08_07_cr_er_une_vid_o_produit_simple.jpg"),
  "course_08_08_v_rifier_la_coh_rence_d_une_vid_o_ia": require("../assets/academy/course-visuals/p08_c08__course_08_08_v_rifier_la_coh_rence_d_une_vid_o_ia.jpg"),
  "course_09_01_d_crire_une_app_clairement_une_ia": require("../assets/academy/course-visuals/p09_c01__course_09_01_d_crire_une_app_clairement_une_ia.jpg"),
  "course_09_02_cr_er_un_prompt_lovable_propre": require("../assets/academy/course-visuals/p09_c02__course_09_02_cr_er_un_prompt_lovable_propre.jpg"),
  "course_09_03_demander_une_interface_sans_casser_l_ux": require("../assets/academy/course-visuals/p09_c03__course_09_03_demander_une_interface_sans_casser_l_ux.jpg"),
  "course_09_04_crire_un_cahier_des_charges_simple": require("../assets/academy/course-visuals/p09_c04__course_09_04_crire_un_cahier_des_charges_simple.jpg"),
  "course_09_05_demander_du_code_chatgpt_ou_claude": require("../assets/academy/course-visuals/p09_c05__course_09_05_demander_du_code_chatgpt_ou_claude.jpg"),
  "course_09_06_utiliser_cursor_ou_claude_code_sans_perdre_le_co": require("../assets/academy/course-visuals/p09_c06__course_09_06_utiliser_cursor_ou_claude_code_sans_perdre_le_co.jpg"),
  "course_09_07_cr_er_un_plan_de_test_avec_l_ia": require("../assets/academy/course-visuals/p09_c07__course_09_07_cr_er_un_plan_de_test_avec_l_ia.jpg"),
  "course_09_08_corriger_un_bug_avec_une_demande_claire": require("../assets/academy/course-visuals/p09_c08__course_09_08_corriger_un_bug_avec_une_demande_claire.jpg"),
  "course_10_01_construire_un_prompt_multi_tapes": require("../assets/academy/course-visuals/p10_c01__course_10_01_construire_un_prompt_multi_tapes.jpg"),
  "course_10_02_cr_er_une_grille_d_valuation_de_r_ponse_ia": require("../assets/academy/course-visuals/p10_c02__course_10_02_cr_er_une_grille_d_valuation_de_r_ponse_ia.jpg"),
  "course_10_03_utiliser_un_agent_ia_sans_lui_donner_trop_de_lib": require("../assets/academy/course-visuals/p10_c03__course_10_03_utiliser_un_agent_ia_sans_lui_donner_trop_de_lib.jpg"),
  "course_10_04_demander_une_r_ponse_avec_raisonnement_contr_l": require("../assets/academy/course-visuals/p10_c04__course_10_04_demander_une_r_ponse_avec_raisonnement_contr_l.jpg"),
  "course_10_05_cr_er_un_workflow_ia_r_utilisable": require("../assets/academy/course-visuals/p10_c05__course_10_05_cr_er_un_workflow_ia_r_utilisable.jpg"),
  "course_10_06_faire_relire_et_am_liorer_un_prompt_par_l_ia": require("../assets/academy/course-visuals/p10_c06__course_10_06_faire_relire_et_am_liorer_un_prompt_par_l_ia.jpg"),
  "course_10_07_prot_ger_ses_donn_es_personnelles_et_professionn": require("../assets/academy/course-visuals/p10_c07__course_10_07_prot_ger_ses_donn_es_personnelles_et_professionn.jpg"),
  "course_10_08_construire_son_syst_me_de_travail_avec_ia": require("../assets/academy/course-visuals/p10_c08__course_10_08_construire_son_syst_me_de_travail_avec_ia.jpg"),
} as const;

export type AcademyLessonVisualId = keyof typeof ACADEMY_LESSON_VISUALS;

export function getAcademyLessonVisual(courseId?: string) {
  if (!courseId) return undefined;
  return ACADEMY_LESSON_VISUALS[courseId as AcademyLessonVisualId];
}